### ISSUE TITLE
Fields Incorrectly Categorized as "Deprecated"

### ISSUE THREAD

**Issue by arahansen** [apollographql/apollo-client-devtools#100]
Prior to the latest release of the apollo devtools, I had fields showing up in devtools as expected, undeprecated.

Since the latest release, all properties on what seems to be all types in my schema show up as deprecated. The only change was the apollo devtools version.

Our Person type for example, has about 20 fields all of which show as deprecated, when before none of them did:
![image](https://user-images.githubusercontent.com/8746094/35749915-ff7858ea-0807-11e8-8312-2da599e06a1b.png)

**Comment by arahansen** [comment]
I narrowed down the issue to a problem with how `graphql` is parsing `isDeprecated` fields. This problem can be resolved by upgrading the `graphql` dependency which has better handling for `isDeprecated`

**Comment by jbaxleyiii** [comment]
Can do! Thanks for debugging this!

**Comment by carlsverre** [comment]
I am hitting this issue as well with a gqlgen (https://github.com/99designs/gqlgen) schema.  All the fields on all my types are showing up as deprecated.

**Comment by justinanastos** [comment]
Thanks @carlsverre 	, can you you share a reproduction URL so I can take a look at this?

**Comment by carlsverre** [comment]
It seems to have been resolved in a recent version of gqlgen!  Will ping if I see it again with a repro.

**Comment by justinanastos** [comment]
Thank you @carlsverre 	!
