### ISSUE TITLE
[bug] Devtools never appear if initial page does not contain an Apollo Client instance

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client-devtools#1035]
**Intended outcome:**
When I navigate to a page that initializes Apollo Client in the browser, the devtools should appear even if Apollo Client is not detected in the browser when the initial page load occurs.

**Actual outcome:**
If you have an app that is purely server rendered initially, and navigate to a page that loads Apollo Client the devtools never appear. You need to refresh the browser from the page that loads Apollo on the client in order for devtools to appear.

**How to reproduce the issue:**
I reproduced this in the Next.js experimental repo's [polls-demo example](https://github.com/apollographql/apollo-client-nextjs/tree/main/examples/polls-demo).

If you start on the homepage, `/`, which is a React Server Component and navigate to the client component page, Apollo Client devtools never appear.

If you refresh the client component page, they do appear:

![CleanShot 2023-07-25 at 10 43 43](https://github.com/apollographql/apollo-client-devtools/assets/5139846/164892b3-230a-47ae-bf06-65d087b67593)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Mac OS**
 - Browser [e.g. chrome, safari] **Arc**
 - Browser version [e.g. 22] **1.0.1**
 - Extension version [e.g. 3.0] **4.1.4**

**Comment by vezaynk** [comment]
My app has delayed initializing for the graphql client, and I can't get the devtools to work :(

**Comment by jerelmiller** [comment]
I've tested this out with recent versions of the devtools and they are working much better with these environments. Since we now go into the "connected" state of the devtools when a client is registered, we no longer need to rely on a page refresh for this to work. As such I'm going to close this out as completed 🙂
