### ISSUE TITLE
Crashes when viewing optimisticResponse in cache

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client-devtools#105]
Steps:

- Network tab -> Slow 3G
- Apollo devtools -> Cache panel
- In app, trigger a mutation that has an `optimisticResponse`
- Click on the new cache item that corresponds with the `optimisticResponse`
- After a second when the server response returns, the devtools UI goes white

**Comment by justinanastos** [comment]
@lorensr I'm sorry no one responded to this issue! I'm going to close this issue out for now. IF this is still an issue with the most recent version of the devtools then please re-open the issue and include a link to a repo I can use to reproduce the error. Thank you!
