### ISSUE TITLE
Migrate to Manifest V3

### ISSUE THREAD

**Issue by alessbell** [apollographql/apollo-client-devtools#1075]
There is no exact date for when Chrome and Firefox will declare Manifest V2 to be EOL, but [in the last update](https://groups.google.com/u/0/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E?pli=1) wrote:

> We will provide sufficient migration time for developers - at least 6 months of heads-up - before beginning any experiments to turn off MV2 in the browser next year.

More details on [Chrome](https://developer.chrome.com/blog/more-mv2-transition/) and [Firefox's](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/) move to Manifest V3.

There are significant changes between V2 and V3 (see [migration guide](https://developer.chrome.com/docs/extensions/migrating/) for more details), including:

- **Migrating to a service worker**: a service worker replaces the extension's background script. This has implications like needing to use an offscreen document in order to access local storage, and moving DOM and window calls to an offscreen document too.
- **Updated APIs**: https://developer.chrome.com/docs/extensions/migrating/api-calls/
- other changes that may impact our extension

**Comment by jerelmiller** [comment]
I did a 5 min dive into switching and I quickly ran into the fact that FireFox doesn't support background service workers in v3 (https://github.com/mozilla/web-ext/issues/2532). Chrome requires background scripts to be moved into a service worker, but this mismatch is currently making this difficult.

**Comment by alessbell** [comment]
Oof, yeah. Though as someone there pointed out, that only affects `background. service_worker`, so the same script could be shipped at `background.scripts` for the FF extension.

Not great to have to ship two different manifests—and there were many other reasons the Chrome team got pushback and delayed the EOL dates—but my guess is we'll be forced to tackle this upgrade regardless of browser feature parity.
