### ISSUE TITLE
Queries get stuck after page refresh

### ISSUE THREAD

**Issue by tnrich** [apollographql/apollo-client-devtools#108]
Hey there, 

I'm finding that once a refresh occurs in my app all of the previously made queries get "stuck" in the apollo devtools queries tab. When they get stuck there no other queries get added and nothing changes as I navigate around. 

Here is a gif of this occurring from scratch. I'm on the latest version of apollo 2.

![untitled](https://user-images.githubusercontent.com/2730609/36456957-7d53e146-165c-11e8-8c1f-f63d7be02adc.gif)

As you can see in the gif, on the initial load, everything seems to be working fine, but after refreshing no other queries get added. I can confirm that this occurs for all my colleagues as well. 

I think this is very serious because it makes the devtools unusable after the initial page load.

**Comment by ramsaylanier** [comment]
👍 happens to me too

**Comment by seangransee** [comment]
Happens to me when refreshing the page, and when manually modifying the URL. After I manually change the URL, I have to close the Apollo dev tools and open it back up again.

**Comment by wesbos** [comment]
I find my whole cache says with a page reload - I need to close dev tools and re-open it to see the correct data

**Comment by wesbos** [comment]
A stop-gap solution right now is to just reload the entire frame:

![](http://wes.io/qihc/content)

**Comment by deltaskelta** [comment]
using the "reload" frame option made my life a whole lot easier for now

**Comment by nilshartmann** [comment]
As mentioned in #111 the problem also occures if you execute a query in the GraphiQL tab after a page reload.

The workaround from @wesbos works in that case by choosing "Reload Frame" in the `Documentation Explorer` column from GraphiQL or in the navigation tab at the left:

![image](https://user-images.githubusercontent.com/435073/41189546-dc3db722-6bcf-11e8-9e95-e5939ce6a931.png)

**Comment by SeanRoberts** [comment]
Is this going to be fixed at some point?  The workaround works but it adds a lot of extra clicks/overhead when debugging

**Comment by btorresgil** [comment]
Agree with other commenters, this doesn't seem to be getting enough attention given how fundamental this functionality is.  The devtools are unusable unless you reload the frame every time.  During development where refreshing the page happens every few seconds, this is extremely painful.

**Comment by THPubs** [comment]
This issue is still there. Any updates on it?

**Comment by ccpony** [comment]
Is anybody monitoring these issues?

**Comment by justinanastos** [comment]
Thank you everyone for your report and for your patience. I'm going to be looking into this very soon.

**Comment by elioschmutz** [comment]
Whats the progress of this issue?

**Comment by thomasmichaelwallace** [comment]
Out of interest, does anyone have a workaround the works in Firefox? (the devtools context menu in Firefox does not have the "refresh" option).

**Comment by meebix** [comment]
Any updates on this issue? This is a pretty big (bad) issue from a developer experience standpoint.

**Comment by ccpony** [comment]
Walked away from Apollo and dev-tools.  Project seems abandoned.  Was never ready for prime time.

**Comment by justinanastos** [comment]
I'm sorry to respond with bad news and after such a long delay @elioschmutz , @theadactyl , @meebix , and @ccpony ; we haven't had the available resources to come back and make this change. We use this tool internally so we feel the same pain as you. I'm hoping that we'll have the resources to come up with a solution in the next few months; we're always trying to do better and are always happy to hear feedback, even if it's critical feedback.

**Comment by justinanastos** [comment]
We're always looking for help with our open source libraries! Either with a PR or even an idea/recommendation on how to resolve the issue would be super helpful to me!

**Comment by btorresgil** [comment]
@ccpony What did you move to?  Been looking at alternative as well.

**Comment by wesbos** [comment]
This is still an issue for me, I have to reload the entire dev tools to see any updates to the cache.  Any work around?

having to use `console.table(__APOLLO_CLIENT__.cache.data.data)` to see if the cache has changed

**Comment by coler-j** [comment]
This is also still an issue for me `apollo@2.31.0`, @hwillson can you re-open?

**Comment by stazcp** [comment]
4 years later this is still an issue I tried using different browsers I'm using React and Apollo no NextJS

**Comment by jerelmiller** [comment]
Hey all apologies on this issue! Seems this may still be a thing so I'm going to reopen this. 

We've done a lot of work on the message passing recently to try and get some of the big stuff out of the way, but seems we still have some work to do to handle some cases that are still happening. Thanks!

**Comment by jerelmiller** [comment]
Hey all 👋 

We've done a lot of work recently to make the communication between the browser tab and the extension more reliable. https://github.com/apollographql/apollo-client-devtools/pull/1378 was released with [4.13.1](https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.13.1) which should fix the intermittent issue where data would not show up in the devtools on page reload.

As such, I'm going to go ahead and close this issue. If you are still seeing the issue while using 4.13.1 or later, please let me know and I'd be happy to reopen this issue. Thanks!
