### ISSUE TITLE
Scroll not working in Queries and Cache tabs.

### ISSUE THREAD

**Issue by agarciabz** [apollographql/apollo-client-devtools#1084]
**Intended outcome:**
I should be able to scroll down in Queries and Cache tabs.

**Actual outcome:**
No scroll var is visible. I also can't scroll down using my mouse wheel or with keyboard arrows.

**How to reproduce the issue:**
Open browser devtools, click on Apollo tab and inside Apollo Dev Tools click on Queries or Cache tabs. Try to scroll down in both list of items or results.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Microsoft Edge
- Browser version: 116.0.1938.76
- Extension version: 4.1.6

I'm facing this issue in both Chrome and Brave browsers.

**Comment by guesswhozzz** [comment]
I've the same problem 

**Desktop:**

- OS: MacOS 13.5.2
- Browser:  Chrome
- Browser version:  116.0.5845.179 
- Extension version: 4.1.6

**Comment by alessbell** [comment]
Version [4.2.0](https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.2.0) was just released and shipped to the Chrome and Firefox stores with this fix. Will close this when the releases are live, thanks!

**Comment by alessbell** [comment]
Just confirmed it's live and that it resolves this issue. Thanks all!
