### ISSUE TITLE
Load from cache loads from server

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client-devtools#115]
In GraphiQL, when I select "Load from cache", change a field on the server, and execute the query, the updated field appears in the results. (And I don't have an active polling query for this field.) Additionally, a request to the server with the query shows up in the Network tap.

devtools v2.1.2
react-apollo v2.1.1

**Comment by tushar-singh** [comment]
I can reproduce this. Additionally, I cannot see anything in queries and cache tabs (they're blank even though data does get loaded from cache in the actual app)

**Comment by justinanastos** [comment]
Thanks for the report @lorensr 	! Can you provide a reproduction? I tried to reproduce the behavior you described with Apollo's Fullstack Tutorial (https://github.com/apollographql/fullstack-tutorial). I saw that when I tried to query `LaunchDetails` in the Apollo Client Devtools , I didn't see a network request.

![](https://cl.ly/c573f7b1be5e/Screen%20Recording%202019-02-11%20at%2004.00%20PM.gif)

**Comment by hwillson** [comment]
This should no longer be an issue - thanks!
