### ISSUE TITLE
Not working! Apollo Client Devtools on Chrome latest

### ISSUE THREAD

**Issue by billnbell2** [apollographql/apollo-client-devtools#1163]
This stopped working and no longer works as a Chrome plugin. Happy to give more info. Just wanted you to know.

**Comment by jerelmiller** [comment]
Hey @billnbell2 👋 

More info would definitely be appreciated! We haven't pushed out an update since October, so its a bit difficult to know what "do

**Comment by jerelmiller** [comment]
Hey @billnbell2 👋 

Would you be able to provide more info? Its a bit difficult to know what "doesn't work" means here. Does it not load? Do you not see cache updates?

Your devtools version and Apollo Client version would also be helpful to determine what might be happening. We haven't pushed out an update to the devtools since October, so its odd that it would start failing now. Thanks!

**Comment by alessbell** [comment]
Hi @billnbell2 - another gentle ping here. Is there anything you can provide us with in the way of understanding your issue better? Screenshots and the version of the extension you're using would be helpful. We also just shipped a new minor version so you can try that out and see if it improves whatever your issue is. Thanks!

**Comment by billnbell2** [comment]
Hey! Yeah I install it fine on Chrome, but it it does not work. I don't see the plugin and no errors, nothing.

**Comment by billnbell2** [comment]
![image](https://github.com/apollographql/apollo-client-devtools/assets/147371671/abb8bfbd-f382-4a3a-bc0a-441cbc63188e)

**Comment by jerelmiller** [comment]
@billnbell2 would you be able to share how you're initializing `ApolloClient`?

**Comment by billnbell2** [comment]
Version
4.3.0

**Comment by billnbell2** [comment]
I clicked add to chrome, and cannot find it in Chrome.

![image](https://github.com/apollographql/apollo-client-devtools/assets/147371671/adea8188-9dc7-420b-800b-a872ea0716e4)

**Comment by billnbell2** [comment]
I don't see the plugin after I enable, reboot, etc.

![image](https://github.com/apollographql/apollo-client-devtools/assets/147371671/3a6a60ef-3420-41f0-bb2e-92a2dcc83a67)

**Comment by phryneas** [comment]
You will only see the plugin on pages using Apollo Client with a development build.

Do you see them e.g. when you visit https://dp0id-3000.csb.app/ ? (If that page does not load, you might need to open https://codesandbox.io/p/devbox/github/apollographql/react-apollo-error-template/tree/main/ ) before.

**Comment by billnbell2** [comment]
I do not see it on that page. I am using Mac Safari Version 17.0 (19616.1.27.211.1)


<img width="1450" alt="Screenshot 2023-12-19 at 5 22 30 PM" src="https://github.com/apollographql/apollo-client-devtools/assets/147371671/69ef5971-c250-4c0c-a302-24490e19a44c">

**Comment by jerelmiller** [comment]
@billnbell2 I'm a bit confused. You mention that you're using Safari in that screenshot, but you've opened this issue specifying that its not working in Chrome. Just want to clear up that you have indeed tried this in Chrome as well.

Unfortunately we don't Safari at the moment with the extension, so its expected that you won't see it show up there.

**Comment by billnbell2** [comment]
I meant Chrome.


<img width="305" alt="Screenshot 2023-12-19 at 5 26 23 PM" src="https://github.com/apollographql/apollo-client-devtools/assets/147371671/e7174efb-113c-43e7-9086-f627f713130c">

And here is the plugin info in Chrome:
<img width="751" alt="Screenshot 2023-12-19 at 5 25 39 PM" src="https://github.com/apollographql/apollo-client-devtools/assets/147371671/2f7833ce-0b4d-4cd9-87ec-315ebe83aa38">

**Comment by jerelmiller** [comment]
Interesting! I'm using Chrome 117.0.5938.132 (Official Build) (arm64) and it seems to be working fine.

<img width="2560" alt="Screenshot 2023-12-19 at 5 29 18 PM" src="https://github.com/apollographql/apollo-client-devtools/assets/565661/ad484faf-dcb8-451c-bd2c-31fd341e5956">


Let me see if I can update my browser!

**Comment by jerelmiller** [comment]
Ok, looks like I was on version 4.2.3 of the devtools, but once I upgraded to 4.3.0, I'm seeing the issue you are. We will see if we can take a look at this and get it fixed! Thanks for reporting.

**Comment by billnbell2** [comment]
Thanks. How to I get 4.2.3?

**Comment by jerelmiller** [comment]
@billnbell2 unfortunately I think it requires us to revert our latest change and re-release the extension. Give us a little bit of time to figure out if we can still use the latest change, but fix it not showing up.

**Comment by jerelmiller** [comment]
Hey @billnbell2 👋 

We've reverted our latest change which we believe was the cause of this issue. `v4.3.1` should be live in the Chrome and Firefox stores any time.

I'm going to go ahead and close out this issue. If you experience this again after upgrading, feel free to drop a comment and I'd be happy to reopen this issue. Thanks!
