### ISSUE TITLE
Doesn't work in latest Chromium-based MS Edge

### ISSUE THREAD

**Issue by sepsol** [apollographql/apollo-client-devtools#1168]
**Intended outcome:**

To see a tab in Edge DevTools called "Apollo"

**Actual outcome:**

Not seeing the "Apollo" tab in Edge DevTools

**How to reproduce the issue:**

Download the latest Edge and see for yourself.

**Desktop (please complete the following information):**

- OS: Microsoft Windows 11 Version 23H2 Build 22631.2861
- Browser: Microsoft Edge Version 120.0.2210.77 (Official build) (64-bit)
- Extension version: Apollo Client Devtools v4.3.0

**Comment by jerelmiller** [comment]
Hey @sepsol 👋 

It looks like we had some buggy behavior go out in `4.3.0` that caused an issue with the devtools showing up. We've reverted the change for now and released `4.3.1` that should go live in the Chrome and Firefox stores any time.

I'm going to go ahead and close out this issue. If you upgrade to `4.3.1` and are still experiencing the issue, feel free to comment back here and I'd be happy to open this back up. Thanks!

**Comment by sepsol** [comment]
Thanks! Will keep an eye out for the update and keep you posted here.

**Comment by agenceKanvas** [comment]
@jerelmiller I've updated the chrome extension and I'm using the last version of apollo client, but still not seeing Apollo tab in the console. 
I've added a .env with NODE_ENV=development and connectToDevTools: true, to the apollo client. 
I don't know what to try more that that :)

**Comment by sepsol** [comment]
@agenceKanvas it worked for me though. Strangely, I didn't have to explicitly set `NODE_ENV=development` or `connectToDevTools: true`. All I can say is make sure you're on the tab for your app and maybe restart your browser.

![image](https://github.com/apollographql/apollo-client-devtools/assets/47871887/49c947be-13a4-4af6-a77b-76bdb80bb483)

**Comment by jerelmiller** [comment]
@agenceKanvas can you verify that you're on 4.3.1 and not 4.3.0? Restarting your browser might also help.

Thanks for the confirmation @sepsol! Glad its working again for you 🙂

**Comment by agenceKanvas** [comment]
I've made a full restart and it finally showed. Thanks !
