### ISSUE TITLE
IDEA: Standalone version for React-Native. (like react-devtools) for Integration with React Native.

### ISSUE THREAD

**Issue by MichelDiz** [apollographql/apollo-client-devtools#117]
reference https://github.com/facebook/react-devtools

It would be nice to have a version similar to react-devtools. That you install globally and parses the application code. In that case would be queries end mutations.

With React-devtools I can analyze every "react" structure as if it were an injection from RN. It would be an interesting feature because apollo-client-devtools is more geared towards web applications.

Cheers

**Comment by hwillson** [comment]
See https://github.com/jhen0409/react-native-debugger (which integrates with this project - https://github.com/jhen0409/react-native-debugger/blob/master/docs/apollo-client-devtools-integration.md). Thanks!
