### ISSUE TITLE
Don't require 3rd-party cookies

### ISSUE THREAD

**Issue by nslocum** [apollographql/apollo-client-devtools#118]
Great work on the extension!

The extension currently requires allowing sites to set 3rd-party cookies. This setting is applied globally and is BIG deal. For me it's a deal breaker.

It looks like the Redux extension solved this issue by mocking localStorage when it's not available for whatever reason.
Here's their simple solution:
https://github.com/zalmoxisus/redux-devtools-extension/commit/493a4cc7fd37a39b28e02e9157c08e949d43a99a

**Comment by MariuszHenn** [comment]
this is my solution proposal https://github.com/MariuszHenn/apollo-client-devtools/commit/9c13564c55315845e6b6ceb9835d677c4804e4b6

**Comment by justinanastos** [comment]
Release in [v2.1.9](https://github.com/apollographql/apollo-client-devtools/releases/tag/v2.1.9)
