### ISSUE TITLE
Suggestion: Show latest query result data

### ISSUE THREAD

**Issue by armstrjare** [apollographql/apollo-client-devtools#12]

**Comment by stubailo** [comment]
Good idea - we should also show any errors, the current options (pollInterval, etc), and anything else we can find out about the query.

**Comment by timbotnik** [comment]
I'd also love to see a way to sort the query list by "last run" (probably also show a timestamp column) so i can see what's running as i click around the app.

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/370 - thanks!
