### ISSUE TITLE
Integration as reactotron plugin?

### ISSUE THREAD

**Issue by tonyxiao** [apollographql/apollo-client-devtools#122]
- [x] feature

Given that apollo client devtools does not currently work for react native via either chrome or react-native-debugger, how about integrating with say Reactotron? It seems to have a nice plugin API that's more amenable to extensions.

**Comment by Gongreg** [comment]
Hey, I am currently working on react-native-debugger implementation. I already have working forks, but trying to clean up the code now.

https://github.com/apollographql/apollo-client-devtools/issues/6

**Comment by fbartho** [comment]
@Gongreg that's great news! -- Does that mean that once that ships, this will be more easily ported into Reactotron? or is that just an alternative?

**Comment by Gongreg** [comment]
Hey @fbartho. Assuming reactotron works same way as react native debugger (that is running react native code in a webworker) and has a support to display chrome dev tools then yes.

**Comment by Gongreg** [comment]
Ah, just looked into it. Seems like it works not as a remote debugger? I am on mobile, so it is a little bit difficult to check.

Worst case scenario we will have support with react-native-debugger and other integrations might come after. After all, i believe having dev tools working is already a big step forward :)

**Comment by felire** [comment]
@Gongreg Hi! Is there any new about this? Will be an apollo plugin for reactotron?

**Comment by hwillson** [comment]
[React Native Debugger](https://github.com/jhen0409/react-native-debugger) integrates with this project, so I'll close this off. Thanks!
