### ISSUE TITLE
automatic UI updates via apollo-link-state? (a la Redux Dev Tools)

### ISSUE THREAD

**Issue by leebenson** [apollographql/apollo-client-devtools#124]
I have an app that uses [apollo-link-state](https://github.com/apollographql/apollo-link-state) to manage local app state, and I'm hoping to use Dev Tools to invoke UI changes when submitting mutations, just as if I'd have used a `<Mutation>` component in code.

Submitting the mutation works fine (and returns the correct data, albeit with the server request mentioned in #115), but it doesn't appear to update the app in the same way that, say, the Redux Dev Tools does.

Is there a way to get Dev Tools and the underlying app in 'sync'?

(Apologies if this has already been answered in the docs; apollographql.com is currently down for me)

**Comment by bryankennedy** [comment]
I think this may be related to this issue about the [dev tools requiring a reload to view the current cache state](https://github.com/apollographql/apollo-client-devtools/issues/121).

**Comment by hwillson** [comment]
Similar `apollo-link-state` functionality is now baked into `@apollo/client`, and is supported by these devtools. Thanks!
