### ISSUE TITLE
Intermittent connection issues when first opening dev tools

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/apollo-client-devtools#1247]
We've had a couple issues opened now (https://github.com/apollographql/apollo-client-devtools/issues/1244, https://github.com/apollographql/apollo-client-devtools/issues/1239) where users report an issue connecting to the client at first. After a refresh, the issue seems resolved.

I've now experienced myself now a few times now and think this might be a symptom of another underlying issues with the devtools communication. I think there is room for further improvement.

Unfortunately this one is a bit hard to track down as it only happens the first time before you can access logs from the devtools panel, then it seems to work reliably after connecting for the first time. I'm opening this issue to track this so that we can continue to make the devtools communication more bullet proof.

**Comment by jerelmiller** [comment]
Another comment regarding potential issues: https://github.com/apollographql/apollo-client-devtools/issues/1244#issuecomment-2019380737

Perhaps this could be due to the ugprade of the extension while devtools is open? This might invalidate the extension and prevent messages from properly connecting in the background script. Perhaps we need to build some more resiliency into the message passing between the devtools and content scripts from the background script if something disconnects (message queue perhaps?).

**Comment by jerelmiller** [comment]
Another one: https://github.com/apollographql/apollo-client-devtools/issues/1316

**Comment by paddyobrien** [comment]
I found that I need to go to the chrome task manager, kill the service work associated with the apollo inspector and restart dev tools.

**Comment by UlyssesInvictus** [comment]
> I found that I need to go to the chrome task manager, kill the service work associated with the apollo inspector and restart dev tools.

Just confirming that this worked for me as well. On 4.12.3 of the dev tools.

**Comment by jerelmiller** [comment]
I have a suspicion that its related to background updates of the devtools. This is not handled well at all right now and from the surface it just appears to hang forever. That and we don't handle connections that may have dropped from the devtools to the background script due to inactivity. 

I'm exploring both of these situations right now and hope to have a PR up sometime soon to make this work a little better. 

Thanks for your patience and letting me know at least we have an (annoying) workaround in the meantime.

**Comment by jerelmiller** [comment]
Hey all 👋 

We've done quite a bit more work shoring up the messaging in the devtools and ensuring data is sent through to the devtools more reliably. I've done quite a bit of testing with our sample app and have not seen this issue show up in some time. I used to be able to reproduce this quite frequently. 

I believe this issue has been fixed by a recently release and as such, I'm going to go ahead and close this issue. If you are seeing intermittent connection issues when opening dev tools, please let me know and I'd be happy to reopen this. Thanks!
