### ISSUE TITLE
Minor fix in the extension features

### ISSUE THREAD

**Issue by dandv** [apollographql/apollo-client-devtools#134]
"A cache inspector that displays..." should be #4 instead of #3 

![image](https://user-images.githubusercontent.com/33569/43001604-a88d2d92-8bda-11e8-8dd0-33209cf6ced1.png)

**Comment by justinanastos** [comment]
Thanks @dandv 👍

**Comment by justinanastos** [comment]
Fixed. Thank you @dandv !
