### ISSUE TITLE
getCacheKey is missing in operation context

### ISSUE THREAD

**Issue by raymondsze** [apollographql/apollo-client-devtools#136]
As title, the getCacheKey is missing in the context of resolvers. Probably due to version of apollo-client?
I can obtain the getCacheKey if I perform query or mutation by apollo-client instead of dev-tools.

**Comment by serranoarevalo** [comment]
@raymondsze  How did you fix this?

**Comment by raymondsze** [comment]
I didn't fix it. I am currently using it like this way.
```
{
  Mutation: {
      testing(root: {}, args: { id: string, value: string }, { cache }: { cache: InMemoryCache }): TestingMutation['testing'] {
        cache.writeData({
          // once this issue is resolved, here should be changed to cache.getCacheKey instead of dataIdFromObject
          id: cache['config'].dataIdFromObject({
            __typename: TESTING,
            id: args.id,
          }),
          data: { value: string },
        });
        return null;
      },
    },
}
```

**Comment by serranoarevalo** [comment]
@raymondsze Cheers! Thanks

**Comment by justinanastos** [comment]
Thanks for the report! This doesn't appear to be a devtools issue. If I'm mistaken then please comment here and I'll re-open (and ask for a full reproduction).

**Comment by moonray** [comment]
Actually, this does appear to be a problem with devtools; it's not using the same version of apollo-cache-inmemory as whichever react app it's trying to integrate with

**Comment by justinanastos** [comment]
Thanks for responding so quickly @moonray . Can you please help me with a minimal reproduction? https://github.com/apollographql/fullstack-tutorial might be a good jump off point

**Comment by justinanastos** [comment]
@moonray Can you share the versions of the packages?

**Comment by justinanastos** [comment]
@moonray I tried to reproduce this by installing old versions. I'm going to close this issue until I hear back 🤞
