### ISSUE TITLE
TypeError: can't redefine non-configurable property "__APOLLO_CLIENT__"

### ISSUE THREAD

**Issue by jerelmiller** [apollographql/apollo-client-devtools#1406]
Originally reported in https://github.com/apollographql/apollo-client-devtools/issues/256#issuecomment-2149669136

> I'm getting a similar error again, with Firefox and the Apollo dev tools extension installed.
> 
> ```
> TypeError: can't redefine non-configurable property "__APOLLO_CLIENT__"
> ```

**Comment by jerelmiller** [comment]
Hey @ianchanning 👋 

Would you mind pointing me to a reproduction step for this? I'm having trouble reproducing this myself. While I have a pretty good idea on how to fix it, I just want to be sure I'm not introducing some other side-effect in doing so. Perhaps this is caused by a background update to the extension while you're using it?

I've tried refreshing the page, navigating to a non-Apollo page, closing/reopening the devtools, navigating pages within the same app, and nothing I do seems to trigger this error. If you have any more information, that would be super helpful. Thanks!

**Comment by ianchanning** [comment]
Hi @jerelmiller sorry its quite hard to reproduce - these are the details of what I was using

- Firefox 126.0 (with https://addons.mozilla.org/en-GB/firefox/addon/apollo-developer-tools) installed
- I also just spotted we hit the error with Mobile Safari 14.0.3 too (that wasn't mine though)
- Apollo Client 3.5.10

I'm sure Apollo Client is way out of date so I didn't want to properly raise an issue.

**Comment by ianchanning** [comment]
Also bare in mind, I'm not really using the dev tools, its was installed but I hadn't configured it

**Comment by ianchanning** [comment]
I also can't recreate it on demand, sorry I can't be more helpful. I'll track the bug more closely if it appears again.

**Comment by jerelmiller** [comment]
@ianchanning no problem! I'm willing to bet it was a background update to the extension that caused it to reload the content scripts, which meant re-evaluating the [`Object.defineProperty` call](https://github.com/apollographql/apollo-client-devtools/blob/2af37e2640d00642ddc100784fdbf37a108c1b11/src/extension/tab/hook.ts#L262-L278) we have for `window.__APOLLO_CLIENT__`.

I went ahead and made this configurable, so hopefully you won't see that anymore 🙂
