### ISSUE TITLE
client.writeQuery not logged

### ISSUE THREAD

**Issue by sarink** [apollographql/apollo-client-devtools#141]
When calling `client.writeQuery`, it doesn't appear that any log or history of these writes is captured by apollo-client-devtools.

Because this is such a handy way to perform optimistic updates without submitting a mutation (for example, updating a complex model from user input, but not being ready to click the submit button yet), I think devs need this.

Thanks! Apollo's been great to me so far ❤️

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/392 - thanks!
