### ISSUE TITLE
Is it possible to use devtools for a Chrome extension?

### ISSUE THREAD

**Issue by indigoviolet** [apollographql/apollo-client-devtools#144]
I can't get the Apollo pane to show up in the popup.html devtools or background page devtools. For react devtools, they provide a standalone Electron app (https://github.com/facebook/react-devtools/tree/master/packages/react-devtools) that lets you inspect the Chrome extension's React tree.

**Comment by justinanastos** [comment]
Thanks for the request! That's a pretty slick feature `react-devtools` has that I didn't know about. I'm going to mark this as a feature request for the future!

**Comment by alexstrat** [comment]
The PR on react-devtools that added the support for Chrome extension, iframes, react-native etc. : facebook/react-devtools#91

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/382 - thanks!
