### ISSUE TITLE
[Issue] [Firefox] Scroll Issue in Apollo Client Devtools tabs

### ISSUE THREAD

**Issue by pavanmehta91** [apollographql/apollo-client-devtools#145]
- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [x] good first issue

Browser: Firefox 62
Apollo Client Dev Tools: 2.1.4
OS: MacOS Sierra: 10.12.6
Issue: Scroll inside the tabs(Queries, Mutation,Cache) does not work. It only shows objects which are in the view of the devtools

http://prntscr.com/l7g9c3
http://prntscr.com/l7g9ir
TODO: Test it in other OS

**Comment by raysuelzer** [comment]
Can confirm in firefox that the scroll bar does not work in the Cache tab.  The right scroll bar for me does work in the Queries Tab. 

Browser: 64.0b1 (64-bit)
Apollo Client Dev Tools: 2.1.4
OS:  Windows 10

**Comment by dcolthorp** [comment]
This problem affects Chrome as of version 72 as well. The Queries tab is still scrollable for me, but I'm not able to scroll in the Cache tab. (I didn't test the Mutations tab – not enough mutations to scroll in my test case.)

I've switched to Vivaldi (based on Chrome 71) in the meantime, where the Cache tab is still scrollable.

**Comment by miclud** [comment]
Same as @dcolthorp.
The mutation log is scrollable.
This could shed some light on it https://www.reddit.com/r/webdev/comments/alg8az/anyone_experiencing_issues_with_flexbox_and/
This link is posted there [Issue 927066: Flexbox rendering changed between chrome 71 and 72](https://bugs.chromium.org/p/chromium/issues/detail?id=927066)

**Comment by woahitsraj** [comment]
I signed the 2.5.5 version for firefox since the scroll bug was annoying me also. You can get it here

[apollo_client_developer_tools-2.2.5-fx.xpi](https://github.com/woahitsraj/apollo-client-devtools/releases/download/2.5.5/apollo_client_developer_tools-2.2.5-fx.xpi)

**Comment by Nohac** [comment]
I'm facing the same issue in react-native-debugger: https://github.com/jhen0409/react-native-debugger/issues/359

**Comment by hwillson** [comment]
This is fixed in 3.0 (which is being published this week) - thanks!
