### ISSUE TITLE
Chrome extension doesn't work

### ISSUE THREAD

**Issue by kaitlynbrown** [apollographql/apollo-client-devtools#146]
I've never been able to get the Apollo Client Devtools chrome extension to work. The extension shows up next to my other ones, but forever remains greyed out. I never see a tab for it in chrome devtools (I do have working tabs for React and Redux devtools though). I've tried passing the `connectToDevTools: true` as an option when constructing `ApolloClient`, but this seems to have no effect.

versions:
Chrome Version 68.0.3440.84 (Official Build) (64-bit)
apollo-client 2.4.2 (also tried with 2.3.1)

**Comment by ecbrodie** [comment]
I am also running the latest version of both React-Apollo and the Apollo DevTools, getting a blank page in the Apollo tab. I have set `connectToDevTools: true`, still nothing. I even following the [Debugging Steps](https://github.com/apollographql/apollo-client-devtools#debugging), but to no avail; my Chrome settings already allowed third-party cookies.

**Comment by smeevil** [comment]
I had this issue as well with 2.1.5, cloning the repo and loading that version works fine. Please update the extension in the chrome store :)

**Comment by JonathanYates** [comment]
Same issue for me. On 2.1.5 I just get a blank page in the Apollo Tab running against Apollo Client 2.4.9.
Please fix.

**Comment by chiedo** [comment]
Same issue for me.

**Comment by amcvitty** [comment]
Confirming I also was able to get an Apollo tab to appear by installing via the Development instructions in the README.md from master

I first uninstalled the extension from the Chrome store, and I needed to restart Chrome after I'd installed the new one

**Comment by justinanastos** [comment]
Let's give this a shot using the same repo. If you setup https://github.com/apollographql/fullstack-tutorial per its instructions, are you able to see the chrome extension?

**Comment by justinanastos** [comment]
In an effort to consolidate the conversation of the extension not showing up, i'm going to close this ticket and move the conversation to #142. https://github.com/apollographql/apollo-client-devtools/issues/142#issuecomment-461914592
