### ISSUE TITLE
i am using  "@apollo/client": "^3.10.8", and i am not be able to connect to apolo dev tool 

### ISSUE THREAD

**Issue by frosty1222** [apollographql/apollo-client-devtools#1465]
### Apollo Client Devtools version
4.17.3

**Comment by jerelmiller** [comment]
Hey @frosty1222 👋 

Are you setting [`connectToDevtools`](https://www.apollographql.com/docs/react/api/core/ApolloClient#apolloclientoptions-connecttodevtools) by chance? If not, are you still having troubles connecting after this is set?

```ts
new ApolloClient({ connectToDevtools: true })
```

**Comment by jerelmiller** [comment]
Hey @frosty1222 👋 

Since I haven't heard back, I'm going to assume you've been able to get this to work so I'm going to go ahead and close this issue. Please let me know if you're still experiencing issues and I'd be happy to help figure out what might be happening here.

**Comment by frosty1222** [comment]
Yes
