### ISSUE TITLE
Console debug project 1

### ISSUE THREAD

**Issue by Creativityliberty** [apollographql/apollo-client-devtools#1541]
### Apollo Client Devtools version
4.18.9

**Comment by phryneas** [comment]
?

**Comment by jerelmiller** [comment]
Hey @Creativityliberty 👋 

Not sure if you opened this by mistake, but seeing as there is no information, I'm going to assume it is. I'd be happy to open this issue again if you do in fact have an issue that you'd like us to look into. Thanks!
