### ISSUE TITLE
useQuery option enabled: false not working at all

### ISSUE THREAD

**Issue by leje512** [apollographql/apollo-client-devtools#1543]
**Intended outcome:**

The query should only be called, when enabled is set to true. If this is not reproducable, let me know and I'll try get a minimum reproducable version. Also if I'm doing something wrong, please tell me!:) 

**Actual outcome:**

The Query is always called, no matter the value in enabled. The value is shown correctly in the Apollo and GraphQL Dev Tools, so it doesn't seem like a Vue or ref problem.
Apollo Dev Tools:
<img width="403" alt="image" src="https://github.com/user-attachments/assets/92329af7-4c4f-44bb-b595-63216ed7a0c2">
GraphQL Dev Tools:
<img width="336" alt="image" src="https://github.com/user-attachments/assets/2ec3650f-6618-4f52-aecb-6c6428701c88">

**How to reproduce the issue:**

These are the code snippets I tried.

````
const isCorrectRole = computed(() => meStore.me?.role === UserRole.Admin)
const { result } = useQuery(findThingById, () => ({
  fetchPolicy: 'cache-and-network',
  enabled: isCorrectRole.value,
}))
````

I also tried to hardcode enabled, and got the same results:
````
const { result } = useQuery(findThingById, () => ({
  fetchPolicy: 'cache-and-network',
  enabled: false,
}))
````

```
const { result } = useQuery(findThingById, {
  fetchPolicy: 'cache-and-network',
  enabled: false,
})
```

**Desktop:**

- OS: macOS Sequoia 15.0
- Browser: Chrome (also tested in Safari)
- Browser version: 130.0.6723.59
- Extension version: 
    - @vue/apollo-composable: ^4.2.1
    - vue: ^3.4.37
    - graphql: ^16.9.0

**Comment by jerelmiller** [comment]
Hey @leje512 👋 

I'm not super familiar with the Vue integration, but it looks like that `enabled` property is passed as the third argument to `useQuery`: https://apollo.vuejs.org/api/use-query.html

`enabled` is not core Apollo API option so it looks like this is a Vue integration thing. Could you try using the third argument instead and see if that helps?

**Comment by leje512** [comment]
Ah, thats right. Thanks! That worked:

````
const isCorrectRole = computed(() => meStore.me?.role === UserRole.Admin)
const { result } = useQuery(findThingById, {},  () => ({
  fetchPolicy: 'cache-and-network',
  enabled: isCorrectRole.value,
}))
```
