### ISSUE TITLE
Apollo Firefox add-on

### ISSUE THREAD

**Issue by takticcode** [apollographql/apollo-client-devtools#155]
_Originally posted by @takticcode in https://github.com/apollographql/apollo-client-devtools/issues/73#issuecomment-441026986_

**Comment by hwillson** [comment]
Please see https://github.com/apollographql/apollo-client-devtools/issues/73#issuecomment-444497422. In a nutshell - devtools supports FF, but has been pulled by FF. We're working on a fix, and will track all progress in #73. Thanks!
