### ISSUE TITLE
hu

### ISSUE THREAD

**Issue by gititbip** [apollographql/apollo-client-devtools#1551]
### Apollo Client Devtools version
4.18.9

**Comment by gititbip** [comment]
An Apollo Client instance was not found, either because an Apollo Client instance was never created, or because it could not be discovered. You can often solve this issue by setting the [connectToDevTools option](https://www.apollographql.com/docs/react/api/core/ApolloClient#apolloclientoptions-connecttodevtools) in your ApolloClient instance to true.

If you've already set the [connectToDevTools option](https://www.apollographql.com/docs/react/api/core/ApolloClient#apolloclientoptions-connecttodevtools), please try one of the following suggestions or click the Retry button to look for the client again.

Please [create an issue](https://github.com/apollographql/apollo-client-devtools/issues/new?body=%3C!--%20Please%20provide%20a%20detailed%20description%20of%20the%20issue%20you%20are%20experiencing.%20It%20is%20most%20helpful%20if%20you%20are%20able%20to%20provide%20a%20minimal%20reproduction%20of%20the%20issue.%20--%3E%0A%0A%23%23%23%20%60%40apollo%2Fclient%60%20version%0A%3C!--%20Please%20provide%20the%20version%20of%20%60%40apollo%2Fclient%60%20you%20are%20using.%20--%3E%0A%0A%23%23%23%20Apollo%20Client%20Devtools%20version%0A4.18.9&labels=%F0%9F%90%9E+bug) if you have followed the suggestions and continue to see this message. This could be a bug with Apollo Client Devtools.

**Comment by phryneas** [comment]
Hi @gititbip,
I fear we'll need a bit more information to be able to help you :)

* what of the suggestions did you already try?
* are you shipping a development build of Apollo Client?
* are you using iframes or anything like that?
* could you share your client setup code?

**Comment by jerelmiller** [comment]
Hey @gititbip 👋 

Since we haven't heard back, I'm going to go ahead and close this issue. Please chime in if you need additional help. Thanks!
