### ISSUE TITLE
Add saving/restoring GraphiQL queries

### ISSUE THREAD

**Issue by iki** [apollographql/apollo-client-devtools#16]
Enhancement proposal: It would be highly useful to be able to:
- save current GraphiQL query with variables, with editable save-name defaulting to given query/mutation name
- list saved queries for current endpoint, sorted by date from newest, or by save-name
- load selected saved query in the list
- delete selected saved query in the list
- rename selected saved query in the list
- save loaded and updated query with variables
- save loaded and updated query with variables under new name (keeping the old save intact)
- rename the currently saved/loaded query
- optionally import/export saved queries for current endpoint

**Comment by stubailo** [comment]
This is a great idea! I think we can put those in `localStorage`, I'd be happy to accept a PR for this feature.

I think just the first 4 would be a good starting point:

- save current GraphiQL query with variables, with editable save-name defaulting to given query/mutation name
- list saved queries for current endpoint, sorted by date from newest, or by save-name
- load selected saved query in the list
- delete selected saved query in the list

Let me know if you would like to work on this, and if I can help!

**Comment by tlvenn** [comment]
Why not simply leverage [graphiql-workspace](https://github.com/OlegIlyenko/graphiql-workspace), it provides pretty much all of the above and more:

![graphiql-workspace](https://raw.githubusercontent.com/OlegIlyenko/graphiql-workspace/master/screenshot.png)

**Comment by tlvenn** [comment]
@stubailo what do you think ?

**Comment by tlvenn** [comment]
Any feedback on leveraging graphiql-workspace guys ? Thanks.

**Comment by tnrich** [comment]
@tlvenn that seems like a great idea to me!

**Comment by stubailo** [comment]
I think this is a good idea, but it seems like a lot of the UI from that screenshot isn't necessary in the devtools, specifically the stuff with URL/headers.

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/371 - thanks!
