### ISSUE TITLE
Publishing as npm module

### ISSUE THREAD

**Issue by Gongreg** [apollographql/apollo-client-devtools#160]
Hello, I would like to know, would it be possible to publish apollo-dev-tools as a npm module so it could be included as a dependency in [react-native-debugger](https://github.com/jhen0409/react-native-debugger)? We need to use some code (backend code of apollo devtools) inside the debugger itself, to support apollo dev tools for react-native.

A slightly offtopic question, but maybe you know what exactly the UUID is used here for? https://github.com/apollographql/apollo-client-devtools/blob/dc0d97f42e1223ea80e464bdc7aa518006a23c07/src/backend/checkVersions.js 

I am having issues with this part of code since it uses localStorage, but localStorage is not available inside webworkers (react native runs in webworker).

Also here is PR for implementing apollo dev tools for react native.  https://github.com/jhen0409/react-native-debugger/pull/298

**Comment by danilobuerger** [comment]
@hwillson could you take a look at this please so we can finally get react-native dev tool support working? It should be easy to publish this?

**Comment by Gongreg** [comment]
It is holidays season now :) Lets hope to release it in beginning of January :)

**Comment by hwillson** [comment]
Thanks for heading up this initiative @Gongreg! We should be able to do this. The Apollo team is a bit light this week due to the holidays, but I've flagged this for discussion when everyone gets back next week.

**Comment by Gongreg** [comment]
Hey @hwillson,
Maybe you have any news?

**Comment by Gongreg** [comment]
Hey @hwillson, I would really like to move this forward.
I saw a lot of positive feedback from community, the sooner we release it the better :)

**Comment by Gongreg** [comment]
Hello @hwillson,
Writing as a reminder. Is there anything I can do to help?

**Comment by hwillson** [comment]
Hi @Gongreg - we're transitioning repo management responsibilities a bit internally. @cheapsteak and @justinanastos are going to help get outstanding devtools issues under control, PR's reviewed/merged, and work on improving devtools as a whole. Both this request and your great PR https://github.com/apollographql/apollo-client-devtools/pull/165 will be reviewed shortly. Thanks!

**Comment by Gongreg** [comment]
Hey, @cheapsteak
Regarding uuid everything is already solved in the PR I’ve created. It is referenced inside this issue.

**Comment by Gongreg** [comment]
Since it is published I am closing the issue, thanks!
