### ISSUE TITLE
Doesn't seem to work in Canary

### ISSUE THREAD

**Issue by slikts** [apollographql/apollo-client-devtools#161]
I'm using Chrome Canary 73.0.3657.0, and the Apollo tab doesn't show up in devtools. It works with the same site in Chrome 70.0.3538.110, however.

Extension version: 2.1.5

**Comment by justinanastos** [comment]
Thanks for the report @slikts . I just tried devtools with the latest Canary (74.0.3702.0). I used the latest fullstack tutorial repo (https://github.com/apollographql/fullstack-tutorial) and a fork that uses the latest prod versions of the repos (https://github.com/justinanastos/fullstack-tutorial/tree/justin/apollo-pre-2.5) and Apollo Client DevTools was functional. Can you please try either of these projects and see if they work?

If they do work and you are still having trouble with a local project, please respond to this ticket and I'll re-open it.
