### ISSUE TITLE
Add multiple GraphiQL tabs

### ISSUE THREAD

**Issue by iki** [apollographql/apollo-client-devtools#17]
It would be highly useful to have the possibility to run multiple different queries on the developed site. In this aspect, it relates to a complementary ability to save/load GraphiQL queries in #16. 

The implementation could be done e.h. using standard tabbed interface with tabs named after the queries/mutations in them, or `<unnamed>` for tabs with no named query yet.

**Comment by stubailo** [comment]
Is this more useful than simply being able to load queries quickly? Is there a benefit to seeing two results at once?

**Comment by iki** [comment]
@stubailo I'm working on apps that use lots of queries. Now I play with parameters and structure of few queries and need to be able to switch between them quickly. The difference of proposed solution is one tab click versus having to save the current query (often under some new name as I do not want to overwrite original query with current temporarily modified parameters), load another query and run it. So yes, it's only about speed, but the speed difference is significant, the second solution is not effectively usable.

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/372 - thanks!
