### ISSUE TITLE
Not working if typeDefs added to apollo-link-state

### ISSUE THREAD

**Issue by RealSilo** [apollographql/apollo-client-devtools#174]
I've been using the devtools with apollo-link-state without any problems so far.

I had to do a frontend type definition for nested attributes so I added the `typeDef` option to `withClientState`. The app is still working fine, but the devtools throws an error:

![screen shot 2019-02-06 at 15 19 34](https://user-images.githubusercontent.com/10554687/52380695-a7dcd400-2a23-11e9-94cd-9ade0ea757e8.png)

Old setup with which the devtools was working:

`const stateLink = withClientState({
  cache,
  resolvers: { ... },
  defaults: { ...}
});
`

New setup with which the app works but the devtools doesn't

`const typeDefs = 'type FilterType {
    lastContactedBy: String
    lastContactedDateStart: String
    lastContactedDateEnd: String
  }';`

`const stateLink = withClientState({
  cache,
  resolvers: { ... },
  defaults: { ...},
  typeDefs
});
`
Any ideas?

**Comment by justinanastos** [comment]
Thanks for the report @RealSilo . The issue of having client-side `typeDef` causing issues with GraphiQL's introspection is definitely an issue (https://github.com/apollographql/apollo-client-devtools/issues/132). My understanding is that the rest of the devtools _will_ work, just not the introspection query. Does the rest of the devtools work?

I'm going to close this as a duplicate. If there are other parts of the devtools that you see that aren't working, please ping me here with a reproduction and I'll re-open the issue!
