### ISSUE TITLE
Crashes when viewing optimisticResponse in cache

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client-devtools#175]
Reopening #105

## Repro: 

Client: https://github.com/lorensr/repro-105
Server: https://codesandbox.io/s/qmj608j1q 

## Start:

![image](https://user-images.githubusercontent.com/251288/52511334-7dc71580-2bcd-11e9-815c-db5b6ac5f258.png)

## Middle:

![image](https://user-images.githubusercontent.com/251288/52511340-86b7e700-2bcd-11e9-8459-a8771cd8a909.png)

## End:

![image](https://user-images.githubusercontent.com/251288/52511348-8c153180-2bcd-11e9-95ec-bd16bdffa297.png)

**Comment by justinanastos** [comment]
Thank you for re-opening the issue and providing the @lorensr 	! I'll take a look at this!

**Comment by hwillson** [comment]
This should be fixed in 3.0 (which is being published this week) - thanks!
