### ISSUE TITLE
Show GraphQL Errors

### ISSUE THREAD

**Issue by SachaG** [apollographql/apollo-client-devtools#18]
My main use case for Redux Devtools when working with Apollo is for viewing GraphQL query errors (which are not surfaced as regular JavaScript errors and also don't get thrown with any meaningful information on the server):

![https://d3vv6lp55qjaqc.cloudfront.net/items/2R2P1y0P0S1K1J3o2c3p/Screen%20Shot%202017-01-18%20at%2010.28.04.png?X-CloudApp-Visitor-Id=9292ee42fa5c7b5a4aea538793ce9914&v=46272b7f](https://d3vv6lp55qjaqc.cloudfront.net/items/2R2P1y0P0S1K1J3o2c3p/Screen%20Shot%202017-01-18%20at%2010.28.04.png?X-CloudApp-Visitor-Id=9292ee42fa5c7b5a4aea538793ce9914&v=46272b7f)

Since displaying these errors using the Redux Devtools requires drilling down multiple levels, it'd be super helpful if the Apollo Devtools could surface them in an easier way. As far as I can tell there's currently no way to see errors, even in the queries pane.

**Comment by stubailo** [comment]
I think it should be quite easy to display the errors in the queries pane since it's just a matter of reading from the store. Might be an easy PR, want to take a stab at it?

**Comment by SachaG** [comment]
I'm a bit busy right now so I don't want to claim this if somebody else wants to work on it, but I'll let you know if I do find the time. I do have a few ideas on what I'd like to see (for example, highlight the queries tab in red if a query has errors).

**Comment by stubailo** [comment]
Yeah that would be a great improvement.

**Comment by daniman** [comment]
This has been added, thanks to #25!

**Comment by SachaG** [comment]
Oh that's great! Nice work :)
