### ISSUE TITLE
Link to download firefox extension doesnt work

### ISSUE THREAD

**Issue by dnafication** [apollographql/apollo-client-devtools#186]
![image](https://user-images.githubusercontent.com/6381587/53212129-d13e6680-3697-11e9-812c-3c7039cb33a9.png)

![image](https://user-images.githubusercontent.com/6381587/53212173-0ea2f400-3698-11e9-8712-88470e37a725.png)

**Comment by dragan1810s** [comment]
It was taken down, because of eval usage

**Comment by justinanastos** [comment]
Correct @dnafication and @dragan1810s , we're temporarily off the Firefox store. We're using _almost_ the same eval usage as the React devtools (that this extension was originally based on). We've reached out to Firefox and never heard back. I'll be investigating removing all `eval` use in the future and hopefully that'll land is back in the Firefox store.

In the meantime I'll update the readme to reflect that.

**Comment by pho3nixf1re** [comment]
Is there another way to use this with Firefox? Like a download attached to the release?

**Comment by pho3nixf1re** [comment]
Instructions in this thread: https://github.com/apollographql/apollo-client-devtools/issues/73#issuecomment-542604418
