### ISSUE TITLE
Can't scroll in Chrome

### ISSUE THREAD

**Issue by RoberMac** [apollographql/apollo-client-devtools#187]
![image](https://user-images.githubusercontent.com/4065233/53325990-774fd200-391f-11e9-9937-4b74d34547df.png)

As screenshot above, I cannot scroll down in Apollo's tab.

**Comment by justinanastos** [comment]
Thanks @RoberMac ! That's totally a bug! When text is selected in the left pane I can't scroll the list either.

**Comment by nick** [comment]
I'm seeing this too which is making the Cache tab virtually useless right now 😬

**Comment by justinanastos** [comment]
@nick Is this happening just when text in the list is selected?

**Comment by nick** [comment]
No it doesn't scroll for me whether text is selected or not. #145 looks to be related

**Comment by scfoxcode** [comment]
I encountered this today and have a temporary fix.

1. Open the tools and go to the cache view
2. In the right half of the window, right click and inspect
3. <div class="inspector-main"> should be selected.
4. Add height: 100%; to this element

**Comment by keithrobichaud** [comment]
👍

**Comment by hwillson** [comment]
https://github.com/apollographql/apollo-client-devtools/pull/193 has been merged and is now available via version 2.2.2 of the devtools. Thanks all!

**Comment by azsuth** [comment]
This issue is occurring again, version 2.2.3.

**Comment by sam711** [comment]
> This issue is occurring again, version 2.2.3.

I ran into this issue as well, as a temporary workaround I'm using Vivaldi, scrolling works fine in that browser.

**Comment by AlexGodard** [comment]
Happening here as well.

**Comment by bmviniciuss** [comment]
Using version 2.2.3 on Chrome's `Version 76.0.3809.87 (Official Build) (64-bit)`.
I've found a similar fix as @scfoxcode instead of adding `height: 100%` to `<div class="inspector-main">` add to the div `<div class="inspector-body">`.

![Screenshot_20190808_223515](https://user-images.githubusercontent.com/20448523/62747896-ce101a80-ba2c-11e9-8bcc-83d9b244f6ac.png)

**Comment by gohulk** [comment]
Cache tab is not scrollable  using this settings 
2.2.4 and chrome Version 76.0.3809.100 (Official Build) (64-bit) 

Can you please fix it soon

**Comment by GasimGasimzada** [comment]
You also need to add `overlow: scroll` to `.inspector-panel .inspector-body`

**Comment by fgiarritiello** [comment]
This is still a blocking issue.

**Comment by oumad** [comment]
Still getting this issue.
Version : 2.2.4
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by jdpaterson** [comment]
This is still an issue. Have to edit the inspector and add height: 100% to .inspector-body everytime I need to use the devtools.

**Comment by oumad** [comment]
It's a bit more complicated than that for me since I'm using it with electron, so it's not that simple for me to just inspect and change the height to 100%.

**Comment by hwillson** [comment]
2.2.5 was released yesterday and should fix this issue. Thanks!
