### ISSUE TITLE
Publish the latest version to NPM

### ISSUE THREAD

**Issue by jhen0409** [apollographql/apollo-client-devtools#192]
Hi, it looks like the NPM package of apollo-client-devtools is still on [`v2.1.6`](https://www.npmjs.com/package/apollo-client-devtools). Would be great if the latest version published to NPM.

We've issue like https://github.com/jhen0409/react-native-debugger/issues/332, it should be fixed in newer versions.

**Comment by yodaheis** [comment]
v2.2.0 is already published, covering the bug fixes related to cache.

**Comment by hwillson** [comment]
2.2.3 has been published to npm. Thanks!
