### ISSUE TITLE
Icon not visible in chrome dark theme

### ISSUE THREAD

**Issue by SebSchwartz** [apollographql/apollo-client-devtools#194]
The icon in the address bar (in the extension area next to it) is not visible when using chrome with the dark theme.

May be a good idea to put a white icon for this config.

Screenshot: (it should be the right icon)
![image](https://user-images.githubusercontent.com/1962758/55162836-f0358a00-5168-11e9-862d-f819fafe82b7.png)

**Comment by jcpmmx** [comment]
Can anyone point me to where the icon foreground color is set?
For Chrome dark theme, it could be set to white or light blue instead of current dark blue.

**Comment by SebSchwartz** [comment]
I think it should be in the manifest: https://github.com/apollographql/apollo-client-devtools/blob/41a0930b133752ae5e6b3a9e021018d1bbdaad6e/shells/webextension/manifest.json

So they are hardcoded images...

**Comment by hwillson** [comment]
The next major version of devtools (3.0) is almost ready, and has light/dark mode support. Thanks!
