### ISSUE TITLE
devtools.apollodata.com request leaks the URL of page you're on

### ISSUE THREAD

**Issue by odensc** [apollographql/apollo-client-devtools#198]
Hi, I'd like to report a bit of a privacy issue. The extension sends a request to `devtools.apollodata.com` looking for CompatibilityMessages, whenever you're on a page where Apollo devtools are enabled. This request leaks the URL of the page you're on in the `Referer` and `Origin` headers.

Meaning that you (Apollo) could possibly be saving this data, probably not, but there's no way to know. It'd be great if this request could be made without that data included, or at least only when the extension is actually in use.

Possible fixes:

* Make the request in a background/panel page instead of the context of the actual page, making the Origin be `chrome-extension://......` rather than the page URL.

* Or, only make the request when the Apollo tab is opened in the devtools. This would be less preferable but would stop most inadvertent leakage.

**Comment by hwillson** [comment]
Thanks @odensc - let's just remove the phone home compatibility check completely. We can determine Apollo Client compatibility using other methods, so I've removed the check (and will be deploying a new version shortly).
