### ISSUE TITLE
Ability to switch between multiple configured clients

### ISSUE THREAD

**Issue by tgjorgoski** [apollographql/apollo-client-devtools#20]
I'm experimenting with Apollo in the context of Angular 2 app. I connect to multiple graphql end-points , so I have configured multiple clients using ApolloModule.forRoot(provideClients).
Not sure if this is possible, but it would be nice if devtools shows a drop down showing available clients to use, whatever the current context in the webapp might be.

**Comment by zry656565** [comment]
`react-apollo` needs this feature too. Please! :joy:

**Comment by hwillson** [comment]
Migrated to https://github.com/apollographql/apollo-client-devtools/discussions/373 - thanks!
