### ISSUE TITLE
GraphiQL Overhaul Invite

### ISSUE THREAD

**Issue by acao** [apollographql/apollo-client-devtools#200]
Hey friends!

Wanna join us in the GraphiQL overhaul effort? Towards 1.0? 🎂

https://github.com/graphql/graphql-wg/issues/136

Maybe you can help us architect it better for use cases like yours

**Comment by hwillson** [comment]
Thanks @acao - Apollo is definitely interested. I'll add more details in https://github.com/graphql/graphql-wg/issues/136. Thanks again!
