### ISSUE TITLE
Automate npm publish

### ISSUE THREAD

**Issue by Gongreg** [apollographql/apollo-client-devtools#202]
Hello,
The npm version of apollo-client-devtools is still locked to 2.1.6 .

Could anyone look into it? Also it would be great if version publish was automated, so React Native users wouldn't be left behind.

**Comment by Gongreg** [comment]
@cheapsteak, @justinanastos.

Can we get any news regarding this? It is a big bummer that we can't give RN users the latest version.

If you cannot do an npm release could you at least tell us? Then we will just release it ourselves or do some other workaround.

**Comment by Gongreg** [comment]
@hwillson, pinging you too. Not sure who is maintaining the repo atm :)

**Comment by hwillson** [comment]
Thanks for the heads up @Gongreg, and sorry about the publish to npm being missed. I'm about to publish a new browser version, and will make sure the npm version is published at the same time. I'll also make sure we get the publish to npm step added into our manual steps for now, until we figure out a better approach.

**Comment by hwillson** [comment]
2.2.3 has been published to npm. Thanks!
