### ISSUE TITLE
Apollo tab doesn't show up in DevTools

### ISSUE THREAD

**Issue by sedubois** [apollographql/apollo-client-devtools#21]
For some reason, I used to be able to see Apollo in Chrome DevTools, but it doesn't appear any more. I tried with my own Graphcool project and with the next-apollo example: https://next-with-apollo.now.sh (`apollo-client@^0.7.3` and `react-apollo@^0.8.1`, see code: https://github.com/zeit/next.js/tree/master/examples/with-apollo). Reinstalling the extension didn't help.

<img width="972" alt="screen shot 2017-02-21 at 15 54 11" src="https://cloud.githubusercontent.com/assets/4217871/23167761/5686790c-f84e-11e6-9c5f-6fed17ebbf2b.png">

<img width="972" alt="screen shot 2017-02-21 at 15 54 52" src="https://cloud.githubusercontent.com/assets/4217871/23167777/60db5026-f84e-11e6-9a61-406962759f90.png">

**Comment by kachkaev** [comment]
Just faced the same issue and then noticed that I had `connectToDevTools`option missing in the Client. E.g.L `new ApolloClient({ connectToDevTools: true });`.

In your case it's in [`lib/initClient.js`](https://github.com/zeit/next.js/blob/01cc89845040828c6e1f2bc053ff9c853d1635c5/examples/with-apollo/lib/initClient.js)

**Comment by sedubois** [comment]
Ah indeed that was the issue, thanks. It's interesting because I don't think I ever used this config flag before... 

I added this, due to SSR: `connectToDevTools: process.browser`.

**Comment by stubailo** [comment]
Yeah right now the default is to check if `process.env.NODE_ENV` is not `production`, so maybe this somehow got set in your environment.

**Comment by sedubois** [comment]
Ah yes, indeed. In very early stages I was deploying to the Now platform and didn't set NODE_ENV.

**Comment by yanisurbis** [comment]
@stubailo Is there any site to check my extension is working fine? =)
