### ISSUE TITLE
Feature request: Keep the selected tab opened when page reloading

### ISSUE THREAD

**Issue by danieldias51** [apollographql/apollo-client-devtools#211]
When I'm developing something that uses the apollo store, I usually have the store tab opened on the devtool to watch the state being update, but everytime I change something on the code and the app reloads, I've to select again the store tab and scroll to the key I was watching.

It would be awesome if the least the tab opened could kept the same between app reloads.

If you think this is a wanted feature, let me know, I would be happy to contribute :)

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/383 - thanks!
