### ISSUE TITLE
Client does not appear in Chrome

### ISSUE THREAD

**Issue by steelx** [apollographql/apollo-client-devtools#213]
I'm using Mac Chrome version 
`Version 75.0.3770.100 (Official Build) (64-bit)`

Client Version `2.2.3`

Apollo client has suddenly stopped working. shows blanks.

Whether I keep `connectToDevTools: true,` or don't include it, there is no effect. In any case `window.__APOLLO_CLIENT__` is available in console.

npm package `"react-apollo": "^2.1.4",`

**Comment by aujlambkar** [comment]
Chrome version 74.0.3729.169  is also facing the same issue

**Comment by olleblom** [comment]
Latest Debian stable: Linux xxx 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
Latest google-chrome-beta: Version 76.0.3809.80 (Official Build) beta (64-bit)
    apollo-cache-inmemory "1.6.2"
    apollo-client "2.6.0"
DevTool version: 2.2.3

I have uninstalled all extensions except those shipped with the browser (Google's own).

Every time the DevTool extension tries to connect to the apollo client in my app I get:
[15214:15214:0725/122508.346161:ERROR:CONSOLE(1)] "TypeError: Cannot read property '__schema' of undefined", source: chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js (1)
[15214:15214:0725/122508.347075:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Cannot read property '__schema' of undefined", source: chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/devtools.js (1)

**Comment by raysuelzer** [comment]
Issue began today for me. Apollo dev tools is not showing in the developer toolsite. 

Chrome version: 
Version 76.0.3809.132 (Official Build) (64-bit)

DevTool Version: 2.2.4

**Comment by raysuelzer** [comment]
Update: it actually only appears to work when connected to localhost. Perhaps this might actually be a result of some treeshaking that Angular 8 is doing which removes the ability for the client to connect to the client if the code is built in production mode.

**Comment by laij84** [comment]
I've tried both the chrome store webextension and also cloning the repo and building it locally. The apollo tab is just blank. 

Chrome Version 76.0.3809.132 (Official Build) (64-bit)
Apollo-Client-Devtools: 2.2.4
Apollo-Client: 2.6.4

**Comment by brentmclark** [comment]
For anyone using `apollo-link-rest` exclusively (i.e. they do not have a `graphql` server at all) please have a look at #228.

**Comment by peterawlings** [comment]
I'm getting the same problem - apollo tab blank
Version 78.0.3904.87 (Official Build) (64-bit)

`devtools.js:1 TypeError: Cannot read property '__schema' of undefined`

**Comment by mahmoudkhalafallah** [comment]
There is a conflict between React Dev Tools and Apollo Dev Tools, I tried to disable React Dev Tools and restart chrome dev tools and Apollo tab showed up.

**Comment by samithf** [comment]
Disable react dev tools and refresh, Apollo working fine, maybe there is a conflict between two of them

**Comment by avinoamsn** [comment]
I'm having a similar issue, but for me `window.__APOLLO_CLIENT__` returns `undefined`, even with `connectToDevTools: true` in the constructor. @samithf's suggestino did not work.

**Comment by sanderkooger** [comment]
> There is a conflict between React Dev Tools and Apollo Dev Tools, I tried to disable React Dev Tools and restart chrome dev tools and Apollo tab showed up.

This works for me, There must be a conflict with the react and apollo tooling.

**Comment by jcreighton** [comment]
This should be resolved as of the latest release (2.3.1).

**Comment by ohsofoxy273** [comment]
Disabling React Dev Tools didn't help. Then I disabled React, Mobx, and Meteor dev tools, then Apollo showed up; they don't all play nicely together.

**Comment by JuanmaMenendez** [comment]
One reason you don't see the "Apollo" tab is that maybe you are inspecting production (npm run build) and not the development mode (npm run dev)

**Comment by soon-nl** [comment]
omg wth. disabling react dev tools worked for me. that's weird....

**Comment by mankinchi** [comment]
+1 on the disabling react dev tools. Why is this issue closed? This hasn't been solved

**Comment by f0-x** [comment]
Disabled the React Dev Tools still, the Apollo tab doesn't appear. 
Windows 10 Google Chrome Dev Version 106.0.5231.2 (Official Build) dev (64-bit).

**Comment by SadmanYasar** [comment]
Facing this issue. Disabled all the extensions except Apollo devtools but the chrome dev tools doesn't show on my React app. However on Apollo studio it is shown on the chrome dev tools.

**Comment by MuizNadeem** [comment]
Started to face this problem from about a week now. It now works after adding `connectToDevTools: process.env.NODE_ENV !== 'production'` line in ApolloClient constructor of my react app. Doesn't conflict with react-dev tools extentions.

**Comment by forrestwilkins** [comment]
Thank @MuizNadeem. Setting `connectToDevTools` worked for me as well. Disabling other extensions made no difference in my case.
