### ISSUE TITLE
Can't scroll in Apollo dev tool's explore in react-native-debugger

### ISSUE THREAD

**Issue by arrygoo** [apollographql/apollo-client-devtools#214]
After updating to 0.9.9, the explorer field is added to Apollo which is awesome, however if the list is too long you can scroll down to see the rest of the queries.
![image](https://user-images.githubusercontent.com/965429/59778910-5708a200-9285-11e9-8989-4871380e4de3.png)

**Comment by RIP21** [comment]
+1

**Comment by RageOfJustice** [comment]
Still an issue in react-native-debugger

**Comment by Gongreg** [comment]
Hey @RageOfJustice, could you open the issue inside react-native-debugger? The dependency probably wasn't updated yet.
