### ISSUE TITLE
Cache tab is empty

### ISSUE THREAD

**Issue by mvestergaard** [apollographql/apollo-client-devtools#215]
The cache tab is completely empty for me, all the other tabs seem to work fine
![image](https://user-images.githubusercontent.com/2027834/60395704-ce68ec00-9b37-11e9-9820-ad128ec743ff.png)

Is this some sort of known bug, and if not. Do you have any idea what could be causing it?
No errors are shown in the console or anywhere, so there's not much to go on.

**Comment by mvestergaard** [comment]
This resolved itself somehow

**Comment by toddgeist** [comment]
I have this problem all the time, with my Next.js app. No idea what it happens

**Comment by davscro** [comment]
@toddgeist +1 with my Next.js app :-(

**Comment by felixmeziere** [comment]
Same with my next.js app!

**Comment by ToledoNicola** [comment]
same with apollo-angular

**Comment by jcreighton** [comment]
@davscro @felixmeziere @ToledoNicola We've been working on a [3.0 release](https://github.com/apollographql/apollo-client-devtools/tree/release-3.0) for the devtools. It's a complete rewrite of the existing codebase. It would be **amazing** if you could check it out. The more users we have before releasing, the more bugs we can catch!

**Comment by EliasTouil** [comment]
> @davscro @felixmeziere @ToledoNicola We've been working on a [3.0 release](https://github.com/apollographql/apollo-client-devtools/tree/release-3.0) for the devtools. It's a complete rewrite of the existing codebase. It would be **amazing** if you could check it out. The more users we have before releasing, the more bugs we can catch!

How can we test 3.0 ? Noob question but I don't find that version on the chrome web store
