### ISSUE TITLE
[Firefox] Addon will randomly not show up in Developer Tools

### ISSUE THREAD

**Issue by hibbie** [apollographql/apollo-client-devtools#218]
I have an issue where I installed the client into Firefox Developer Edition and it will not consistently show up, usually after a reboot.  Another reboot is not guaranteed to fix the issue.  In the past I have updated and rebuilt the addon to no avail.  So far it seems random and not necessarily tied to updates from Mozilla.  Is there a way to force the app to try and connect to the client tools or vice versa?

![image](https://user-images.githubusercontent.com/201506/61133308-d3586480-a482-11e9-9ff1-2060f38eb57c.png)

Firefox:  69.0b3 
Apollo client:  2.2.3  41a0930b133752ae5e6b3a9e021018d1bbdaad6e

Thanks for supporting Firefox users.  Usually the addon works very well.  😄

**Comment by stuarthadfieldglobality** [comment]
@jcreighton This is still occurring on the latest version of the addon & FF 84.0

Is there a fix or?

**Comment by StuartHadfield** [comment]
@jcreighton This is still occurring on the latest version of the addon & FF 84.0

Is there a fix or?

**Comment by jcreighton** [comment]
@StuartHadfield It looks like from the original screenshot that `window.__APOLLO_CLIENT__` is undefined. Is that still the case?

**Comment by lilred** [comment]
I'm having the same issue! `window.__APOLLO_CLIENT__` is set to a rich object.

It's a wonderful extension otherwise, thank you for that.
