### ISSUE TITLE
[Chrome] Extensions shows blank screen on error

### ISSUE THREAD

**Issue by VladimirMilenko** [apollographql/apollo-client-devtools#222]
When I have an error for introspection query(some of my servers are remote and do not allow the use of introspection in production mode) - apollo extensions simply wipes the extension window and nothing helps unless I enable introspection on the remote server.

**Comment by Fled8617** [comment]
same issue for me

**Comment by Fled8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/62677651-a9db1c00-b9e1-11e9-93c5-47d604a952eb.png)
![image](https://user-images.githubusercontent.com/35049517/62677657-ae073980-b9e1-11e9-9459-fc6c530d5f8c.png)
nothing render

**Comment by AbdelhakAj** [comment]
yup same here ... used to work thought

**Comment by grantsheppard** [comment]
I get this as we've explicitly configured our GraphQL server to only expose the schema if a specific request header exists. A really basic form of security through obscurity.

Would be really nice if the plugin allowed the user to specify request headers, not sure how hard this would be though?

**Comment by giulianok** [comment]
Completely blank

<img width="867" alt="Screen Shot 2021-02-27 at 5 47 39 PM" src="https://user-images.githubusercontent.com/8062245/109402463-13a07b00-7924-11eb-962f-2a5ab91fb167.png">

**Comment by hwillson** [comment]
This is fixed in 3.0 (which is being published this week) - thanks!
