### ISSUE TITLE
React Native Debugger crashes

### ISSUE THREAD

**Issue by garywong89** [apollographql/apollo-client-devtools#227]
We use apollo link rest and apollo link state for our code base.

When we open React Native Debugger and navigate the the apollo tab, the extension crashes on the graphQL options but works on cache, mutations, queries options.

**Comment by fbartho** [comment]
I'm also on @garywong89's team, and, to clarify, the Cache Tab works great, we'd love for all the tabs to work equally well!

**Comment by fbartho** [comment]
I'm also the maintainer of [apollo-link-rest](https://github.com/apollographql/apollo-link-rest), and this is a regularly requested feature, so I'd love to get this fixed. Please let me know how I can help.

- https://github.com/apollographql/apollo-link-rest/issues/114
- https://github.com/apollographql/apollo-link-rest/issues/172#issuecomment-438885852

**Comment by hwillson** [comment]
We can't support React Native Debugger issues unfortunately, but if this problem is still happening when you work with AC devtools directly, let us know. Thanks!
