### ISSUE TITLE
Does not appear in devTool tab bar.

### ISSUE THREAD

**Issue by amerllica** [apollographql/apollo-client-devtools#229]
I read an awesome article about this awesome extension but after installing it doesn't appear in devTool tab bar. the screenshot:

![image](https://user-images.githubusercontent.com/10472437/65793384-870fed00-e172-11e9-94ce-22f2ebc03d25.png)

My chrome version is: `Version 77.0.3865.90 (Official Build) (64-bit)`
My device is: `Mac OSX Mojave 10.14.6 `

**Comment by Blindpupil** [comment]
I managed to get it working on Chrome only after I connected the Apollo client to the Meteor server. I'm using Vue on the front instead of React, but maybe this will help someone: 

**imports/startup/client/index.js**
```
import Vue from 'vue'
import App from './App.vue'
import VueApollo from 'vue-apollo'
import { Accounts } from 'meteor/accounts-base'
import ApolloClient from 'apollo-boost'

Vue.use(VueApollo)

const client = new ApolloClient({
  uri: Meteor.absoluteUrl('graphql'),
  request: operation =>
    operation.setContext(() => ({
      headers: {
        authorization: Accounts._storedLoginToken(),
      },
    })),
})

const apolloProvider = new VueApollo({
  defaultClient: client,
})

Meteor.startup(() => {
  new Vue({
    el: '#app',
    apolloProvider,
    ...App,
  })
})
```

**Comment by abominab** [comment]
We've experience the same thing. Sometimes its there, sometimes its not.
https://github.com/apollographql/apollo-client-devtools/issues/142#issuecomment-546506290

**Comment by hwillson** [comment]
This should no longer be an issue - thanks!
