### ISSUE TITLE
Dev tool append in tool bar but not show anything

### ISSUE THREAD

**Issue by memsenpai** [apollographql/apollo-client-devtools#230]
Now, I'm using apollo client for management local state only.
Apollo version: apollo-boost@^0.4.4:
Apollo dev tool version: 2.2.5
Console log errors:
Uncaught Error: Extension context invalidated.
TypeError: Cannot read property '__schema' of undefined
Uncaught (in promise) TypeError: Cannot read property '__schema' of undefined

<img width="549" alt="Ảnh chụp Màn hình 2562-09-30 lúc 10 04 29" src="https://user-images.githubusercontent.com/10399540/65847002-f00d8580-e369-11e9-8705-08b2daacb20c.png">

**Comment by Daniel-Griffiths** [comment]
Same issue here :/

**Comment by Daniel-Griffiths** [comment]
I found a temporary solution here: https://github.com/apollographql/apollo-client-devtools/issues/228

**Comment by memsenpai** [comment]
solved with solution on https://github.com/apollographql/apollo-client-devtools/issues/230#issuecomment-546396994
