### ISSUE TITLE
devtools keeps crashing

### ISSUE THREAD

**Issue by tafelito** [apollographql/apollo-client-devtools#231]
First time I open the devtools everything is fine, it just take sometime to load, but I can see my cache data. Sometimes if I make any change to my app and the browser reloads, then if I try to go to the cache it will automatically crash. Other times it just crash if I try to just move through the data.
I have to reload the chrome extension, close the inspector and re open it again. 
I don't have much data in my dev env, so I don't think is related to that. 

I wanna help to find what issue could be, is there any way to see logs or anything like that?

one difference I found is that after I write to the cache, my ROOT_QUERY changes

before

![image](https://user-images.githubusercontent.com/5973652/66064331-2cc8b080-e513-11e9-9a9b-52d0b4cfa45a.png)

after

![image](https://user-images.githubusercontent.com/5973652/66064409-52ee5080-e513-11e9-965c-f60c29298a72.png)

I'm on chrome Version 77.0.3865.90 (Official Build) (64-bit) and version 2.2.5 of the devtools

**Comment by RichieMerchant** [comment]
I'm experiencing that exact same issue. Same Chrome version also.

**Comment by danielkv** [comment]
+1

**Comment by dalkegama** [comment]
+1

**Comment by kidtango** [comment]
Any resolutions for this issue? My Apollo Devtools crashed when 'cache' button is clicked after the data is recieved from API. tabs work just fine so long as I don't click on the cache button to view cache! Please help.

**Comment by soulfresh** [comment]
I'm seeing this issue as well. For me it's new as of the latest Chrome update (83.0.4103.61). I'm on the latest appollo devtool client (2.3.0) and have the most recent apollo react packages.

I'm seeing the following when I debug the apollo devtools and then click on the cache tab:

```
12098devtools.js:1 TypeError: Cannot read property '__typename' of null
    at T (devtools.js:1)
    at Yi (devtools.js:1)
    at Io (devtools.js:1)
    at Ka (devtools.js:1)
    at za (devtools.js:1)
    at Cu (devtools.js:1)
    at Ou (devtools.js:1)
    at Pu (devtools.js:1)
    at On (devtools.js:1)
```

**Comment by eDubrovsky** [comment]
@soulfresh I think this fixed in https://github.com/apollographql/apollo-client-devtools/pull/268 pr

Check https://github.com/apollographql/apollo-client-devtools/issues/266 issue

**Comment by soulfresh** [comment]
Thanks @eDubrovsky 👏  I'll keep my eye out for that release.

**Comment by jcreighton** [comment]
If anyone wants to test out this PR https://github.com/apollographql/apollo-client-devtools/pull/273, let me know if this fixes the issue!

**Comment by threehams** [comment]
2.3.1 fixed this for me (from source)! Do releases happen automatically at some point?

**Comment by jcreighton** [comment]
@threehams Glad it resolved the issue! Releases are a manual process but both the Firefox and Chrome extensions should be at 2.3.1 now.
