### ISSUE TITLE
TypeError: Cannot read property '__schema' of undefined

### ISSUE THREAD

**Issue by MatildaIE** [apollographql/apollo-client-devtools#238]
Chrome version `78.0.3904.108`

Apollo devtools are crashing on load. When I inspected the Apollo frame, it gives the error of `TypeError: Cannot read property '__schema' of undefined`

**Comment by nikolaik** [comment]
The workaround mentioned in https://github.com/apollographql/apollo-client-devtools/issues/228#issuecomment-535482693 fixed it for me, ie instantiating `ApolloClient` with `typeDefs: {}`

**Comment by jcreighton** [comment]
@MatildaIE Could you see if the latest version of devtools (2.3.1) resolves this issue?

**Comment by jessicacraftere** [comment]
For me, it was my file "possibleTypes.json" (file schema for fragmentMatcher) starting with element "data" instead of "__schema". 
I deleted the first element from schema and it started working fine.
