### ISSUE TITLE
Devtools graphiql does not execute queries

### ISSUE THREAD

**Issue by jebadirad** [apollographql/apollo-client-devtools#245]
Hello all, 

When using apollo dev tools with apollo client and apollo-link-rest, any query i make with graphiql does not execute.  

Heres the setup of the client 

```
import { RestLink } from 'apollo-link-rest';
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client';

const restLink = new RestLink({
    uri: 'https://jsonplaceholder.typicode.com/'

});
const client = new ApolloClient({
    link: restLink,
    cache: new InMemoryCache(),
    connectToDevTools: true,
    typeDefs: {}
});
```

Here is a component that works.
```
const container = () => {
    const query = gql`
        query something {
            person @rest(type: "Person", path: "todos/1") {
                id
                __typename
            }
        }
    `;
    const { loading, error, data, client } = useQuery(query);
    console.log(client);
    if (loading) return 'Loading ...';
    if (error) return `Error! ${error.message}`;
    return <div>{data.person.id}</div>;
};
```

In the app I do get the correct data back. In this case it is rendering `1` perfectly. 

When I open up dev tools I get: 
![Capture](https://user-images.githubusercontent.com/3018517/72027417-2ba6ce00-323c-11ea-87a5-16000ae736f5.PNG)

The cache is fine, the queries are fine, I just can't get graphiql to actually work.  Further more I opened up fiddler to see if it was even making any network requests, it is not. I am also unable to hit my local cache, so I am pretty sure there is some error being thrown somewhere, though I do not see any errors in the dev console for the extension. 

```
"@apollo/client": "^3.0.0-beta.19",
"apollo-link-rest": "^0.7.3"
```

**Comment by jcreighton** [comment]
This seems related to the devtools not being upgraded (at the time of this issue being opened) to handle Apollo Client 3. It should be resolved as of the latest release.
