### ISSUE TITLE
Cache shown in devtools doesn't update after calling `evict` or `gc` methods

### ISSUE THREAD

**Issue by mattwilson1024** [apollographql/apollo-client-devtools#247]
### Intended outcome:

Apollo Client 3 has introduced new `evict` and `gc` methods for removing objects from the cache, as detailed in the [Garbage collection and cache eviction docs](https://www.apollographql.com/docs/react/v3.0-beta/caching/cache-interaction/#garbage-collection-and-cache-eviction).

After calling either of these methods, I would expect the displayed information in the "Cache" tab of Apollo devtools to update in order to reflect the changes.

### Actual outcome: 

I have found that neither `evict` nor `gc` causes the cache tab of the devtools to update. This means that devtools are out of sync, showing an older representation of the cache which is misleading.

### Workaround:

The only way I've found to get the devtools to show the new state is to manually right click the devtools in Chrome and click "Reload Frame". The devtools do then show the true state of the cache, but it relies on you knowing that something may have changed in the cache and manually reloading the extension. 

### How to reproduce the issue:

If it helps, I have an example repo which the issue: [https://github.com/mattwilson1024/apolloclient3-experimentation](https://github.com/mattwilson1024/apolloclient3-experimentation)

### Versions

```
System:
    OS: macOS 10.15.2
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.116
  Developer tools extension:
    Apollo Client Developer Tools: 2.2.5
  npmPackages:
    @apollo/client: ^3.0.0-beta.36 => 3.0.0-beta.36
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3
```

**Comment by ivan-kleshnin** [comment]
Same goes for React components... From reading posts Spectrum I understood that `evict` just removes the item from cache. It doesn't trigger any updates hovewer. And how to do that is a big question. I dunno why those sections were added in docs when they are clearly useless by itself and describe something very low-level.

**Comment by mattwilson1024** [comment]
@ivan-kleshnin exactly - the piece that seems to be missing to me is some kind of observable / event which lets you know that an eviction has occurred. It relates quite closely to another question that I have here https://stackoverflow.com/questions/60344713/is-there-a-way-to-detect-when-data-used-by-a-query-is-evicted-from-the-apollo-cl

**Comment by jcreighton** [comment]
This is a known limitation of the current devtools. I'm currently heads down on rewriting the entire devtools architecture so keep an eye out for a future release.
