### ISSUE TITLE
Is there a way to debug another webextensions

### ISSUE THREAD

**Issue by MatthD** [apollographql/apollo-client-devtools#249]
Hi *Apollo team*

Our team is using Apollo  in one of our *webextension* & we tried to use this debugger, is there any kind of way to achieve this ?

**Comment by alexstrat** [comment]
Very very linked to #144

**Comment by hwillson** [comment]
We're tracking this feature request in https://github.com/apollographql/apollo-client-devtools/discussions/382 - thanks!
