### ISSUE TITLE
Cannot read property 'getStore' of undefined

### ISSUE THREAD

**Issue by use-strict** [apollographql/apollo-client-devtools#250]
After updating to `@apollo/client@3.0.0-beta.41` (latest), an error is thrown in the console on page load by this extension: `Cannot read property 'getStore' of undefined`.

It previously worked fine with beta.39.

As there are no source maps, here are some screenshots with the minified code and debugger watch frame:
![image](https://user-images.githubusercontent.com/9483866/76962216-7ec98b00-6927-11ea-8f70-45bbcdb2982e.png)
![image](https://user-images.githubusercontent.com/9483866/76962352-bf290900-6927-11ea-8586-9b4a0b3454a1.png)

**Comment by gradinarot** [comment]
Same here.

**Comment by markwain** [comment]
+1

**Comment by markwain** [comment]
Any updates?

**Comment by alfechner** [comment]
Same problem here.

**Comment by jebadirad** [comment]
Same here. Latest version as well.

**Comment by matt-senseye** [comment]
Same here when updating to @apollo/client 3.0.0-beta.43

**Comment by mzygmunt** [comment]
The same with @apollo/client 3.0.0-beta.44 :(

**Comment by nratter** [comment]
Also having intermittent issues with this

**Comment by devinhalladay** [comment]
+1! `@apollo/client@^3.0.0-beta.44`

**Comment by yellowspaceboots** [comment]
+1! `@apollo/client@^3.0.0-beta.44` I had to revert to `@apollo/client@^3.0.0-beta.39` in order to see my cache in Apollo Dev Tools

**Comment by keithlayne** [comment]
See:

https://github.com/apollographql/apollo-client/pull/5909#issuecomment-598784949

**Comment by fpsstyle228** [comment]
+1

**Comment by ammanvedi** [comment]
beta 48 its still dead

**Comment by noah-potter** [comment]
I've created a temporary fork with a hacky workaround. https://github.com/noah-potter/apollo-client-devtools
I've only tested it against a simple app, so it might not work for all cases.

Relevant changes: https://github.com/noah-potter/apollo-client-devtools/commit/52d2b8924236bdb2d2472d761c6fbd1670351804

**Comment by jcreighton** [comment]
@use-strict Could you try out the latest release of the devtools (2.3.1) and let me know if that resolves the issue?

**Comment by willingram** [comment]
> @use-strict Could you try out the latest release of the devtools (2.3.1) and let me know if that resolves the issue?

FWIW I'm on `3.0.0-beta.44` and 2.3.1 is working for me.

**Comment by tobiassteenweg** [comment]
> > @use-strict Could you try out the latest release of the devtools (2.3.1) and let me know if that resolves the issue?
> 
> FWIW I'm on `3.0.0-beta.44` and 2.3.1 is working for me (previously broken as per the original post).

I can confirm it as well. Kudos to the developer 👍

**Comment by fdev** [comment]
Latest version works for me as well on `3.0.0-beta.53`. Thanks!
