### ISSUE TITLE
Apollo Devtools not Connecting using Apollo Client 3

### ISSUE THREAD

**Issue by bbrinx** [apollographql/apollo-client-devtools#251]
It seems that the devtools don't work with Apollo Client 3. After upgrading to Apollo 3.0.0-beta.23 I can no longer use the Apollo Devtools. The tab shows up and can be opened, but there is no content. Prior to this upgrade the devtools were hooked up and working. 

```
    "@apollo/client": "^3.0.0-beta.23",
    "@apollo/link-batch-http": "^2.0.0-beta.3",
    "@apollo/link-context": "^2.0.0-beta.3",
    "@apollo/link-error": "^2.0.0-beta.3",
    "apollo": "^2.24.0",

     Chrome v. 80.0.3987.149
```

**Comment by rpCal** [comment]
Have same issue with "@apollo/client": "^3.0.0-beta.37". apollo chrome tab is not active.

**Comment by onpaws** [comment]
I just ran into the same issue. 
Taking a quick look at the branches, it seems
https://github.com/apollographql/apollo-client-devtools/tree/release-3.0
might be 3.0 compatible.

**Comment by onpaws** [comment]
I was able to get `release-3.0` built and installed in Chrome, it looks like this:
![image](https://user-images.githubusercontent.com/182515/78670937-d59b0280-78de-11ea-9e9c-5c139e240775.png)
The queries appear to be hard coded (not from my app). Seems it may still be too early to use.

@justinanastos, @cheapsteak not sure if you're still maintaining? 
Would be appreciated if you could provide an update. Thanks for your work on this. 🍻

**Comment by jcreighton** [comment]
@bbrinx Thanks for opening this issue! Changes in the AC3 beta are incompatible with the current extension but we are working on a fix! 

@onpaws I'll be leading on this project 😀Looking forward to getting you AC3-compatible devtools!

**Comment by onpaws** [comment]
Glad to hear it @jcreighton! Good luck. 
If memory serves I heard the Firefox extension was blocked by Mozilla for using `eval`, so if that's true, I especially wish you luck in that endeavour! :)

**Comment by prins-p** [comment]
@jcreighton , that's great, thank you!! Could you give us some guidance when you expect to be able roll out an update of the devtools with AC3 support?
