### ISSUE TITLE
Apollo Client devtools not showing data in cache

### ISSUE THREAD

**Issue by chrisjaimes** [apollographql/apollo-client-devtools#253]
After installing the Apollo Client Devtools from the chrome store, I noticed none of my mutations are displayed in the Mutations tab in the devtools. Also, the only data that the cache is showing is the `ROOT_QUERY` but the cache does not refresh after Mutations are executed. If I run `window.__APOLLO_CLIENT__.cache.data.data` I am not able to see the data that was just recently sent to the server with my mutation. I removed the extension in the browser and now I am trying by cloning the repo... but the problem persists. The weird part is that it used to work before but woke up this morning not being able to debug with the tool 😢 

Any ideas? 

I am using Apollo Angular
apollo-client: 2.6.0
devtools: 2.2.5
chrome: 80.0.3987.163 (Official Build) (64-bit)

**Comment by chrisjaimes** [comment]
I spent about an hr reloading the app, installing and uninstall the extension until it resolved somehow. I see two other posts reporting the same issue https://github.com/apollographql/apollo-client-devtools/issues/226

**Comment by sotomaque** [comment]
hey @chrisjaimes any updates on this?
