### ISSUE TITLE
Apollo Dev tools as Flipper Plugin

### ISSUE THREAD

**Issue by plrdev** [apollographql/apollo-client-devtools#255]
React Native dev tooling is going to Flipper more and more. Flipper seems to have a good plugin system. It would be really nice to have the Apollo dev tools as a flipper plugin. I have no idea how feasible this would be, but would be interested in taking a look at it if this is thought a good idea & someone can help point out to right direction.

**Comment by marhaupe** [comment]
I agree, I expect most people to make the switch towards Flipper. I can't tell if implementing a plugin is going to be a one person job or not, but if it isn't, I'd gladly help. As far as I can tell, we'd have to develop a react-native-library as well, so maybe we could split the work between multiple contributors afterall

**Comment by TheMrZZ** [comment]
Yeah, I'd really be glad if that happened!

**Comment by twelve17** [comment]
@eduplus  If you end up getting impatient or get a sense that this might not be done otherwise, I'd be up for looking into it as well.

**Comment by eduplus** [comment]
Just to say I have no knowledge of how to actually do this, I was hoping there would be someone able to point out the right way to even start doing this. Cool to see there are others interested in helping out as well, I am sure there is enough work for all of us!

One thing to consider: As Apollo Client 3.0 is still in beta, dev tools seems to be going under some major reworking as well. AC3.0 Beta 39 is the last version the dev tools are working right now, with 40+ getting getStore is undefined error. We could use 39 to test for now I guess, but there might be changes coming soon. Not sure whether it would make sense to wait until AC3.0 is out with Dev tools working with it or if there are tasks that could be started already?

**Comment by twelve17** [comment]
> Just to say I have no knowledge of how to actually do this

I'm in the same boat. :) 

> One thing to consider: As Apollo Client 3.0 is still in beta

This definitely makes me want to wait.

**Comment by eduplus** [comment]
I started some preliminary work on this during the weekend, but waiting for the dev tools restructure to land before going full steam ahead.

**Comment by hsavit1** [comment]
> I started some preliminary work on this during the weekend, but waiting for the dev tools restructure to land before going full steam ahead.

Any updates? 🙏

**Comment by plrdev** [comment]
https://github.com/plrdev/react-native-flipper-apollo-devtools here you go for a rough alpha that should have a somewhat working Cache tab. It is based on the old devtools version and not the one under rework. Contributions welcome! After the rework is done, hopefully it is done in a way we can take it into use.

**Comment by swrobel** [comment]
@plrdev very cool, but it seems that 0.0.1 is the [latest version you've released](https://www.npmjs.com/package/flipper-plugin-apollo-client-devtools), not 0.0.2. Am I missing something?

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/385 - thanks!

**Comment by mohit23x** [comment]
Folks, checkout apollo client devtools for react native [here](https://github.com/razorpay/react-native-apollo-devtools) 🎉
