### ISSUE TITLE
TypeError: can't redefine non-configurable property "__APOLLO_DEVTOOLS_GLOBAL_HOOK__"

### ISSUE THREAD

**Issue by rogue-agent** [apollographql/apollo-client-devtools#256]
The following is visible in the console when using 2.2.5 in firefox.

TypeError: can't redefine non-configurable property "__APOLLO_DEVTOOLS_GLOBAL_HOOK__"

Info:
The error message was present when a page had apollo and when it did not.

**Comment by hellkat1911** [comment]
Exact same issue. Installed Apollo dev tools (2.3.1) on Firefox Developer Edition (83.0b4).

The Apollo tools don't show up as an option inside the browser dev tools, and console has the following error:
**Uncaught TypeError: can't redefine non-configurable property "__APOLLO_DEVTOOLS_GLOBAL_HOOK__"**

Only seems to appear on pages that are actually running Apollo.

**Comment by rogue-agent** [comment]
Still nothing...

**Comment by hwillson** [comment]
This should be fixed in 3.0 (which is being published this week) - thanks!

**Comment by ianchanning** [comment]
I'm getting a similar error again, with Firefox and the Apollo dev tools extension installed.

```
TypeError: can't redefine non-configurable property "__APOLLO_CLIENT__"
```

**Comment by jerelmiller** [comment]
Hey @ianchanning, I've created a new issue https://github.com/apollographql/apollo-client-devtools/issues/1406 and will move the conversation over there 🙂
