### ISSUE TITLE
Running Queries or Mutation from log are not the same queries

### ISSUE THREAD

**Issue by martinrojas** [apollographql/apollo-client-devtools#257]
![image](https://user-images.githubusercontent.com/317579/81231079-94bb0a00-8fc0-11ea-98ba-8c92d7f898b4.png)

when selecting the run in graphical button from either the Queries or the Mutations log the queries do not carry all the values in the call. specifically, if a call had other header variables passed in the context. These are not passed for testing and therefore the calls are not the same. Neither is there an option to see or add header values in the graphical UI.

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/386 - thanks!
