### ISSUE TITLE
[feature] View/Copy as JSON

### ISSUE THREAD

**Issue by bennypowers** [apollographql/apollo-client-devtools#258]
Hey Hey

Thanks for making this great extension, it really helps my workflow and is a big part of the value proposition of apollo client

-----

I'd love to be able to view and/or copy an object from the cache inspector as JSON. That would help me for instance in writing test cases.

Thanks again

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/387 - thanks!
