### ISSUE TITLE
Tab doesn't display in Angular apps

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-client-devtools#26]
**apollo-client**: 0.8.5
**apollo-angular**: 0.10.0
**apollo-client-rxjs**: 0.4.1

So I've had this extension installed for ages and have never ever seen the tab. Thought that the extension wasn't yet ready but saw a commit in Client that is pushing people towards this so figured I should take another look. Still no tab.

Within Angular apps, Apollo Client is lazily loaded and the `window.__APOLLO_CLIENT__` property is only being set when a component is loaded that depends on Apollo. Even if I refresh the page on a route that contains a component using Apollo, it still doesn't display the tab.

Tried #24 but it doesn't seem to change anything despite it supposedly polling for the property.

The only way to get the Apollo tab to work, is to view a component that depends on ApolloClient THEN open the DevTools, when the property has already been set.

Related: #23

**Comment by TheoMer** [comment]
> The only way to get the Apollo tab to work, is to view a component that depends on ApolloClient THEN open the DevTools, when the property has already been set.

@intellix Yes. This is the case here as well.

**Comment by kamilkisiela** [comment]
Only a function that returns an instance of `ApolloClient` is being executed when Angular bootstraps.

```ts
function provideClient() { return new ApolloClient; }

ApolloModule.withClient(provideClient);
```

You can put `new ApolloClient` outside the function.

```ts
const client = new ApolloClient;

function provideClient() { return client; }

ApolloModule.withClient(provideClient);
```

**Comment by loxy** [comment]
Any progress on this?

**Comment by spencermefford** [comment]
I was able to get it working by setting the value on `window` when I create my Apollo Client. 

```
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { ApolloModule, Apollo } from 'apollo-angular';
import { HttpBatchLinkModule, HttpBatchLink } from 'apollo-angular-link-http-batch';
import { InMemoryCache } from 'apollo-cache-inmemory';

import { environment } from '../../environments/environment';

@NgModule({
  exports: [
    HttpClientModule,
    ApolloModule,
    HttpBatchLinkModule,
  ],
})
export class GraphQLModule {
  constructor(apollo: Apollo, httpLink: HttpBatchLink) {
    const uri = environment.graphqlApiUrl || 'http://localhost:3333/graphql';
    apollo.create({
      link: httpLink.create({ uri }),
      cache: new InMemoryCache(),
    });

    window['__APOLLO_CLIENT__'] = apollo.getClient(); // Used by the Apollo Chrome extension
  }
}
```

**Comment by intellix** [comment]
I think things here have changed quite a bit. It always seems to appear for me and I'm not sure it's an issue anymore (for me). You're still having issues then @spencermefford ?

**Comment by spencermefford** [comment]
Wow, I'm really confused. As of yesterday, I never saw the Apollo tab in dev tools until I added that line of code. Today I see the tab even when I remove that line. I've killed my ng server, restarted my browser, and tried in a new Chrome tab. Mysterious. Perhaps it does work now in Angular. No idea why I couldn't see it before though.
