### ISSUE TITLE
Usage of Apollo-client-tools with Chrome and Nativescript

### ISSUE THREAD

**Issue by cjohn001** [apollographql/apollo-client-devtools#269]
Hello together, I am currently using the Apollo client within a nativescript application. Nativescript uses the chrome devtools for debugging. However, I am not able to use the apollo-client-devtools here, as they do not show up. I am wondering, if I might need to configure something in order to be able to open the apollo-client-devtools or if the tools are not working together with nativescript apps. Thanks for your help.

**Comment by lucasbaze** [comment]
No idea if this is related, but I'm getting the following error based on the newest update on May 29th in an electron application: 

`{
  constructor: 'Error',
  name: 'UnhandledRejection Error',
  stack: 'UnhandledRejection Error: Invalid header: Does not start with Cr24\n  
}`

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/388 - thanks!
