### ISSUE TITLE
AC3 Breaks Apollo Client DevTools Query Tab after first broadcast:new message

### ISSUE THREAD

**Issue by justinmwarner** [apollographql/apollo-client-devtools#280]
**Intended outcome:**
Apollo Client DevTools Query Tab works with all queries made on site.

**Actual outcome:**
When the first `broadcast:new` gets sent, it parses using the function `filterQueryInfo` which adds the `document` mapping properly. Later calls get routed through `QueryManager`'s `onBroadcast`, mapping the `queries` field to `getQueryStore`. Looking at `getQueryStore`, you'll see it's a bit different than `filterQueryInfo` (no document map). This causes the `document` field to be undefined when the Query is rendered, causing it to fail here: https://github.com/apollographql/apollo-client-devtools/blob/master/src/devtools/components/WatchedQueries/WatchedQueries.js#L30

**How to reproduce the issue:**
I'm not sure how to get a setup, but I can investigate if needed.

**Versions**
  System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 13.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD 
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD 
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.19041.1.0)
  npmPackages:
    @apollo/client: ^3.0.0-beta.50 => 3.0.2       
    @apollo/link-context: ^2.0.0-beta.3 => 2.0.0-beta.3 
    @apollo/react-common: ^3.1.4 => 3.1.4         
    @apollo/react-hooks: ^4.0.0 => 4.0.0

**Comment by hwillson** [comment]
@justinmwarner can you confirm which devtools version you're using - is it 2.3.1?

**Comment by justinmwarner** [comment]
@hwillson , I have pulled the code down, built and loaded into Chrome, so I have the latest- 2.3.1.

This repro's with the latest on the Chrome extension store, 2.3.1 too.

**Comment by justinmwarner** [comment]
@hwillson , I tested this locally with this patch file:
```
diff --git a/node_modules/@apollo/client/core/QueryManager.js b/node_modules/@apollo/client/core/QueryManager.js
index 61aaeec..407ba67 100644
--- a/node_modules/@apollo/client/core/QueryManager.js
+++ b/node_modules/@apollo/client/core/QueryManager.js
@@ -212,6 +212,7 @@ var QueryManager = (function () {
         var store = Object.create(null);
         this.queries.forEach(function (info, queryId) {
             store[queryId] = {
+                document: info.document,
                 variables: info.variables,
                 networkStatus: info.networkStatus,
                 networkError: info.networkError,
```

It works perfectly fine after this `document: info.document,` was added to the queries broadcast.

**Comment by jkossis** [comment]
@hwillson I can confirm, it breaks as well locally.

**Comment by jcreighton** [comment]
@justinmwarner We released a new version that might fix this issue.

**Comment by justinmwarner** [comment]
@jcreighton , looked at this just now, it seems to be working!

Do you have a link to the PR that fixed this? Just curious what that looks like.

@jkossis , fyi, this may be fixed for you as well.

Probably safe to close this guy, thanks so much!

**Comment by hwillson** [comment]
Looks like this was fixed - thanks all!
