### ISSUE TITLE
Cannot read property 'getStore' of undefined

### ISSUE THREAD

**Issue by drachyovmaxim** [apollographql/apollo-client-devtools#281]
Hi, cannot get it worked. When i press Apollo tab in React Native Debugger i see some loading screen for a second and then an error:

`Uncaught TypeError: Cannot read property 'getStore' of undefined`
`   at te.<anonymous> (RNDebuggerWorker.js:2)`
`   at te.s.emit (RNDebuggerWorker.js:2)`
`   at RNDebuggerWorker.js:2`
`   at RNDebuggerWorker.js:2`

Project dependencies:
"@apollo/client": "^3.0.2",
"graphql": "^15.3.0",
"react": "16.11.0",
"react-native": "0.62.2",

Apollo Client Developer Tools 2.3.1
React Native Debugger 0.11.3

**Comment by aevaldas** [comment]
Try to update `@apollo/client` to `3.1.1`

**Comment by lenarmazitov** [comment]
+1

**Comment by yodaheis** [comment]
+1

**Comment by jcreighton** [comment]
@drachyovmaxim It would be super helpful to see a reproduction!

**Comment by drachyovmaxim** [comment]
@jcreighton i can't make it right now, but the steps are:
1. create react-native app
2. set up apollo client
`import { ApolloClient, HttpLink, ApolloLink, from } from '@apollo/client';
import { onError } from '@apollo/client/link/error';
import { cache } from './cache';

import StorageService from '../services/StorageService';
import CONFIG from '../../app.json';

const authLink = new ApolloLink(async (operation, forward) => {
  const token = await StorageService.token.get();

  operation.setContext( ({ headers = {} }) => ({
    headers: {
      ...headers,
      authorization: `Bearer ${token}` || '',
    },
  }));

  return forward(operation);
});

const httpLink = new HttpLink({
  uri: `${CONFIG.host}/graphql`
});

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors) {
    graphQLErrors.map(({ message, locations, path }) => {
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`
      )
    });
  }

  if (networkError) console.log(`[Network error]: ${networkError}`);
});

const client = new ApolloClient({
  cache,
  link: from([authLink, errorLink, httpLink])
});`

3. Run the app and React Native Debugger and click Apollo tab

**Comment by yodaheis** [comment]
Which rndebugger version are using?
I managed to get rndebugger running fine with latest apollo client 3 version by running rndebugger from building manually and running, from their master branch. Their latest version doesn't include apollo-dev-tools with apollo client 3 support.
rndebugger has updated the apollo-dev-tools version to 2.3.1, but they haven't released it yet.

**Comment by drachyovmaxim** [comment]
Works now with React Native Debugger 0.11.4
