### ISSUE TITLE
Can't explore cache after upgrading to ApolloClient 3

### ISSUE THREAD

**Issue by martdavidson** [apollographql/apollo-client-devtools#283]
This is what the cache pane looks like since upgrading:

![Screen Shot 2020-08-11 at 10 45 39 AM](https://user-images.githubusercontent.com/8870176/89904986-f7bfcc80-dbbf-11ea-9fb2-1b2629548dc2.png)

Instead of being able to explore the data in an entity, it's just __ref for everything. Has this already been brought up?

I'm on version 2.3.1

I can see the normal view when selecting an individual item in cache, but I used to be able to see this for all entities under the root query:

![image](https://user-images.githubusercontent.com/8870176/89905226-4a00ed80-dbc0-11ea-9826-fcc88c03e7e7.png)

**Comment by sasha240100** [comment]
+1

**Comment by jcreighton** [comment]
@martdavidson This is a known limitation of the current devtools for AC3: https://github.com/apollographql/apollo-client-devtools/pull/263 We're in the midst of a major rewrite for the devtools so expect a nicer, cleaner experience in the near future.

**Comment by martdavidson** [comment]
@jcreighton Thank you very much for the response! Knowing it's on the radar is good enough for me! I missed that PR when looking for the issue, thanks for the link.

**Comment by martdavidson** [comment]
@jcreighton Hey Jenn, I didn't want to open a new issue - I see some stuff was merged, but I'm not seeing a difference on 2.3.5. Should I be?
