### ISSUE TITLE
Cannot read property 'loc' of undefined

### ISSUE THREAD

**Issue by maniator** [apollographql/apollo-client-devtools#287]
https://github.com/apollographql/apollo-client-devtools/blob/50248eaac9b813e3667c23a848d546cfd6544a6a/src/devtools/components/WatchedQueries/WatchedQueries.js#L30

![image](https://user-images.githubusercontent.com/539579/93246419-bd1af800-f75a-11ea-861d-73387a79cca4.png)

This happens when I click queries on the tool 
![image](https://user-images.githubusercontent.com/539579/93246473-d7ed6c80-f75a-11ea-8500-954d8789a0e9.png)

I am on the latest version.

On the latest version of apollo/client as well.

**Comment by maniator** [comment]
The `document.loc` is defined like so:

![image](https://user-images.githubusercontent.com/539579/93246549-f2274a80-f75a-11ea-9af4-7b88da29284d.png)

**Comment by jcreighton** [comment]
Feel free to submit a PR!

**Comment by nickpassarella** [comment]
@maniator I'm hitting the same error and started to look into a fix.

What I'm noticing is that I hit this error when [prefetching](https://www.apollographql.com/docs/react/performance/performance/#prefetching-data). Is this the same for you?

**Comment by jcreighton** [comment]
We released a new version (2.3.2) that might fix this issue. Try it out and let us know!

**Comment by jcreighton** [comment]
🤞  This should be resolved in the latest version. If not, please re-open this issue!
