### ISSUE TITLE
I can't for the life of me get the debugger tab to appear

### ISSUE THREAD

**Issue by robclouth** [apollographql/apollo-client-devtools#293]
I've read all the other issues, and tried everything.

```
"@apollo/client": "3.2.1"
```
Chrome Version 85.0.4183.121
MacOS Catalina

I tried the firefox one too.

I'm using expo 39. 
window.__APOLLO_CLIENT__ is undefined.
 connectToDevTools is true

Any ideas? I really need that cache inspector...

**Comment by ElvenMonky** [comment]
Same:

**Comment by AdrienLemaire** [comment]
You want to inspect `window.__APOLLO_CLIENT__` (notice the double underscore surrounding the name)

**Comment by donovantc** [comment]
@robclouth did you ever get the tab to appear?

**Comment by robclouth** [comment]
I actually just switched to URQL. Lighter and simpler for my use case.
Everything just worked.

**Comment by KVestergaard** [comment]
> @robclouth did you ever get the tab to appear?

Well, I didn't... So still; please advise.

**Comment by ElvenMonky** [comment]
It appears only when I run WEB application locally. This partially solved my problem, but would be curious to know, what webpack/etc. configuration would make it appear for deployed site.

**Comment by hwillson** [comment]
To use Apollo Client Devtools in production, you'll want to pass `connectToDevTools: true` in as an option to your `ApolloClient` constructor call. See the [devtools config docs](https://www.apollographql.com/docs/react/development-testing/developer-tooling/#configuration) for more details. Thanks!
