### ISSUE TITLE
Apollo Dev Tools don't refresh data

### ISSUE THREAD

**Issue by wesbos** [apollographql/apollo-client-devtools#294]
I'm not able to see whats in my cache via apollo dev tools. I can refresh the frame (which only exists on Chrome, not firefox), but about half the time it can't find the cache.

I can see the cache if  I run `__APOLLO_CLIENT__.cache.data.data` in the console, so the data is there.

It's almost like the dev tools aren't aware of changes to cache most of the time. For some reason, sometimes changing the page will cause it to update. 

[Here is a video detailing the problem](https://wes.io/6quP7dyA), hopefully it's helpful. Any tips on a workaround for now?

**Comment by wesbos** [comment]
Just seeing this PR for a new version of dev tools, I bet this will fix it. Any way to beta test it?

https://github.com/apollographql/apollo-client-devtools/pull/292

**Comment by jcreighton** [comment]
Hi @wesbos! So, as you've seen, we're working on an overhaul of the existing devtools. We're not ready for beta testing yet but we'd love your feedback when we are! 

Re: "It's almost like the dev tools aren't aware of changes to cache most of the time" - we're working to make 3.0 more reliable. We won't be working on fixing issues in 2.x so we can focus on getting 3.0 out the door.

**Comment by wesbos** [comment]
Thanks. Would you merge a hot fix if I can at least make 2.x work for now? It’s unusable right now

**Comment by jcreighton** [comment]
@wesbos Would be happy to!

**Comment by jcreighton** [comment]
Good news! I was able to find the issue here and a fix is coming with 2.3.2! Please check out the associated PR and confirm the fix.

**Comment by wesbos** [comment]
amazing! Thank you so much :) Will try it out shortly once i'm back on that project

**Comment by jcreighton** [comment]
I went ahead with publishing 2.3.2 in Chrome and Firefox 👍

**Comment by jcreighton** [comment]
Closing this as the latest version should fix this error. Feel free to re-open if that's not the case!

**Comment by wesbos** [comment]
@jcreighton finally getting around to testing this and it doesn't seem to be any different in Firefox or Chrome (2.3.3 on both)

The cache does not show any updates unless I change the page, or close devs tools.  Here is a video: https://wes.io/QwubK1v7

**Comment by wesbos** [comment]
How do I re-open? Make another issue?

**Comment by jcreighton** [comment]
@wesbos Oh, that's disappointing. You're welcome to re-open this issue. But we're focused on 3.0 and we're nearing an alpha release so it's unlikely to be fixed in the 2+ version. I can let you know when the alpha is good-to-go if you're up for testing it?

**Comment by wesbos** [comment]
Please do! I'm recording a course right now with 2.0 and it's really slow to show people what is in the cache.

**Comment by jcreighton** [comment]
@wesbos I might have a solution for you in the above pull request. If you could check it out, that would be awesome! I ended up wanting to get this fixed for anyone using Apollo Client 2 as we're dropping support for that in the next version of devtools.

**Comment by wesbos** [comment]
@jcreighton Is that fix in the firefox extensions store? I don't notice any difference

**Comment by jcreighton** [comment]
@wesbos It is but I think at this point you're better off pulling down the latest from `main` and using the pre-release of 3.0 locally. We're tidying up some work on it so it's not ready for the extension stores yet but it's working so check it out!

**Comment by wesbos** [comment]
Alright thanks!

**Comment by hwillson** [comment]
This should be fixed in `main` (and will be included in the 3.0 release that is landing shortly). Thanks!
