### ISSUE TITLE
Explorer and Documentation empty

### ISSUE THREAD

**Issue by fhourdin** [apollographql/apollo-client-devtools#296]
Hi ! Got some troubles first with a max complexity too weak to handle the IntrospectionQuery.
So, I set the max complexity of "__schema" and "__type" to an higher value.
But now, the problem is that these queries are exposed, and the IntrospectionQuery try to document them as well, and now I've got this error :  

```
Error in event handler: Error: Unknown type "__Schema".

Unknown type "__Type".
    at t.assertValidSDL (<URL>)
    at _ (<URL>)
    at t.buildSchema (<URL>)
    at t.v (<URL>)
    at t.n.emit (<URL>)
    at <URL>
```

Any clue ?

**Comment by hwillson** [comment]
We're releasing a new devtools version this week that might address this, but if not any chance you can provide a small runnable reproduction / application that causes this? Thanks!

**Comment by hwillson** [comment]
A lot (almost all) of the codebase has changed in devtools 3.0. I'll close this off for now, but if you're still running into this issue and can provide a small runnable reproduction, we'll take a look. Thanks!
