### ISSUE TITLE
Differentiate between local and remote fields in GraphiQL docs/schema

### ISSUE THREAD

**Issue by lorensr** [apollographql/apollo-client-devtools#309]
I use this: 

https://www.apollographql.com/docs/react/local-state/client-side-schema/

to improve my devtools GraphiQL Docs. However, I don't know by looking at Docs whether I need to include `@client` when selecting a certain field. It would be great if there was an automatically-included differentiator for each client-side field. Barring that, it could be manually implemented if either comments or directives worked.

<img width="842" alt="apollo-devtools-docs-scrollY" src="https://user-images.githubusercontent.com/251288/97764643-b74c5c80-1ae5-11eb-8881-04ed6f75c026.png">

I can't tell that `scrollY` is client-only.

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/389 - thanks!
