### ISSUE TITLE
apollo-client 1.0 breaking change: noFetch deprecated; use fetchPolicy

### ISSUE THREAD

**Issue by 100ideas** [apollographql/apollo-client-devtools#32]
Devtool's explorer pane's `load from cache` checkbox is hooked up to conditional logic that sets a boolean value passed to its apollo-client's queries' `noFetch` option.

The `noFetch` query configuration option has been replaced with a more sophisticated [`fetchPolicy` option](http://dev.apollodata.com/react/api-queries.html#graphql-config-options-fetchPolicy) in [apollo-client v1.0.0-rc.1](https://github.com/apollographql/apollo-client/blob/39be05222b0a4eb0417d766bd57000af775c7134/CHANGELOG.md#100-rc1)

Consequently the `load-from-cache` devtool checkbox can cause errors when the devtool extension is used to inspect an application using apollo-client >= 1.0.0, such as githunt.com.

https://github.com/apollographql/apollo-client-devtools/blob/master/app/components/Explorer/Explorer.js#L69

**Comment by 100ideas** [comment]
Tried hacking the Explorer component in Explorer.js to set `fetchPolicy` instead of `noFetch`, but I don't think this is working (still makes network requests if the query results haven't been cached?)

```es6
export default class Explorer extends Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      noFetch: true,
      fetchPolicy: 'cache-only',
      query: this.props.query,
      variables: this.props.variables,
    };

    try {
      evalInPage(
        `
        window.__APOLLO_CLIENT__.makeGraphiqlQuery = (payload) => {
          return window.__APOLLO_CLIENT__.query({
            query: payload.query,
            variables: payload.variables,
            fetchPolicy: payload.fetchPolicy,
          }).catch(e => ({
            errors: e.graphQLErrors,
          }));
        };
        `, (result, isException) => {}
      );
      console.log(`Explorer.js constructor eval'd makeGraphiqlQuery w/ fetchPolicy: '${this.state.fetchPolicy}'`)
    } catch(e) {
      console.warn(e);
    }

    this.graphQLFetcher = (graphQLParams) => {
      const { fetchPolicy } = this.state;
      console.log("Explorer.js:graphQLFetcher fetchPolicy: " + fetchPolicy)

      return createPromise(
        "window.__APOLLO_CLIENT__.makeGraphiqlQuery(" + JSON.stringify({
          operationName: graphQLParams.operationName,
          query: parse(graphQLParams.query),
          variables: graphQLParams.variables,
          fetchPolicy: `'${fetchPolicy}'`
        }) + ")"
      );
    };
  }

  componentDidMount() {
    if (ga) ga('send', 'pageview', 'GraphiQL');
    if (this.props.query) {
      this.graphiql.handleRunQuery();
    }
  }

  clearDefaultQueryState() {
    this.setState({ query: undefined, variables: undefined });
  }

  render() {
    const { noFetch } = this.state;
    const graphiql = (
      <GraphiQL
        fetcher={this.graphQLFetcher}
        query={this.state.query}
        onEditQuery={() => { this.clearDefaultQueryState() }}
        onEditVariables={() => { this.clearDefaultQueryState() }}
        variables={this.state.variables}
        ref={r => {this.graphiql = r}}
      >
        <GraphiQL.Toolbar>
          <label>
            <input
              type="checkbox"
              checked={noFetch}
              onChange={() => {
                let fetchPol = noFetch ? 'network-only' : 'cache-only';
                this.setState({ noFetch: !noFetch, fetchPolicy: fetchPol, query: undefined, variables: undefined });
              }}
            />
            Load from cache
          </label>
        </GraphiQL.Toolbar>
      </GraphiQL>
    );

    return <div className="body">{graphiql}</div>;
  }
}
```

**Comment by helfer** [comment]
Thanks @100ideas !

Hm, I think that's going to start causing problems for us somewhat. We can update the devtools, but we'll have to know and check the version of Apollo Client to know which option to use.

Actually... we can probably just pass both options, because currently Apollo Client just ignores options that it doesn't know about 🤔 

@100ideas would you be willing to make a PR to make this change?

**Comment by 100ideas** [comment]
It's unlikely I'll spend time on this in the near future, but I will remember this thread if I do.
