### ISSUE TITLE
Version tracking might not be working with umd bundles

### ISSUE THREAD

**Issue by helfer** [apollographql/apollo-client-devtools#33]
@stubailo and I ran into an issue on apollo-client the other day which made us think that maybe the devtools can't detect the version of the umd bundles. This is actually an issue in apollo-client (build setup), but we should test if it's actually a problem here and track it if it is.

We need the version number to help make sure that the devtools are compatible with whichever version of Apollo Client the page is running.

**Comment by Gethyl** [comment]
@helfer Are you getting the same issue, where the apollo dev tool is not working and on inspecting the network tab of the apollo dev tool, we can see the below error:- 

![image](https://cloud.githubusercontent.com/assets/15939823/26100936/3a340936-39e4-11e7-888d-f7c3c0a6d0d0.png)

And apollo-client version is taken as _**local**_ in this request.

I am guessing it is related to the umd bundle as you mentioned?

**Comment by stubailo** [comment]
Yep - basically we introduced a new bundle format for Apollo Client which doesn't have that property. It doesn't affect most of the features, but we hope to put stuff like changelog announcements etc into the dev tools, and turn features on and off for different versions, so having a good sense of the version would be useful for sure.

**Comment by Gethyl** [comment]
Thanks for the reply. So will it be coming in the next release?

**Comment by stubailo** [comment]
Not that I know of.

Here's the line where we put a `version.js` file: https://github.com/apollographql/apollo-client/blob/5f8108aa675ad26ff86d80a1b766340f978b6e2f/scripts/deploy.sh#L40

But it's not used by the UMD build. Maybe we can make the UMD build first create that file, then it will be added to the build?
