### ISSUE TITLE
Queries list shows full query history

### ISSUE THREAD

**Issue by jcreighton** [apollographql/apollo-client-devtools#331]
Currently, the queries list represents the historical invocations of all queries. Instead, it should show watched queries + one-off queries with their latest data. We can surface the historical invocations in the QueryViewer panel but we'll need design help to do so. We also need design help to communicate to the user that a watched query has new data.

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/390 - thanks!
