### ISSUE TITLE
Devtools failing intermittently with React when not immediately mounted. 

### ISSUE THREAD

**Issue by Spark3000** [apollographql/apollo-client-devtools#335]
**Intended outcome:**
Chrome Apollo GraphiQL with React connecting and working. 

**Actual outcome:**
Not working. 

**How to reproduce the issue:**
DevTools intermittently fails when ApolloProvider component is not mounted immediately on page load. 
eg: If I render my App component with suspense and a fallback from index.js like this:

```javascript
ReactDOM.render(
  <React.StrictMode>
      <Suspense fallback={<Spinner />}>
          <LazyApp />
      </Suspense>
  </React.StrictMode>,
  document.getElementById("root")
);
```

Then Apollo Devtools will sometimes fail like this:

![Screenshot 2020-12-26 at 19 02 11](https://user-images.githubusercontent.com/4939629/103156015-2fb16000-47ad-11eb-99b8-e3c7510c5625.png)

![Screenshot 2020-12-26 at 19 04 39](https://user-images.githubusercontent.com/4939629/103156022-3b9d2200-47ad-11eb-8d99-400ce037a7de.png)

Also if conditionally rendering the ApolloProvider in my main App component like this: 
```javascript
  return authState.isLoading ? (
    <div>Loading...</div>
  ) : (
    <ApolloProvider client={client}>
      <AuthContext.Provider value={{ authState, authDispatch }}>
        <Routes />
      </AuthContext.Provider>
    </ApolloProvider>
  );
```
then it will pretty much always fail. But If I mount ApolloProvider straight away then DevTools connects and works every time. 

Thanks. 

**Desktop (please complete the following information):**
 -- Mac OS 10.15
 -- Chrome
 - Browser version [e.g. 22]
 -- Version 87.0.4280.88 (Official Build) (x86_64)
 - Extension version [e.g. 3.0]
--2.3.5

**Comment by jcreighton** [comment]
Thanks @Spark3000! Think you could create a working reproduction of the issue? That helps us debug and fix the issue much faster.

**Comment by Spark3000** [comment]
> Thanks @Spark3000! Think you could create a working reproduction of the issue? That helps us debug and fix the issue much faster.

Will do

**Comment by jcreighton** [comment]
@Spark3000 We're also working towards a major [3.0 release](https://github.com/apollographql/apollo-client-devtools/tree/release-3.0). It would be awesome if you could check that out and let us know if you're encountering the same issue with 3.0.

**Comment by hwillson** [comment]
We haven't heard back on a reproduction, so I'll close this off for now. Happy to re-open if you can provide a small runnable reproduction (or reproduction steps) that show this issue. Thanks!
