### ISSUE TITLE
Add support for reactive variables

### ISSUE THREAD

**Issue by Aliaksei-Martsinkevich** [apollographql/apollo-client-devtools#337]
I use [Reactive Varibables](https://www.apollographql.com/docs/react/local-state/reactive-variables/) to manage my local state and I cannot inspect reactive variables in apollo devtools even when I use `typePolicies`.

It would be nice to see values in the cache tab, especially when I've added some client fields to existing entity. I understand that technically this values are not part of the cache, but I think it could've been marked as local or something.

Also I would like to have an ability to inspect reactive variables, maybe as a different tab, where all variables are listed (display name support?).

Also I'd like to add that previous approach, using client resolvers worked with devtools

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/391 - thanks!
