### ISSUE TITLE
Mutations in apollo devtools

### ISSUE THREAD

**Issue by ryannealmes** [apollographql/apollo-client-devtools#35]
I can't seem to find mutations in the apollo devtools. I would have thought it would work just like any other query.

Is this be design? Is there an enhancement planned? Am I just missing it?

Thanks.

**Comment by bartlett705** [comment]
I am pretty sure this is do-able, and I plan on taking a crack at it very soon!

**Comment by stubailo** [comment]
You mean the mutations that are currently attached to components in the UI, like the query panel?

Or a log of mutations?

Right now, you can already do mutations via GraphiQL, it would be good to get some more info about what you would like to know about mutations.

**Comment by ryannealmes** [comment]
Yes like the mutations attached to components. Yes like the query panel.

Right now in apollo devtools you can only view a list of _Watched queries_ run. Mutations are not included. I am not talking about graphiql, I am talking about the apollo devtools chrome application.

Not sure what more information I can give.

**Comment by stubailo** [comment]
Yeah, being able to easily get the mutations from your code and see when they are called, and maybe call them yourself (even triggering the optimistic updates, etc) would be pretty sweet!

**Comment by ryannealmes** [comment]
Hey guys I have made this change. Check it out and let me know what you think :)

**Comment by tnrich** [comment]
@ryannealmes where can we check this out?! Nice work!

**Comment by ryannealmes** [comment]
You can pull down the repo and follow the readme to install the chrome extension
```
After cloning this repo, compile the extension bundle:

cd apollo-client-devtools
npm install
npm run build
Install the extension in Chrome:

Open chrome://extensions
Enable the 'Developer Mode' checkbox
Click 'Load unpacked extensions...'
Select the apollo-client-devtools/extension folder
```
Note there is a dependency on the latest version of the apollo-client. This unfortunately couldn't be avoided. If you don't have the latest version, the mutations tab will not display. 

Ping me with any feedback :)

**Comment by tnrich** [comment]
I'm not seeing the mutations tab after following the above instructions.. I have what I believe is the latest apollo version `"apollo-client": "1.2.2"` 

Anything you think I might be doing wrong?

![image](https://cloud.githubusercontent.com/assets/2730609/26235671/6c6dc38a-3c21-11e7-9693-189ab6777688.png)

**Comment by ryannealmes** [comment]
Sorry looking at the apollo-client, they haven't released a new version yet. You can always modify your node_modules apollo-client directly if you just want to see it working. You can get the PR here https://github.com/apollographql/apollo-client/pull/1699

I just changed timezones so my responses may be a bit delayed.

**Comment by tnrich** [comment]
@ryannealmes did they release a new version? I saw they released this 4 days ago: https://github.com/apollographql/apollo-client/releases/tag/v1.3.0

**Comment by ryannealmes** [comment]
There are some changes they want done which I need to do. Haven't had enough time to get to it. You can see the changes and add any comments on the PR.
https://github.com/apollographql/apollo-client-devtools/pull/36

**Comment by rrdelaney** [comment]
PR is merged 😄 I'll close this when the feature is released

**Comment by tnrich** [comment]
Looks like this has been released?! Anyone want to verify that?

**Comment by ramyanaga** [comment]
It has been released!
