### ISSUE TITLE
Queries showing only while running

### ISSUE THREAD

**Issue by cskiwi** [apollographql/apollo-client-devtools#366]
I'm not fully sure this is a bug, intended case or I'm missing a feature. Any how it's seems unpractical 

**Intended outcome:**

When having the queries tab open it shows all queries run for that page

**Actual outcome:**

It only shows the query when the network request is running, When the api gives an answer it disappears

**How to reproduce the issue:**

**Other info**
- I have the `connectToDevTools; true` in my configuration (but it has the same outcome without this set)
- I tried running the 3.xx  branch/release there the queries didn't even show up

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro
 - Browser [e.g. chrome, safari] Chrome
 - Browser version [e.g. 22]  88.0.4324.104
 - Extension version [e.g. 3.0] 2.3.5

**Comment by hwillson** [comment]
@cskiwi the `Queries` panel shows queries that are currently watching the Apollo Client cache. If a query stops watching the cache, it is removed from the list. It isn't a historical list of all queries for example. If a query is being removed from your list, then it sounds like it is no longer active / watching the cache. We're releasing a new 3.0 version of devtools this week, but our next version 3.1 will include a new `Network` tab, that will keep a historical list of all GraphQL operation based request/responses. Thanks!
