### ISSUE TITLE
Load from cache doesn't return

### ISSUE THREAD

**Issue by richburdon** [apollographql/apollo-client-devtools#39]
In the extension, select a query then check "load from cache"
The spinner appears and the results are not returned.
Unchecking the options returns the correct results from the server.
The correct items appear to be in the cache (Store tab) and ROOT_QUERY.

**Comment by rrdelaney** [comment]
Thanks for filing an issue! What version of Apollo a client are you using?

**Comment by richburdon** [comment]
~~~~
   "apollo-client": "^1.2.2",
    "react-apollo": "^1.2.0",
~~~~

I think the issues is related to https://github.com/apollographql/apollo-client/issues/1708

I.e., some internal error in apollo client (failing silently).

**Comment by evanshauser** [comment]
@rrdelaney I ran into the same issue and found that through Apollo Client the cache was accessed correctly. The issue may be that noFetch should be changed to fetchPolicy: "cache-only", since noFetch no longer exists.

**Comment by rrdelaney** [comment]
@evanshauser Thanks for looking into this more! Hopefully I can look into this later tonight.

This is probably where the code should be updated: https://github.com/apollographql/apollo-client-devtools/blob/master/app/components/Explorer/Explorer.js#L82
