### ISSUE TITLE
The header disappears once the "Build" button is clicked.

### ISSUE THREAD

**Issue by slorenzo** [apollographql/apollo-client-devtools#402]
**Intended outcome:**

Once users click on the Build button, it should open a sidebar where users can build their queries and/or mutations. 

**Actual outcome:**

Once users click on the Build button, the header shouldn't disappear and it should open the sidebar I mentioned above.

**How to reproduce the issue:**

Click on the "Build" button.

**Desktop (please complete the following information):**
 - OS: MacOs Big Sur 11.2
 - Browser: Chrome
 - Browser version:  88.0.4324.150
 - Extension version: 3.0

**Comment by slorenzo** [comment]
Hi there.

I was able to address this issue and would like to contribute by submitting a pull request.
Let me know if it's possible.

Thanks for this awesome project.

**Comment by hwillson** [comment]
Thanks @slorenzo - I noticed this as well, and have a fix ready (it will be merged shortly).

**Comment by slorenzo** [comment]
I'll close this issue because it no longer happens and was fixed here: https://github.com/apollographql/apollo-client-devtools/pull/410

Thanks.
