### ISSUE TITLE
Query in watched queries panel disappeared after page loaded.

### ISSUE THREAD

**Issue by kingkong2013** [apollographql/apollo-client-devtools#42]
apollo-client@1.3.0
react-apollo@1.2.0

I can see Apollo tab in chrome after I add `connectToDevTools: true` into `new ApolloClient()`, 
but the questions is when I open a page, the query displayed in the Watched queries panel, but soon when the page is ready, the query disappeared from the panel. why?

Thanks.

**Comment by rrdelaney** [comment]
Thanks for submitting an issue!

> I cannot see Apollo tab in chrome after I add connectToDevTools: true into new ApolloClient(),

Did you mean _I can see_? When you first load the page with devtools can you see the tab?

**Comment by kingkong2013** [comment]
@rrdelaney 
Sorry for my wrong words,  I cannot see Apollo tab, unless I set connectToDevTools: true.

but in the old version:
"react-apollo": "^0.5.13",
"apollo-client": "^0.4.22",

I did nothing and apollo-client-devtools  worked great.
[https://github.com/apollographql/apollo-client/issues/1748](https://github.com/apollographql/apollo-client/issues/1748)

**Comment by rrdelaney** [comment]
Thanks for clarifying 😄 Is the code base you're working on open source? I'd love to dig into this issue deeper

**Comment by rrdelaney** [comment]
Closing do to inactivity
