### ISSUE TITLE
Chrome extension for v3

### ISSUE THREAD

**Issue by AdrienLemaire** [apollographql/apollo-client-devtools#429]
Please upload the v3 version released a few hours ago to the chrome store.
I'm watching this repository's releases, but since the chrome plugin hasn't yet been uploaded, I might forget to check again later on ^^

Thanks, looking forward to it!

**Comment by hwillson** [comment]
@AdrienLemaire it will be uploaded first thing tomorrow morning - I promise! 🙂

**Comment by hwillson** [comment]
Quick update here - 3.0 is still pending review by the Chrome web store team, so I'm not sure when it will be available. I'll post back when it is!

**Comment by AdrienLemaire** [comment]
Thank you for keeping us updated!

**Comment by hwillson** [comment]
3.0 still hasn't been approved by Google. Seems like we're caught in a long approval line 🙁.

**Comment by vonkanehoffen** [comment]
@AdrienLemaire FYI following the instructions in the README you can clone this repo, `npm i && npm run zip` then drag the resulting `dist/apollo_client_devtools-3.0.0.zip` onto your Chrome extensions tab to install manually. Just realised you can do that myself 😀  

...v3 seems way better so far btw, so nice work u guys! 🎉

**Comment by sebastienbarre** [comment]
@vonkanehoffen thx. I have tried it a few times, and again today, but it fails building on macOS.
```
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/Cellar/node/15.8.0/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/barre/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN Found: graphql@15.0.0
npm ERR! npm WARN node_modules/graphql
npm ERR! npm WARN   dev graphql@"^15.0.0" from the root project
npm ERR! npm WARN   10 more (codemirror-graphql, graphiql, graphiql-2-rfc-context, ...)
npm ERR! npm WARN
npm ERR! npm WARN Could not resolve dependency:
npm ERR! npm WARN peer graphql@"^14.4.1" from express-graphql@0.9.0
npm ERR! npm WARN node_modules/express-graphql
npm ERR! npm WARN   dev express-graphql@"0.9.0" from graphiql@1.0.6
npm ERR! npm WARN   packages/graphiql
npm ERR! npm WARN   1 more (graphiql-2-rfc-context)
npm ERR! npm ERR! code EBADENGINE
npm ERR! npm ERR! engine Unsupported engine
npm ERR! npm ERR! engine Not compatible with your version of node/npm: undefined
npm ERR! npm ERR! notsup Not compatible with your version of node/npm: undefined
npm ERR! npm ERR! notsup Required: {"npm":"please_use_yarn_instead"}
npm ERR! npm ERR! notsup Actual:   {"npm":"7.6.1","node":"v15.8.0"}
```

Fails even faster with yarn.
```
yarn install                                                                
yarn install v1.22.10
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
error Can't add "graphiql-forked": invalid package version undefined.
```

**Comment by vonkanehoffen** [comment]
Could be a node version thing perhaps? I'm on Mac as well but Node 14.15.5 via nvm

**Comment by swrobel** [comment]
How about Firefox? I assume you can just update there without some arbitrary review process, but it doesn't seem like that's been done.

**Comment by hwillson** [comment]
@swrobel The Chrome webstore supports doing a scaled rollout, which we were hoping to do to test the new version with a subset of the install base before rolling it out to everyone. The Firefox store doesn't support this feature, so we were going with Chrome first. But since it's taken so long with Chrome we're going to go ahead with the full rollout on both stores shortly. The good news is we just heard back from Google - it only took 9 days! The bad news is they rejected the version. But, the good news (again) is that they rejected the version because our privacy policy link was broken 🙂. We'll have things fixed and submitted for review in both stores today.

**Comment by swrobel** [comment]
@hwillson I now see 3.0.2 in the Chrome store, but still 2.3.5 in Firefox: https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/versions/

**Comment by werevamp** [comment]
Hey apollo team I want to thank you SO MUCH for the deployment on the Chrome store! This is going to make life so much better now.

**Comment by AdrienLemaire** [comment]
Thank you ! closing the issue :)

**Comment by hwillson** [comment]
@swrobel we're still working on getting 3.0 into the Firefox store. It should be there shortly. Thanks all!
