### ISSUE TITLE
Devtools fails to detect that client and graphql backend are located on different ports

### ISSUE THREAD

**Issue by gforge** [apollographql/apollo-client-devtools#44]
I  have a separate backend that is independent of my client and is served at a different port. Unfortunately devtools fails to detect this and looks for the /graphql at the same server as the app is served from. Is there a solution to this or is this a bug?

**Comment by stubailo** [comment]
The devtools use your Apollo client configuration from inside the app. What does your network interface configuration look like?

**Comment by stubailo** [comment]
Closing since no response and this doesn't look like a bug.
