### ISSUE TITLE
Apollo data not visible in devtools using Apollo client v2

### ISSUE THREAD

**Issue by timhere** [apollographql/apollo-client-devtools#456]
**Intended outcome:** View local root cache structure, queries, mutations

**Actual outcome:** Apollo devtools frame appears, but no data is populated in any tab. Navigating to the graphiql tab seems to cause the extension to crash, only fixed by closing & reopening devtools.

![apollo-devtools-2021-03-15](https://user-images.githubusercontent.com/9252810/111154333-0671c600-858b-11eb-981b-4ffe68d35d51.jpg)

**How to reproduce the issue:** 

* Start local environment via yarn (vuejs application using apollo-client v2.6.10)
* Open browser tab and go to localhost URL
* Open devtools, navigate to Apollo tab

**Desktop (please complete the following information):**
 - OS: Arch linux 5.11.6-arch1-1
 - Browser Chromium
 - Browser version: Version 89.0.4389.90 (Official Build)
 - Extension version: 3.0.0

**Comment by hwillson** [comment]
Thanks for letting us know @timhere. Which exact version of `apollo-client` are you using?

**Comment by veeramarni** [comment]
I have same issue, i'm using `apollo-client@2.6.10`

**Comment by timhere** [comment]
> Thanks for letting us know @timhere. Which exact version of `apollo-client` are you using?

Thanks for the speedy response, I'm using `apollo-client@2.6.10`.

**Comment by arascan35** [comment]
Having the same problem with `apollo-client@2.4.12`

**Comment by jhoffmanqualified** [comment]
Same problem here, `apollo-client@2.6.4`

**Comment by arascan35** [comment]
> Same problem here, `apollo-client@2.6.4`

Try to install v3.0.2. Its worked for me.

**Comment by jhoffmanqualified** [comment]
> > Same problem here, `apollo-client@2.6.4`
> 
> Try to install v3.0.2. Its worked for me.

huh! I actually checked the chrome extension for an update and didn't see one, so assumed I was on v3.0.2.

I just did an uninstall-reinstall and that seemed to force an update from v3.0.0 -> v3.0.2, which fixed the issue for me.

Tyvm for the reply @arascan35 - you got me unstuck! :D

**Comment by hwillson** [comment]
Interesting - @timhere does 3.0.2 fix things for you by chance?

**Comment by gsofter** [comment]
I have tried to remove and reinstall the extension. So now the version is exactly `3.0.2`.
![image](https://user-images.githubusercontent.com/49583931/111715939-f8d66d80-8822-11eb-886a-f36335ce0db3.png)

But still, it doesn't work for me.

:roll_eyes:

**Comment by jhoffmanqualified** [comment]
Update on my end - it _kinda_ works, but appears very flaky. I haven't pinned down repro for what's breaking it, but uninstalling and reinstalling seems to fix me for a few page loads. Definitely strange.

Is there a straightforward way to install a version that's compatible with `apollo-client` 2.6.x?

**Comment by gsofter** [comment]
You can downgrade the apollo-client-devtool version.

I did build for the `v2.3.5` and then installed it.
https://github.com/apollographql/apollo-client-devtools/tree/v2.3.5

Now it works for me.

**Comment by hwillson** [comment]
Thanks all - we'll take a closer look.

**Comment by timhere** [comment]
@hwillson unfortunately it's still not working for me, I have the same issues with 3.0.2.

**Comment by dspacejs** [comment]
I'm using v3.4.7 and there's nothing showing up in devtools.

The `connectToDevTools` option is `true,` and `window.__APOLLO_CLIENT__` is also set.

There are no errors to debug it. I have no idea how to fix this. Does anyone have any ideas?

**Comment by liydaco** [comment]
I had the same issue and found an old v2 import that I forgot to change. Make sure you follow the [V2 > V3 migration guide](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/#updating-imports) and remove any v2 imports from your app.
