### ISSUE TITLE
New version doesn't resolve fragment imports?

### ISSUE THREAD

**Issue by jeffdesign** [apollographql/apollo-client-devtools#462]
Hi! I recently got my Apollo Client Devtools updated where I noticed that imported fragments no longer work. Does v3 introduce any breaking changes or is it suppose to be backwards compatible?

**Intended outcome:**
```
query Me {
  me {
    id
    ...SomeFragment
  }
}

fragment SomeFragment on User {
	displayName
}
```

**Actual outcome:**
```
#import "./fragments/SomeFragment.gql"

query Me {
  me {
    id
    ...SomeFragment
  }
}
```

**How to reproduce the issue:**
Setup a client using webpack
https://www.apollographql.com/docs/react/integrations/webpack/
I switched between Firefox that's using v2 and Chrome that's using v3 to compare changes.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.1
 - Browser chrome
 - Browser version 89.0.4389.90
 - Extension version 3.0.1

**Comment by hwillson** [comment]
Thanks @jeffdesign - if this works in v2 and not in v3, then it's definitely a regression. We'll take a look - thanks!

**Comment by macrozone** [comment]
can confirm this issue. If you click on "Run in Graphiql", your query won't work if it contains fragment.

**Comment by macrozone** [comment]
is there an easy way to downgrade? Asking because our customer also uses the dev tools for debugging and he can no longer use it now

**Comment by macrozone** [comment]
@hwillson i recommend to unpublish the current version until this is fixed. I don't think its useful in the current state. The old version worked good enough, but its tricky to install the old version.

**Comment by hwillson** [comment]
Sorry for the frustration @macrozone - we're working on fixes for this (and all outstanding issues). And we also love PR's! 🙏
