### ISSUE TITLE
Breaks Support for Import Maps

### ISSUE THREAD

**Issue by guybedford** [apollographql/apollo-client-devtools#464]
**Intended outcome:**
It should be possible to use apollo client devtools on websites that use import maps.

**Actual outcome:**
Because Apollo Client Devtools injects ES modules into the page, this causes all subsequent import maps in the page to not be processed, giving the import map error - `An import map is added after module script load was triggered.`

I've posted more information about this in https://github.com/WICG/import-maps/issues/248.

**How to reproduce the issue:**
For example, try navigating to https://generator.jspm.io/ with the extension enabled in latest chrome with import maps support (89+). The error above comes up and the page will not load further unless the extension is disabled.

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Browser version: 89
 - Extension version: 3.02

**Comment by hwillson** [comment]
Interesting - thanks @guybedford. We'll take a look!
