### ISSUE TITLE
Document explorer is no longer resizable since V3

### ISSUE THREAD

**Issue by acapro** [apollographql/apollo-client-devtools#465]
Hello :) First of all thanks for this awesome tool! 

I frequently use the document explorer in apollo tools, and since the V3 update, it is no longer resizable, at it was in V2.  

**Intended outcome:**

I can resize the document explorer and easily read the graphql docs.

**Actual outcome:**

The document explorer has a fixed size and is at times too small and hard to read the contents, since it gets smushed.

**How to reproduce the issue:**
Click `graphiql` in the apollo tools, then open the document explorer by clicking the `Docs` button, and try to make it bigger.

**Desktop (please complete the following information):**

OS: macOS 10.15.7
Browser opera
Browser version 74.0.3911.218
Extension version 3.0.1

**Comment by hwillson** [comment]
Thanks @acapro - we'll get a fix in place shortly.

**Comment by MrDoomBringer** [comment]
Hey guys! Thanks a ton for opening this issue.

Release [4.0.0](https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.0.0) introduced the more advanced Apollo Studio Explorer as a replacement to GraphiQL, and as such the documentation tab is again nicely resize-able.

Will be closing this issue for now, thanks! :-)

**Comment by cstoddart** [comment]
@MrDoomBringer I am still unable to resize the Queries, Mutations, and Cache pages.
