### ISSUE TITLE
Empty field value on boolean

### ISSUE THREAD

**Issue by edith-santacana** [apollographql/apollo-client-devtools#488]
Hello,

I am having an issue visualizing a boolean field, in my case of a type `Country`.

```
type Country {
  ...
  thisIsABool: Boolean!
  thisIsAInt: Int!
  thisIsAString: String!
}
```

This is what the Apollo Client Dev Tools is displaying when I run the `Countries` query.
![image](https://user-images.githubusercontent.com/41595951/112736103-75490a80-8f0d-11eb-88d6-c112af513ef4.png)

Is it a bug or am I doing something wrong?

_(I am using version 3.0.2)_

**Comment by hwillson** [comment]
@edith-santacana this was fixed in https://github.com/apollographql/apollo-client-devtools/pull/446 and will be included in 3.0.3 (which we're hoping to publish within the next day or two). Thanks!
