### ISSUE TITLE
Nothing but trash after v3 update

### ISSUE THREAD

**Issue by pussyslain** [apollographql/apollo-client-devtools#538]
ever since caching and other confusing features has been added, the main query editor now is unusable. The caret moves back to the top every keytroke and the autocomplete does not work well with tab. 

I'm using the chrome extension.

Please dont force users to use the new release when it's working well before.

Thanks btw

**Comment by macrozone** [comment]
I generally don't endorse this kind of complaint, but i can understand the frustration. I also think the new version was published premature and without proper testing and should be unpublished as soon as possible. Maybe one can publish it as a beta version that is optional to install?

**Comment by hwillson** [comment]
> ever since caching and other confusing features has been added, the main query editor now is unusable. 

Caching has always been part of these devtools.

> The caret moves back to the top every keytroke and the autocomplete does not work well with tab.

Can you provide more details that explain the issue, by perhaps including a small runnable reproduction or an animated gif that shows the problem?

**Comment by hwillson** [comment]
I see the issue - a fix is coming.
