### ISSUE TITLE
Why doesn't cmd-click work in apollo?

### ISSUE THREAD

**Issue by tnrich** [apollographql/apollo-client-devtools#54]
Why doesn't hitting cmd make different attributes selectable in the apollo devtools? 

A gif is worth a thousand pictures (aka 1M words):
![timing](https://user-images.githubusercontent.com/2730609/27677815-cb58c140-5c67-11e7-8d1e-fee4e56473fc.gif)

Although the above gif doesn't show it, I can confirm this doesn't work even when the docs panel is open and loaded. 
It would be awesome if this just worked. Any insights as to what's going wrong?
Thanks!

**Comment by rrdelaney** [comment]
What version of GraphiQL are you using on localhost? It might be a feature in a newer version. 

I'm currently working on updating the version we use anyway 🙂

**Comment by tnrich** [comment]
I'm using `"express-graphql": "^0.6.4"`

Is that what is providing graphiql?

**Comment by rrdelaney** [comment]
Looks like that uses GraphiQL version [0.10.1](https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js#L19).

I'll update GraphiQL and see if we get the feature for free

**Comment by stubailo** [comment]
Yeah, I think we should just upgrade and see what happens :]

**Comment by rrdelaney** [comment]
Should be resolved by #59 😄

**Comment by tnrich** [comment]
Wahoo! When will this be live?

**Comment by ramyanaga** [comment]
Should be live now!
