### ISSUE TITLE
Fast close & reconnect loop when using with websockets transport

### ISSUE THREAD

**Issue by mistic** [apollographql/apollo-client-devtools#56]
Hi @daniman @stubailo ,

This extension isn't working very well when I use `subscriptions-transpor-ws` as a network interface for the apollo client. The GQL operations are working as intended using the apollo client but when I open the dev tools and start using graphiQL shipped with this extension, right after click on the play button the onclose callback from the websocket is called and the close -> try reconnect loop started replaying every 1/2 s. 

Can you please check the problem as this is a precious tool when developing with apollo client and subscriptions-transport-ws?

**Comment by stubailo** [comment]
Oh, that's interesting! I can't imagine why that would happen since it does queries in the same way as Apollo Client does. Do you have a simple example we could run to reproduce the issue?

**Comment by mistic** [comment]
@stubailo You can use the `GitHunt-API` and the `GitHunt-React` together. Just set ` wsTransportType='full'` inside the `GitHunt-React` `config.js` file, open the dev tools and try to make a query. The same error will happen :)

**Comment by ramyanaga** [comment]
@mistic Is this issue still occurring? I've made the changes you mentioned in your last comment to Githunt-React, but I'm still able to run queries in the graphiql tab of the devtools.

**Comment by mistic** [comment]
Hey @ramyanaga It still happens exactly as I have reported :( Please assure you are making the queries over websockets and not over http.

**Comment by justinanastos** [comment]
I tested subscriptions with https://github.com/the-road-to-graphql/fullstack-apollo-subscription-example and it seems to be working now. Please let me know if this is still an issue!
