### ISSUE TITLE
Unable to Access GrapihQL/Run in GraphQL and Variables not showing up. 

### ISSUE THREAD

**Issue by axat17** [apollographql/apollo-client-devtools#564]
I am trying to see variables in Apollo Dev Tools but those are coming up as blank. Don't know if I miss any config.

Also, When I click on Run in GraphQL the entire Apollo DevTools turns blank and I have to close Chrome DevTools and Open again to see it. 

![2021-05-12_09-48-48](https://user-images.githubusercontent.com/16588397/117986355-8a37fc80-b307-11eb-9fd7-1dd99455a715.png)

![2021-05-12_09-51-08](https://user-images.githubusercontent.com/16588397/117986519-b3f12380-b307-11eb-9016-a9cc9a1c9ab5.png)

**Here what I have in Network Tab**

```
{
  "operationName": "getClientNationality",
  "variables": {
    "company": "XYZ",
    "region": "EASTERN"
  },
  "query": "query getClientNationality($company: String, $region: String) {  getRegion {    getClientNationality(region: $region, company: $company) {     nationality   }  }"
}
```

**Here is the Apollo Client setup I have.** 

```
export const testGraphQLClient = new ApolloClient({
  link: ApolloLink.from([namedLink(uri), link]),
  cache: new InMemoryCache({
    addTypename: false,
  }),
  connectToDevTools: true,
});
```

**Desktop (please complete the following information):**
 - OS: [MacOS Catalina]
 - Browser [Chrome]
 - Browser version [90.0]
 - Extension version [3.0.5]

**Comment by ajaypillay** [comment]
I've been having this exact issue as well.

OS: Fedora 34
Browser: Chrome 90.0.4430.212
Extension Version: 3.0.5

I'm running a Meteor/Apollo integration and I can connect to the Graphiql instance at `localhost:3000/graphql` but I'm unable to do so using the extension, the page is blank.

**Comment by hwillson** [comment]
We'll track this in https://github.com/apollographql/apollo-client-devtools/issues/539 - thanks!
