### ISSUE TITLE
postMessage fails when query information contains non-serializable values?

### ISSUE THREAD

**Issue by stubailo** [apollographql/apollo-client-devtools#58]
https://github.com/apollographql/apollo-client/issues/1871

Looks like it has trouble with some objects like `Date`  types which are still OK when JSON serialized and sent to a GraphQL server.

**Comment by tnrich** [comment]
Anything I can do to help fix this? Running into this issue now and am not sure how to debug it, but would love to have the apollo devtools back up and running.

**Comment by ieow** [comment]
Any update on this issue?
I am having same messages for every graphql error 
`DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error:`

It keep printing every time I try query graphql after the error.

**Comment by rohmanhm** [comment]
Weird error, but I got the same issue here.
