### ISSUE TITLE
Uncaught Error: Schema must be an instance of GraphQLSchema.

### ISSUE THREAD

**Issue by backjo** [apollographql/apollo-client-devtools#60]
Hi, 

I'm getting the following error when using the graphiql tool inside of the devtools (graphiql works fine outside of apollo devtools for 0.11.2)
latest react-apollo (1.4.3) and apollo-client(1.8.0)

Uncaught Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.

**Comment by ramyanaga** [comment]
Do you know how I can replicate this error on my computer, or can you provide us the repo you're developing on so we can further address this? In the meanwhile, apollo-client had similar issues 2 years ago, and this link might help: https://github.com/graphql/graphiql/issues/58
Thanks!

**Comment by backjo** [comment]
Let me create a sample repo

**Comment by backjo** [comment]
@ramyanaga don't even need a sample app - if you open apollo client devtool on www.githunt.com, you will see similar issue when you try to query feed items (autocomplete will not work, and if you open console for devtools, you will see err messages)

```graphql
query x {
  feed(type:HOT) {
    id
    repo
  } 
}
```

**Comment by backjo** [comment]
devtools version from web store:  2.0.1

**Comment by ramyanaga** [comment]
@backjo Looks like this error is being caused by a graphiql update. I'm currently trying to find a version of graphiql in which both intellisense and cmd+click functionality work.

**Comment by austingray** [comment]
@ramyanaga Have you had any luck figuring this out? It was working on my end when I was doing:

```
export default graphql(gqlQuery)(Component);
```

But after switching to:

```
export default compose(
  graphql(gqlQueryOne)
  graphql(gqlQueryTwo)
  graphql(gqlQueryThree)
)(Component);
```

It stopped working. Thank you!

**Comment by justinanastos** [comment]
This appears to be working now! Please re-open the issue if it happens again. Thank you @backjo 	!
