### ISSUE TITLE
Ability to stop running queries

### ISSUE THREAD

**Issue by Aides359** [apollographql/apollo-client-devtools#61]
When running a query and out of any reason the server doesn't respond the result window just loads forever. Closing and reopening the devtools is the only option to get it working again.

It would be nice to be able to cancel a running query (i.e. play-button turning into stop-button with appropriate shortcut).

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/375 - thanks!
