### ISSUE TITLE
Autocomplete in GraphiQL

### ISSUE THREAD

**Issue by amannn** [apollographql/apollo-client-devtools#66]
I've noticed that the GraphiQL inside the apollo client devtools doesn't react to ctrl+space interactions, which usually shows an auto complete for properties on GraphQL types.

Is there a specific reason for this or could this be added?

I prefer the Apollo devtools to running GraphiQL on an endpoint as the devtools are configured with the right HTTP headers. This is really helpful for my apps, as almost all of them have header based authentication.

Thanks!

**Comment by ramyanaga** [comment]
This is most likely because we updated the version of GraphiQL running inside the devtools -- I'm taking a look at it now, and we'll keep you updated on progress!

**Comment by ramyanaga** [comment]
@amannn What version of the devtools are you running? I'm not running into this issue

**Comment by amannn** [comment]
@ramyanaga Hm, that's strange. I'm using Apollo Client Developer Tools 2.0.2 and Chrome 60 on macOS Sierra. I have a German keyboard layout (QWERTZ) – not sure if that makes a difference. I'm getting neither an autocomplete while typing in field names as well as when pressing ctrl+space. In a regular GraphiQL App I don't have these issues.

**Comment by olaf89** [comment]
I have same issue, autocomplete not working Apollo Client Developer Tools 2.0.3 Chrome 60 also on Mac

**Comment by evankyle** [comment]
Same for me.  No auto complete in GraphiQL win7, chrome 60, Apollo Dev Tools 2.0.3

**Comment by TAQ2** [comment]
same here mac chrome 61 Apollo Dev Tools 2.0.4, thanks for the help

**Comment by Dermah** [comment]
For me, ctrl+space autocomplete works until i get about three levels deep into my query. So when typing out this query:

```graphql
query {
  viewer {
    email
    firstName
    bananas {
      id
      name
      seeds {
        plant
      }
    }
  }
}
```

autocomplete worked for `viewer`, `email`, `firstName` and `bananas`, but stopped working for `id`, `name`, `seeds` and `plant`.

macOS 10.13.2, Chrome 63, Apollo Dev Tools 2.0.6

**Comment by AkivaLandsberg** [comment]
Still not working for me on Apollo Dev Tools 2.1.2 , Chrome 64,  macOS 10.13.2

**Comment by xialvjun** [comment]
Still not working for me on Apollo Dev Tools 2.1.2 , Chrome 65, macOS 10.13.3

**Comment by romucci** [comment]
Not working :D

**Comment by vizo** [comment]
Still not working after one year

**Comment by deftomat** [comment]
Well, it's not working 😟

**Comment by mmun** [comment]
This was bothering me so I looked into it. It turns out that it's just a CSS issue. I've made a PR: https://github.com/apollographql/apollo-client-devtools/pull/123.

**Comment by deftomat** [comment]
@mmun AWESOME
