### ISSUE TITLE
Bump-up graph-tag version

### ISSUE THREAD

**Issue by infinityfye** [apollographql/apollo-client-devtools#69]
Can you please bump-up graphql-tag and graphql versions? Because sometimes issues like [this (issue #47)](https://github.com/apollographql/graphql-tag/issues/47) from graphql-tag pops-up when I'm testing out queries through the Dev Tools. e.g.: when I'm checking store values vs re-fetching values.

p.s. This is my first ever github issue; I hope I wan't rude or anything.

**Comment by ramyanaga** [comment]
Do you mean updating the graphql and graphql-tag versions?

**Comment by infinityfye** [comment]
Yes, issues like the ones I have mentioned earlier have been resolved in later versions of graphql-tag and graphql.

**Comment by justinanastos** [comment]
I'm going to close this issue because it hasn't been discussed for a while. If this is still an issue please re-open it!
