### ISSUE TITLE
Opt out of analytics

### ISSUE THREAD

**Issue by joshuataylor** [apollographql/apollo-client-devtools#72]
With analytics built in, would be nice to optout (unless I'm missing it somewhere?).

**Comment by stubailo** [comment]
Hi! It's really helpful for us to be able to know which features of the dev tools are most frequently used - is there a particular concern you have with it? All of the data is completely anonymous so we cant use it to track across sites or anything like that.

**Comment by joshuataylor** [comment]
Makes sense, cheers. Just always wary about extension tracking.

**Comment by stubailo** [comment]
Thanks! The Chrome Extension TOS forbid a lot of kinds of tracking, so we've been careful to follow that!

**Comment by meyer** [comment]
I’d like to opt out of analytics as well, please.
