### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by avrelaun** [apollographql/apollo-client-devtools#73]
Can we have official firefox support for this addon ?

The build from https://github.com/apollographql/apollo-client-devtools/pull/41 works for now, but it's not durable.

**Comment by tizmagik** [comment]
🤞 https://twitter.com/peggyrayzis/status/933741807942488071 😁

**Comment by fandy** [comment]
Any update on this @peggyrayzis? I would love to have this moved to FF since with Quantum it is now my browser of choice.

**Comment by peggyrayzis** [comment]
@fandy I published devtools to the Firefox addons store three weeks ago. Everything was working fine for a week until it recently got taken down. I haven't had the time to look into it and won't be able to get to it until after the holidays, unfortunately.

**Comment by maticrivo** [comment]
any news on this?

**Comment by EthanML** [comment]
This would be awesome to see happen again - though if it's not likely anytime soon perhaps the link to an FF version should be removed from the README for now.

**Comment by frankdugan3** [comment]
I haven't had any luck installing from the latest release files either. Firefox simply throws an error saying that the add-on appears to be corrupt. Are there any special steps to installing it from the release files?

**Comment by haikyuu** [comment]
maybe https://github.com/mozilla/addons/issues/450 is related

**Comment by seangransee** [comment]
Agreed that the link should be removed from the README until this is fixed.

**Comment by Extarys** [comment]
I want it :( RIP

**Comment by japrogramer** [comment]
+1

**Comment by relhtml** [comment]
What's the latest on Apollo Developer Tools support on the latest Firefox?

**Comment by takticcode** [comment]
No Firefox support yet?

**Comment by hwillson** [comment]
Firefox is supported, but currently broken. FF has pulled devtools due to its use current use of `eval`. We're using `eval` in a safe way, but even if we plead our case and can get FF to agree, I'd like to move away from using `eval` as much as possible (to prevent this from happening again in the future). I'm working on a solution to this, and hope to have this all resolved very shortly. Thanks all!

**Comment by hwillson** [comment]
Devtools 2.1.6 should now be available to Firefox users: 
https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/

Let me know if you encounter any issues. Thanks!

**Comment by drdaeman** [comment]
The link says "page not found" for me. Was the addon pulled back from the directory?

**Comment by jacobmischka** [comment]
I imagine it was, it was kinda buggy. I'm guessing it'll be back as soon as those kinks get ironed out!

**Comment by hwillson** [comment]
Arg - it was pulled again for these reasons:

> 1) Please make it clear to us which is the reason why your add-on uses eval?
>
> 2) We were not able to reproduce the final XPI with the provided source code and instructions because the Dist folder containing the final XPI is already generated.

We had already provided details for both of these items, which I guess the FF reviewers missed. I'll get it re-submitted shortly.

**Comment by benjaminsweetnam247** [comment]
any chance you can just provide the file so we can side load it for the mean time?

**Comment by go-diego-go** [comment]
any update on this?

**Comment by Spaxe** [comment]
Shouldn't this ticket be reopened? Still page not found.

**Comment by avrelaun** [comment]
Definitely should

**Comment by acrogenesis** [comment]
Is there a way we could get attention from Mozilla?

**Comment by tiagosalema** [comment]
So I am guessing there are still no updates on the addon?

**Comment by lukewlms** [comment]
@hwillson Would you reopen this till the link works?  We love Apollo and Firefox and would love them to play great together!

**Comment by hwillson** [comment]
@lukewlms for sure, and good news - @justinanastos is going to be looking into this and working out a plan of attack to prevent this from happening again.

**Comment by thomasmichaelwallace** [comment]
For the sake of other people like me who couldn't work out how to build it yourself. Here are some explicit instructions:

* Using Firefox Developer Edition (required to accept unsigned extensions)
* Allow unsigned extensions in Firefox (navigate to `about:config`, and set the key `xpinstall.signatures.required` to `false`)
* Clone, install (`yarn install`) and build (`yarn run build`) the main extension package
* Edit `shells/webextension/manifest.json` and add the following key (required to install the addon persistently):
```
  "browser_specific_settings": {
    "gecko": {
      "id": "apollo-client-devtools@whatever.com"
    }
  }
```
* Build the unsigned pacakge: `yarn run zip:firefox`
* Install the zip extension in Firefox (navigate to `about:addons`, click the cog on the right hand side, select "Install Addon From File...", and select to `dist/apollo_client_developer_tools-2.2.0.zip`)

**Comment by andreicristianpetcu** [comment]
@thomasmichaelwallace it does not work on my machine :( if you managed to build it locally and have it work for you, I can show you how to sign it and have a one click install (no need to disable signing verification).

Create an account on AMO and upload your zip at this location https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted This is for unlisted addons, they need fewer checks than normal addons on addons.mozilla.org. Once you get it signed, download the signed version and put it on the release page in a github fork. Check out how I did on [this page](https://github.com/andreicristianpetcu/google_translate_this/releases). That's it! You have your one-click-install.

If you want to maintain your builds and ship updates to the nice people in this thread, just add a [update_url in your manifest.json](https://github.com/andreicristianpetcu/google_translate_this/blob/bab2e8c1142ed5c2e0df64a6663650d799843977/manifest.json#L46) and make it point to some [update.json](https://github.com/andreicristianpetcu/google_translate_this/blob/bab2e8c1142ed5c2e0df64a6663650d799843977/updates.json) on the web. Once you update the update.json, other people will start getting your updates.

This is an official way to ship extensions that are internal or not intended for the general public. I would have done this myself but: I don't use the extension, I just help out Firefox users. Also, my build does not work, yours seems to work.

**Comment by thomasmichaelwallace** [comment]
@andreicristianpetcu - thanks for the guidance- I've just given that a go, but looks like it gets stuck again at requiring the manual justification for eval &c that the _official_ build is seemingly still waiting for the Mozilla Add-on team to allow through, so I don't hold much hope of my unlisted version beating this.

As for the build, the only two steps I am missing are "on a MacBook, using Node 8".

For convenience I've forked with my `dist` and build files committed: https://github.com/thomasmichaelwallace/apollo-client-devtools

**Comment by acrogenesis** [comment]
So I got it signed as @andreicristianpetcu said here it is: [apollo_client_developer_tools-2.2.2-fx.xpi.zip](https://github.com/apollographql/apollo-client-devtools/files/3110303/apollo_client_developer_tools-2.2.2-fx.xpi.zip)

Later this week I'll try and add the update_url to keep it updated :)

**Comment by andreicristianpetcu** [comment]
After you add the update_url users need to manually install once again. @acrogenesis
Thank you for providing this build and updates for it!

**Comment by acrogenesis** [comment]
Created the updates.json and updated the manifest so it can be updated :) here is the new link https://github.com/acrogenesis/apollo-client-devtools/releases/download/FF2.2.2/apollo_client_developer_tools-2.2.2-fx.xpi

**Comment by phatcatmatt** [comment]
Any progress on this?

**Comment by jdpaterson** [comment]
> Created the updates.json and updated the manifest so it can be updated :) here is the new link [apollo_client_developer_tools-2.2.2-fx.xpi.zip](https://github.com/acrogenesis/apollo-client-devtools/releases/download/FF2.2.2/apollo_client_developer_tools-2.2.2-fx.xpi)

I got this installed ok, but it doesn't let me scroll down in the cache view. So not entirely useful.

**Comment by woahitsraj** [comment]
@jdpaterson 
I followed @acrogenesis lead and signed the 2.5.5 version for firefox since the scroll bug was annoying me also. You can get it here

[apollo_client_developer_tools-2.2.5-fx.xpi](https://github.com/woahitsraj/apollo-client-devtools/releases/download/2.5.5/apollo_client_developer_tools-2.2.5-fx.xpi)

**Comment by meglio** [comment]
`yarn install` fails for me (checked out tag `v2.2.5`):

<img width="752" alt="image" src="https://user-images.githubusercontent.com/282177/70698713-f203a580-1d17-11ea-9faf-b91bdc2f28d4.png">

**Comment by woahitsraj** [comment]
@meglio , this is because apollo uses npm and not yarn. They have a `package-lock.json` which guarantees that fixed package versions are used in npm but not in yarn. The yarn equivalent is `yarn.lock`

**Comment by iDuuck** [comment]
It should be uploaded to the Firefox Addons Store again, when there is nothing wrong in signing the add-on, right?

**Comment by woahitsraj** [comment]
No... it looks like Firefox will let you self sign and self publish an add on if it contains `eval` but it won't let you put it on the Firefox store. I'm not sure why Apollo doesn't just do this themselves but I'm happy to publish and keep it up do date in the meantime

**Comment by wesbos** [comment]
Paged @digitarald to see if there is anything he can do here to get it back in the Firefox store. I realize they are just following the rules, but it seems Apollo has a lot on their plate right now and the browser extension isn't high on that list

**Comment by digitarald** [comment]
Thanks @wesbos, I pinged the review team on clarification for self-signed addons.

**Comment by wagnerand** [comment]
Hi all, the Mozilla [add-on policies](https://extensionworkshop.com/documentation/publish/add-on-policies/) apply to all add-ons, regardless of how they are distributed (except where stated otherwise on that page).

Using `eval()` is allowed if that is the only way to achieve the intended functionality (which must not be violating other policy rules of course).

**Comment by woahitsraj** [comment]
Perhaps it's that those of us that are using Firefox Developer Edition are able to install browser add-ons that are not on the Firefox store? I think it would be generally safer to have Apollo or someone at Apollo then sign and release the extension in a similar way to how I did it and make it available for download

**Comment by wesbos** [comment]
@wagnerand so is Apollo using eval in a safe way? Or is it a violation?

**Comment by wesbos** [comment]
Here are the two spots Apollo uses eval. 

This one seems to check for Apollo client so it can load dev tools:

https://github.com/apollographql/apollo-client-devtools/blob/master/shells/webextension/src/devtools-background.js#L39

and this one seems to inject the script tag so dev tools can get running. 

https://github.com/apollographql/apollo-client-devtools/blob/master/shells/webextension/src/devtools.js#L11-L56

**Comment by wesbos** [comment]
@wagnerand @digitarald  Could you clarify if Apollo is using it in a safe way or not?

**Comment by wagnerand** [comment]
Sorry I missed the earlier message.

Don't take this reply as an authoritative answer, you should check with your reviewer and consult or [forums](discourse.mozilla.org/c/add-ons/) for help with development practices.

> This one seems to check for Apollo client so it can load dev tools:
> /shells/webextension/src/devtools-background.js@master#L39

If I read the code write, this executes eval in the devtools, only to check if Apollo is already attached. While I doesn't seem dangarous, I believe there must be better ways to achieve this. There are a couple of devtools add-ons, maybe take a look at how others tackled this.

> and this one seems to inject the script tag so dev tools can get running.
> /shells/webextension/src/devtools.js@master#L11-L56 

Similarly I would assume there is a better way to inject a script into the devtools than `eval`ing it. Note that injecting a script and instantly removing it again can generally be seen as fishy, even with legitimate intention it looks like a bit of a hack.

**Comment by digitarald** [comment]
Ok, to restate what I read: There is definitely a need to reconsider the use of eval in some of these cases (and I can pull in DevTools people) – but only re-submitting for review can get a final answer if these uses of eval are acceptable.

@peggyrayzis, not sure if you are still working on this, but could you or somebody from the team re-submit it to Firefox AMO? We should now have the right awareness in the review team to get the right feedback.

**Comment by hughrawlinson** [comment]
@wagnerand perhaps since this is something the add-on got wrong, the firefox add-on documentation could be modified to include a guide on how to do this the "correct" way?

**Comment by bennypowers** [comment]
I noticed that Redux Dev Tools also uses `eval`:

https://github.com/zalmoxisus/redux-devtools-extension/blob/4ccdfe3a3cd24c9a0b92c148d4886a0cae9544e6/webpack/replace/JsonpMainTemplate.runtime.js#L13-L15

and React Dev Tools does as well:

https://github.com/facebook/react/blob/3e94bce765d355d74f6a60feb4addb6d196e3482/packages/react-devtools-extensions/src/main.js#L30-L44

Although the example from React's dev tools is perhaps more in line with what Mozilla is looking for.

I hope this information is helpful towards resolving this issue.

**Comment by wesbos** [comment]
@peggyrayzis @hwillson Are you able to resubmit this to FF to get it back in the store?

**Comment by digitarald** [comment]
We make sure to hold the doors wide open for you! Let me know if I can help in any way.

**Comment by rogue-agent** [comment]
> 
> 
> @jdpaterson
> I followed @acrogenesis lead and signed the 2.5.5 version for firefox since the scroll bug was annoying me also. You can get it here
> 
> [apollo_client_developer_tools-2.2.5-fx.xpi](https://github.com/woahitsraj/apollo-client-devtools/releases/download/2.5.5/apollo_client_developer_tools-2.2.5-fx.xpi)

Have you gotten to updating or is this the newest version while the review is going on?

**Comment by woahitsraj** [comment]
> > @jdpaterson
> > I followed @acrogenesis lead and signed the 2.5.5 version for firefox since the scroll bug was annoying me also. You can get it here
> > [apollo_client_developer_tools-2.2.5-fx.xpi](https://github.com/woahitsraj/apollo-client-devtools/releases/download/2.5.5/apollo_client_developer_tools-2.2.5-fx.xpi)
> 
> Have you gotten to updating or is this the newest version while the review is going on?

2.5.5 is the newest version as far as I can tell

**Comment by jaydenkieran** [comment]
React and Redux devtools work great on Firefox, which makes it a bit of a pain to switch out to Chrome whenever I have to work with a project that uses Apollo (quite often), as the Apollo devtools are just too useful _not_ to use during development but it's the one extension I can't use on Firefox.

Please consider re-submitting Apollo devtools to Mozilla for review ASAP, and if @digitarald can be across this too to help try and get this up again that'd be great. I don't _want_ to switch to Chrome to have to use this.

**Comment by hwillson** [comment]
Hi all - just a quick note to apologize for the long delay in responding to this, and our overall devtools radio silence. Apollo's OSS team has been tied up working on other projects, which means we haven't been able to give AC devtools the love it deserves. The good news is, this is all about to change. @jcreighton has recently joined Apollo and has agreed to take the lead on building a brand new / modern Apollo Client devtools experience 🎉. We're just starting to plan out what this new major version of devtools will look like, and will be involving the community every step of the way, but wanted to share that we're dedicating Apollo resources to this project starting immediately. 

Since the rewrite will take some time, in parallel we're going to look into addressing 2 main outstanding devtools issues - this one (getting re-approved as a valid Firefox add-on) and supporting the soon to be released Apollo Client 3. We're currently digesting this (and other) threads, and will post back shortly. Thanks all!

**Comment by jcreighton** [comment]
Looks like we should re-submit to get a final answer on the use of `eval` in those two instances. (Thank you for the help on this @digitarald!) That will also help guide us as we take a fresh look at the architecture for the next version.

**Comment by rogue-agent** [comment]
Took you long enough. Well atleast you are attending the community forums.

**Comment by hwillson** [comment]
@rogue-agent delays like this can be frustrating for sure, but please keep in mind we're a small team spread out over several different projects. We're focusing on consolidating some of those projects, and moving others to community stewardship, to free up more time to spend on the projects we love the most. This project is one of our favorites, and it has definitely pained us as well to not have time to help improve it. Reset assured it's going to get much better very soon.

**Comment by wesbos** [comment]
Thank you @hwillson - we really appreciate the update here!

**Comment by rogue-agent** [comment]
I thought this was corporate thing by Graphql or FB or something. I did not know there was a small team.

**Comment by mrm007** [comment]
Some of us actually pay for Apollo services. It's beyond frustrating that it's taken this much time to just _acknowledge_ the issue. Personally, I'll appreciate it more when you put your [money] where your mouth is and ship a working extension.

[money]: https://www.businesswire.com/news/home/20190612005247/en/Apollo-Raises-22-Million-Give-GraphQL-based-Data

**Comment by hwillson** [comment]
@mrm007 Thanks for paying for our services 🙇‍♂️. Hopefully the fact you're paying for them means you're getting some value out of them! 🙂 Not responding to this issue in a more timely manner is a valid criticism, and is something we're definitely trying to get better at. We're a small team, but the good news is we're growing. @jcreighton is ramping up and is going to be working closely with everyone here, to help improve our community response times and help take devtools to the next level.

**Comment by jcreighton** [comment]
@digitarald Resubmitted a little bit ago 🤞

**Comment by bennypowers** [comment]
https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/

**Comment by digitarald** [comment]
> @digitarald Resubmitted a little bit ago 🤞

Thanks so much, @jcreighton. I touched base with the addons team 🤞.

As you ramp up, please don't hesitate to get browsers/devtools to help to get the Apollo tooling to the next level 🚀.

**Comment by wesbos** [comment]
Yessss! thanks everyone! This issue can be closed :)

**Comment by robinmetral** [comment]
This is great news 🎉 

> This issue can be closed :)

Just before that, we should update the README for others to easily find the addon on Firefox 🙂 

(side note:
![Addon showing "Chrome" instead of "Firefox" in about:addons](https://user-images.githubusercontent.com/35560568/82290692-c8763680-99a7-11ea-836b-ca1ab4a22a36.png)
)

**Comment by jcreighton** [comment]
@robinmetral 😬I'll have to fix that.

**Comment by jcreighton** [comment]
Added Firefox back to the README https://github.com/apollographql/apollo-client-devtools/pull/261 🎉

**Comment by digitarald** [comment]
@jcreighton thank you. I also found a Chrome-only reference on https://www.apollographql.com/docs/react/development-testing/developer-tooling/#apollo-client-devtools.

**Comment by jcreighton** [comment]
@digitarald Good catch! I'll update that documentation (but it'll be a PR in a separate repo). 

In the meanwhile, closing this issue.

**Comment by jaydenkieran** [comment]
Thanks so much for getting this sorted. Thanks for also responding quickly after my earlier comment here asking for a resubmission. I'm sure we all appreciate being able to use this again on Firefox ❤️
