### ISSUE TITLE
GraphiQL tab spins forever if introspection queries are disallowed by server, even if the query is successful

### ISSUE THREAD

**Issue by seansfkelley** [apollographql/apollo-client-devtools#746]
**Intended outcome:** query results and status are shown even if the introspection query fails.

**Actual outcome:** results panel spins forever, occasionally retrying introspection query (per the network inspector).

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/2101409/140407783-43bfebf9-be73-4bfc-8b58-ec7a31a0df4c.png">

**How to reproduce the issue:** disable introspection on the server and try running queries against it:

```
const server = new ApolloServer({
    schema,
    introspection: false,
    ....
});
```

I checked the network tab -- I see the query I'm attempting to run through the extension coming back successfully.

**Desktop (please complete the following information):**
 - macOS 10.15.7
 - Firefox 93.0 (64-bit)
 - Extension version: 3.0.5

**Comment by alessbell** [comment]
Hi @seansfkelley 👋  Since the devtools now ship with embedded Explorer instead of GraphiQL, I'm going to close this out. Thanks!
