### ISSUE TITLE
DOMException: Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by akagomez** [apollographql/apollo-client-devtools#75]
There are two other `postMessage` related issues logged here (#64, #58), but they both seem related to passing non-serialized objects. 

In my case, a simple mutation as described in the "[Apollo User Auth w/ Email](https://www.graph.cool/docs/tutorials/react-apollo-email-oopheesaj9)" guide will throw this error if executed more than once. 

The error isn't thrown with the Apollo Dev Tools disabled.

**Comment by stubailo** [comment]
@akagomez the link to the guide seems to be incorrect; it would be super helpful to have a reproduction since we have been missing one!

**Comment by akagomez** [comment]
Whoops! Fixed the link. 

@stubailo If it doesn't turn out to be too much trouble, I'll try and cobble something together.
