### ISSUE TITLE
What are the impacts to enable apollo-devtools in production?

### ISSUE THREAD

**Issue by UknownBaguette** [apollographql/apollo-client-devtools#790]
**Intended outcome:**

Identify eventual vulnerability and performance risks to enable apollo-devtools in production, as advised in the repo [README](https://github.com/apollographql/apollo-client-devtools/blob/main/README.md?plain=1#L29)

> To enable the devtools for your application in production, pass connectToDevTools: true to the ApolloClient constructor in your application

**Actual outcome:**

Uncertainties at using the tool in production

**Comment by cheapsteak** [comment]
Hi there

Performance impact may depend on how frequently your data changes  
Currently, Apollo Client running in production mode (with `__DEV__` false) skips development-only code paths, including talking to devtools, which involves serializing and transmitting the cache 

Security wise, my understanding is that extensions (like Apollo's devtools) will be able to read from your cache

Curious to know where you land for enabling in production 🙏
