### ISSUE TITLE
"Cached Data" always empty

### ISSUE THREAD

**Issue by kaysond** [apollographql/apollo-client-devtools#816]
**Intended outcome:**
Cached Data shows data that is/was cached
![image](https://user-images.githubusercontent.com/1147328/155202602-577732e2-1df3-4b94-acc9-0151015195d9.png)

**Actual outcome:**
Cached Data is always empty

**How to reproduce the issue:**
I've posted some more details on the forums here: https://community.apollographql.com/t/im-new-to-apollo-ive-built-a-functional-app-server-client-and-now-i-have-a-few-questions-about-queries-caching-and-dev-tools/2793/2

Reproduced by repeating identical queries. Ideally, some information would show up in the "Cached Data" tab at any point, but so far it seems to be always empty.

This could be related to #815

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox (happens with Chrome too)
 - Browser version: 91.6.0esr
 - Extension version: 4.0.0

**Comment by sparrowek** [comment]
The same problem for me!
The data is shown under the CACHE tab though. Only the QUERIES panel shows an empty cache.
