### ISSUE TITLE
[Firefox] Icon for Apollo Client DevTools in Firefox DevTools is missing

### ISSUE THREAD

**Issue by ElSuture** [apollographql/apollo-client-devtools#817]
Hi,

missing Icon for Apollo Client DevTools in Firefox DevTools, see screenshot:

![2022-02-24 13_13_21-DevTools Panel added by _Apollo Client Devtools_ add-on](https://user-images.githubusercontent.com/71709819/155522728-10518e6e-bfea-4383-995b-430d171b6265.jpg)

Reinstalling the plugin did not help.

 - OS: Windows 10 20H2
 - Browser: Firefox ESR
 - Browser version: 91.5.0esr (64-Bit)
 - Extension version: 4.0.0

Do not hesitate for further questions.

Best regards,
ElSuture

**Comment by kud** [comment]
Same there: 
<img width="115" alt="screenshot-2023-03-23-18-53-21@2x" src="https://user-images.githubusercontent.com/655838/227301096-bf0c1038-8de5-4b5b-9e3f-20da8d73c90f.png">

**Comment by phryneas** [comment]
I can verify this behavior.
