### ISSUE TITLE
Failing network calls on Explorer Tab

### ISSUE THREAD

**Issue by andrewkowalik** [apollographql/apollo-client-devtools#823]
**Intended outcome:**
View the explorer tab

**Actual outcome:**
The tab fails to load. I have been using the tool for a while and starting yesterday, everytime I visited the explorer tab, I received a Heroku app error page. Today when visiting the explorer tab, I get an error page 

"The webpage at https://explorer.embed.apollographql.com/?sendRequestsFrom=parent&shouldPersistState=false&showHeadersAndEnvVars=false&theme=dark might be temporarily down or it may have moved permanently to a new web address."

Nobody else on the team has been able to replicate this problem and nothing material that I can think of has changed on my end. I am wondering if there is a misconfiguration in my network settings or something else is at play here.

**How to reproduce the issue:**
Go to the network tab.

I have tried chrome and firefox.
Uninstalling/instlaling the extension.
Different DNS settings.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox/Chrome
 - Extension version 4.0.0

**Comment by andrewkowalik** [comment]
Update:

The explorer tab began working on day 3. Going to leave this open in case there was something more to this on apollo's end. I am only assuming so since it looks like the HTML in the explorer tab is being served from Heroku.

**Comment by jpvajda** [comment]
@andrewkowalik Thanks for reporting this, we are actually looking at a few related issues so I'm going to close this one out for now as I believe it's covered in other issues people have been reporting.
