### ISSUE TITLE
Display apollo tracing data in devtools

### ISSUE THREAD

**Issue by slorber** [apollographql/apollo-client-devtools#83]
Hi,

Currently, Apollo tracing data can be displayed on Apollo Engine. 

It could be useful to allow developers to view tracing informations directly in this devtools as well, as the setup would be more simple and wouldn't need a proxy.

My usecase is that I can't guarantee that my team will adopt Apollo Engine for different reasons (timing, setup, pricing model, performance impact...) but I certainly want myself to easily be able to get dev insights on the perf of our graph queries.

**Comment by acoll** [comment]
I can put together a pull request for this. I did something similar with just the graphiql package. I put together a rough gist (the styles are bad).
https://gist.github.com/acoll/a83494430fc3a394504b646622fab422

My thoughts here were to show bars representing the duration and offsets for each resolver as well as showing the actual metric values for duration in milliseconds and the duration percentage of the total query duration.

Here is an example of what it could look like:
![image](https://user-images.githubusercontent.com/1021013/37562969-e4493696-2a4b-11e8-93cb-ab9e369fb44d.png)

What are the maintainers thoughts here?

**Comment by slorber** [comment]
Hi,

I think it would be better to have the same UI on Apollo Engine and on devtools. Maybe Apollo team could publish their UI lib for that?

If that's complicated or not possible, any good enough UI would still be helpful

**Comment by justinanastos** [comment]
This is an awesome idea. This is something we're discussing internally but we haven't started work on it yet. There's an open PR right now from the community (https://github.com/apollographql/apollo-client-devtools/pull/162) but I think it needs some work because, as @cheapsteak pointed out, the UI is hard to navigate.

I'm going to add `enhancement` label to this and keep it up. Thanks!

**Comment by hwillson** [comment]
Moved to https://github.com/apollographql/apollo-client-devtools/discussions/376 - thanks!
