### ISSUE TITLE
Weird layout issues when the explorer loads

### ISSUE THREAD

**Issue by heyitsaamir** [apollographql/apollo-client-devtools#855]
**Intended outcome:**
Load apollo dev tools successfully

**Actual outcome:**
It loaded, but it's not very usable because the explorer loads _under_ the panels

<img width="1702" alt="image" src="https://user-images.githubusercontent.com/48929123/164315718-39b4aaad-85d1-4255-8f15-99610cbe8d00.png">

**How to reproduce the issue:**
Simply load the extension

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser firefox
 - Browser version 99.0.1
 - Extension version 4.0.0

**Comment by heyitsaamir** [comment]
Ah, when you click on "Explorer", the layout fixes itself.

Since this is a pretty simple workaround, we can close this, but it's still worth fixing imo. I'll let admins decide.

**Comment by DanielPower** [comment]
I'm seeing this on Firefox as well, and couldn't figure out how to resolve it. It seems **only** switching to the "Explorer" tab solves it. I had tried switching to the other tabs, refreshing, and restarting my browser before searching and finding this thread.

The extension is basically broken unless you happen to know to or try to switch to the explore tab.

**Comment by metawise** [comment]
I'm experiencing same issue. @heyitsaamir suggestion worked. I agree it's worth to fix, little bit annoying.

**Comment by alessbell** [comment]
This was resolved in [v4.1.6](https://github.com/apollographql/apollo-client-devtools/releases/tag/v4.1.6) which should hit the extension/addon stores in the next 24H.
