### ISSUE TITLE
Issue with both SSR and Store Tab trigger before executing a GraphQL query on the client

### ISSUE THREAD

**Issue by oredi** [apollographql/apollo-client-devtools#87]
1. Apollo Queries and state populated using SSR is not read by DevTools on initial load
![screen shot 2017-11-20 at 8 41 47 am](https://user-images.githubusercontent.com/637249/33129853-5fa7987a-cf5f-11e7-82d7-cab602e07006.png)
2. Apollo Devtools show a blank screen and could not be used till Chrome is restart
![screen shot 2017-11-20 at 8 42 01 am](https://user-images.githubusercontent.com/637249/33129899-81645f84-cf5f-11e7-8813-75109fffb5f5.png)

Chrome Version: 59.0.3071.104
Apollo DevTools Version: 2.0.5 (Installed via Chrome Extensions)
Host: Debian 9.0
Apollo Packages used:
```
"apollo-cache-inmemory": "1.1.1",
"apollo-client": "2.0.3",
"apollo-link": "1.0.3",
"apollo-link-error": "1.0.1",
"apollo-link-http": "1.2.0",
"apollo-server-express": "1.2.0"
```
Code used to reproduce this https://github.com/oredi/react-apollo-auth

The same code and setup works though if I trigger a GraphQL call to the server on my Client App before using the Queries and Store tab in Apollo Client DevTools.
![screen shot 2017-11-20 at 8 46 41 am](https://user-images.githubusercontent.com/637249/33130014-eb5f3a62-cf5f-11e7-9046-021c1c44dcbd.png)
![screen shot 2017-11-20 at 8 46 53 am](https://user-images.githubusercontent.com/637249/33130029-f44dbe46-cf5f-11e7-9688-eb4c776faa0d.png)

Am I missing something in my App or doing something wrong with the configuration?

**Comment by SeanSilke** [comment]
@ramyanaga  @daniman Can you please give some respond?
This type of critical flaws in software behaviour can give lot of frustration to users.

**Comment by justinanastos** [comment]
@SeanSilke I'm sorry no one ever responded to this issue! I'm taking over triage of this repo and I'm here to help. I'm going to close it out for now. If you're still seeing an issue please re-open!
