### ISSUE TITLE
Store Tab exception

### ISSUE THREAD

**Issue by joesankey** [apollographql/apollo-client-devtools#88]
"apollo-client": "2.0.1"
Apollo Client Developer Tools 2.0.6

The devtools appear to crash when I click on the store tab.

Seeing the following stack trace:

```
index_bundle.js:824 TypeError: Cannot read property 'inspector' of undefined
    at Inspector.componentWillReceiveProps (index_bundle.js:91844)
    at updateClassInstance (index_bundle.js:779)
    at beginWork (index_bundle.js:787)
    at e (index_bundle.js:819)
    at k (index_bundle.js:820)
    at p (index_bundle.js:821)
    at y (index_bundle.js:825)
    at D (index_bundle.js:824)
    at Object.enqueueSetState (index_bundle.js:777)
    at Panel.v.setState (index_bundle.js:359)
```
![screen shot 2017-11-22 at 06 07 56](https://user-images.githubusercontent.com/323735/33131530-ab67e33c-cf4b-11e7-84b0-ee300d12e6a9.png)

**Comment by dchambers** [comment]
I definitely didn't use to have this issue, so does anyone know where we can find the older versions (e.g. 2.0.5) as I believe it's possible to install older versions manually?

**Comment by SeanSilke** [comment]
@ramyanaga  @daniman Can you please give some respond?
This type of critical flaws in software behaviour can give lot of frustration to users.

**Comment by daniman** [comment]
We've been working on some stability improvements to the devtools recently that I hope will solve this problem! We're planning to release them soon, but I'm not sure of the exact timeline.

**Comment by SeanSilke** [comment]
@daniman Thank you for clearing situation.

**Comment by justinanastos** [comment]
Thanks for the everyone's participation in this issue. I'm going to close this issue for now hoping that it's resolved in a more recent version of devtools. If this is still an issue with the latest version, please re-open the issue!
