### ISSUE TITLE
GraphiQL convert null to "null"

### ISSUE THREAD

**Issue by linonetwo** [apollographql/apollo-client-devtools#9]
Seems null variable will be convert to "null" if that field accepts String, look at this:

```javascript
`/api/alarm/company?pz=${pageSize}&pi=${pageIndex}&ob=${orderBy}&ft=${fromTime}&tt=${toTime}&ac=${alarmCodes.join(',')}&ct=${confirmed}`
```

![_20161216120145](https://cloud.githubusercontent.com/assets/3746270/21251324/f3072fca-c387-11e6-96f2-55f7e1f171dd.png)

As https://github.com/apollostack/apollo-client-devtools/issues/5 , seems this GraphiQL have some differences from what inside apollo-server.

**Comment by stubailo** [comment]
Wait I'm confused - the thing you posted doesn't look like a graphql query at all?

**Comment by linonetwo** [comment]
Oh, I'm wrapping REST behind GraphQL ... Just likes we discussed few months ago https://github.com/apollostack/apollo-client/issues/379

Though this issue is true.

**Comment by stubailo** [comment]
Yeah definitely looks like there is something fishy going on. I don't have time to look at it in the next few days but hopefully someone can check it out!

**Comment by ramyanaga** [comment]
@linonetwo Is this still an issue? If so, can you give us more info on when/how this is occurring? We haven't been able to replicate this error, so more context would be useful.

**Comment by linonetwo** [comment]
I'm closing this since it's not a common case.
