### ISSUE TITLE
Schema must be an instance of GraphQLSchema

### ISSUE THREAD

**Issue by carlosbaraza** [apollographql/apollo-client-devtools#90]
Apollo Client: 2.0.4
Apollo Client Devtools: 2.0.6

Unfortunately, this extension is completely crashing. This is the stack trace. I tried to debug the first error and the `schema` variable is actually a `GraphQLSchema` instance, just not a `_schema.GraphQLSchema` instance.

<img width="1280" alt="screen shot 2017-12-21 at 3 36 53 am" src="https://user-images.githubusercontent.com/1270425/34238195-c4b59f70-e600-11e7-8131-3f357000ca8c.png">

This is the white screen presented when clicking in "Store".

<img width="508" alt="screen shot 2017-12-21 at 3 36 37 am" src="https://user-images.githubusercontent.com/1270425/34238215-d8791596-e600-11e7-9d15-94cc4e2fc961.png">

**Comment by einarlove** [comment]
Experienced the same error, and other times I get this:
<img width="878" alt="screen shot 2018-01-11 at 10 26 57" src="https://user-images.githubusercontent.com/1495211/34866890-6e9a0678-f77e-11e7-9647-235955a030db.png">

**Comment by AndyBan** [comment]
The current release of the Chrome extension works fine on https://www.githunt.com/ but not my local project which gives the same errors as the above.  I rebuilt the extension using the latest packages and after a short time getting those inspector messages it has started working.  Not sure why the inspector bits have started working as I didn't do anything, timing issue maybe?  I'd submit a PR but I am not sure if its actually the fix.  

I did try downgrading the package versions to those used in the githunt repo in my project but that didn't help. 

 package.json      | 16 ++++++++--------
 webpack.config.js |  1 -
 2 files changed, 8 insertions(+), 9 deletions(-)

diff --git a/package.json b/package.json
index 26f7040..4ed4497 100644
--- a/package.json
+++ b/package.json
@@ -12,25 +12,25 @@
   "devDependencies": {
     "babel-cli": "^6.11.4",
     "babel-core": "^6.18.2",
-    "babel-loader": "^6.2.9",
+    "babel-loader": "^7.1.2",
     "babel-plugin-transform-class-properties": "^6.11.5",
     "babel-plugin-transform-exponentiation-operator": "^6.8.0",
     "babel-preset-es2015": "^6.13.2",
     "babel-preset-react": "^6.16.0",
-    "css-loader": "^0.26.1",
+    "css-loader": "^0.28.9",
     "html-webpack-plugin": "^2.24.1",
     "json-loader": "^0.5.4",
     "less": "^2.7.1",
-    "less-loader": "^2.2.3",
+    "less-loader": "^4.0.5",
     "prettier": "^1.5.2",
-    "style-loader": "^0.13.1",
-    "webpack": "^1.13.3"
+    "style-loader": "^0.19.1",
+    "webpack": "^3.10.0"
   },
   "dependencies": {
-    "apollo-utilities": "^0.2.0-rc.0",
+    "apollo-utilities": "^1.0.4",
     "classnames": "^2.2.5",
-    "graphiql": "0.11.4",
-    "graphql": "^0.11.7",
+    "graphiql": "0.11.11",
+    "graphql": "^0.12.3",
     "graphql-syntax-highlighter-react": "^0.3.0",
     "lodash.flattendeep": "^4.4.0",
     "lodash.pickby": "^4.6.0",
diff --git a/webpack.config.js b/webpack.config.js
index 6c599f3..0996df4 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -41,7 +41,6 @@ module.exports = {
       },
       {
         test: /\.js$/,
-        include: __dirname + '/app',
         loader: "babel-loader",
         exclude: /(node_modules)/
       }

**Comment by caedmon** [comment]
I ran into this as well.  Was working and then for no apparent reason this problem appears.  What cured it for me (at least for now) was going into chrome extensions and clicking Reload on the Apollo devtools extension.

**Comment by justinanastos** [comment]
Thanks for reporting this issue. I'm hoping that things are resolved with a more recent version of devtools because there hasn't been any activity for a while. If that's not the case then please re-open the issue and let me know!
