### ISSUE TITLE
Devtools coming up strange (Devtools v2.0.6 against Apollo client v2.0.2)

### ISSUE THREAD

**Issue by 1attice** [apollographql/apollo-client-devtools#92]
Everything worked great till I bumped to Apollo Client 2.x and now the devtools don't work (and I'm running v2.0.6)

Symptoms: 
- The graphiql component works fine (but so what)
- The mutation and query watchers never see any queries
- The store inspector is a completely blank screen (!)
- _APOLLO_CLIENT_ and _APOLLO_DEVTOOLS_GLOBAL_HOOK_ are both present

Very boring screenshot of 'Store':

![image](https://user-images.githubusercontent.com/315987/34854380-4607f84a-f6ee-11e7-9dcd-09a74b8b0dbe.png)

**Comment by liz-mars** [comment]
And FWIW here's my relatively boring apollo config:

```
const mkcache = (introspectionQueryResultData: Object) => {
  // from recipe at  https://www.apollographql.com/docs/react/recipes/fragment-matching.html
  // added to shut up 'heuristic matched fragment' warning in container/forecast.jsx
  const fragmentMatcher = new IntrospectionFragmentMatcher({ introspectionQueryResultData })
  return new InMemoryCache({ fragmentMatcher })
}

// adapted from https://www.apollographql.com/docs/react/features/error-handling.html
const erroneous = ({ response, graphQLErrors, networkError }) => {
  const errs = []
  if (graphQLErrors) {
    errs.push(...graphQLErrors.map(({ message, locations, path }) =>
      `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`))
  }
  if (networkError) {
    errs.push(`[Network error]: ${networkError}`)
  } else {
    response.errors = null
  }
  console.log('hi I definitely got called')
  setErr(errs.join('\n'))
}

const mklink = (token: string, uri: string) => {
  const httpLink = createHttpLink({ uri })
  const errLink = onError(erroneous)
  const authLink = setContext(() => ({
    headers: {
      authorization: getAuth(token),
    },
  }))
  return from([errLink, authLink, httpLink])
}

export const mkclient = (link: Object) => (
  new ApolloClient({
    connectToDevTools: true,
    cache: mkcache(fragmentTypes),
    link, 
  })
)

// Bring it all together. The Apollo Client.


export const client = mkclient(mklink(JWT_LOCALSTORAGE, GRAPHQL_ENDPOINT))
```

**Comment by liz-mars** [comment]
Any movement on this? :)

**Comment by liz-mars** [comment]
My workaround has been -- and this is ugly as hell -- to use Wireshark and good filtering IPF ruleset to grab the actual queries and return values. It's a fiddle to set up, but it works reasonably well, if/when you're familiar with Wireshark. Caveats: Wireshark is a spiny fish of a friend, and it's easy to get jabbed; also, this only works if your development environment is not using HTTPS (which is a reasonable expectation for developing at `localhost:8080` or similar, but not so reasonable if you're chasing bugs on staging or production)

**Comment by liz-mars** [comment]
Ultimately there's no substitute for good devtools, however, and I'm glad I hadn't gotten around to moving everything over to apollo-state-link. Redux wins this round, hands down and, for my project, permanently.

**Comment by liz-mars** [comment]
@myovchev  interestingly, we're both on Ubuntu. Could be a clue? I mean, probably not, but...

**Comment by jvbianchi** [comment]
I had the same problem and this https://github.com/apollographql/apollo-client-devtools/issues/106#issuecomment-368752638 solved for me

**Comment by justinanastos** [comment]
Thanks for reporting this issue! I just joined the devtools project and I'm going through all the open issues. Was this resolved with https://github.com/apollographql/apollo-client-devtools/issues/106#issuecomment-368752638 ?

If so, then it will also relate to https://github.com/apollographql/apollo-client-devtools/issues/118

**Comment by justinanastos** [comment]
I'm going to close this issue and keep an eye out for a response. If I hear back that things are still not working then I'll re-open the issue. Thanks again!
