### ISSUE TITLE
Error thrown whenever Chrome Dev Tools is opened and PixiJS Dev Tools are installed - `TypeError: i.includes is not a function`

### ISSUE THREAD

**Issue by glennflanagan** [apollographql/apollo-client-devtools#923]
**Intended outcome:**

I don't see the error each time I open the Chrome Dev Tools

**Actual outcome:**

Whenever I open the Chrome Dev Tools with this extension installed an error is thrown in the console 
<img width="1134" alt="Screenshot 2022-09-30 at 11 29 53" src="https://user-images.githubusercontent.com/5485364/193251985-96771707-044e-4ff3-844b-c00211d1fedb.png">

**How to reproduce the issue:**

Install the Apollo dev tools extension
Install the[ PixiJS dev tools extension ](https://chrome.google.com/webstore/detail/pixijs-devtools/aamddddknhcagpehecnhphigffljadon)
Open any new web page
Open the Chrome Dev Tools
Observe the error in the console

---
<img width="2557" alt="Screenshot 2022-09-30 at 11 36 21" src="https://user-images.githubusercontent.com/5485364/193252432-4100ec99-11eb-4026-a735-256e0c192e3c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser version: 105.0.5195.125 (Official Build) (x86_64)
 - Extension version: 4.1.1

**Comment by glennflanagan** [comment]
Is occurring here.
<img width="659" alt="Screenshot 2022-09-30 at 11 40 00" src="https://user-images.githubusercontent.com/5485364/193252764-21e6d50a-8f59-4fd8-adb5-12550cdd030b.png">

**Comment by glennflanagan** [comment]
Ah, it seems there is a conflict with the PixiJS Dev Tools extension. The `message.to` is a number in that instance.
<img width="320" alt="Screenshot 2022-09-30 at 11 44 57" src="https://user-images.githubusercontent.com/5485364/193253581-d0eaaa04-101f-4313-b498-c16bc2a94c39.png">

**Comment by alessbell** [comment]
Hi @glennflanagan 👋 Since this is a conflict between two plugins and there's a reasonable workaround (disabling the PixiJS plugin), I'm going to close this issue out. Thanks!
