### ISSUE TITLE
🐛 Extension installed but tab does not show up in chrome developer tools

### ISSUE THREAD

**Issue by josecolella** [apollographql/apollo-client-devtools#924]
**Intended outcome:**

Use the apollo chrome dev tools

**Actual outcome:**

No tab appears when opening the developer tools

<img width="1574" alt="image" src="https://user-images.githubusercontent.com/1974588/194161074-860d0ed6-2009-49e8-b485-a50219905a49.png">

**How to reproduce the issue:**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 12.6
 - Browser Chrome
 - Browser version Version 106.0.5249.61 (Official Build) (x86_64)
 - Extension version 4.1.2

**Comment by joeshub** [comment]
Same

**Comment by adityaprasoon** [comment]
+1

**Comment by andrewli-ca** [comment]
same for me

**Comment by cmontedonico** [comment]
+1

**Comment by vfaramond** [comment]
Same here, solved by passing `connectToDevTools: true` to the `ApolloClient` constructor in your app when running locally.

**Comment by phugodness** [comment]
+1 me too, it doesn't show up recently. I tried firefox and chrome :/

**Comment by joeshub** [comment]
> Same here, solved by passing `connectToDevTools: true` to the `ApolloClient` constructor in your app when running locally.

thanks for this workaround. fwiw it seems like [calculating __DEV__](https://github.com/apollographql/apollo-client/blob/efdbae05065bfc93e051203e0fbb396eb926830d/src/utilities/globals/DEV.ts#L10) might be the issue I'm always seeing false... not sure tbh

**Comment by thommor** [comment]
I have the same issue on both Chrome and Firefox

**Comment by hwillson** [comment]
Thanks all, we're looking into this. Can anyone share the version of `@apollo/client` they're seeing this happen with?

**Comment by thommor** [comment]
> Thanks all, we're looking into this. Can anyone share the version of `@apollo/client` they're seeing this happen with?

I'm running @apollo/client 3.6.9

**Comment by MrDoomBringer** [comment]
@josecolella Thanks so much for opening the issue! I've been looking into this today, and was wondering if there was any way you could create a reproduction repository for this? Any example of a client that, when viewed, doesn't show the "Apollo" devtools tab would be perfect. Haven't yet been able to reproduce this locally on AC `3.6.9` or `3.7.0` with DevTools `4.12`

**Comment by josecolella** [comment]
@MrDoomBringer The repository I'm working on is my companies, so I will have to see if I can create a reproducible repo with the issue. The version I'm on is "@apollo/client": "^3.7.0",

**Comment by MrDoomBringer** [comment]
Hey @josecolella, we just published AC Devtools `v4.1.3` on the Chrome webstore, could you let us know if this resolves your issue? You might need to restart chrome (url: `chrome://restart`) for the changes to take affect. Thanks!

**Comment by tommcquarrie** [comment]
So I had this same issue and the `connectToDevTools: true` workaround got the apollo tab showing in devtools, but I also noticed executed graphql queries weren't showing on the queries tab (mutations are showing correctly).  Upgrading to devtools 4.1.3 got the apollo devtools showing, but queries are still missing.  Happy to raise this as a separate bug if considered necessary.

**Comment by sethc2** [comment]
I can confirm it is now working as expected on Chrome. (i.e no need for `connectToDevTools: true` anymore).

**Comment by josecolella** [comment]
@MrDoomBringer Updating to the latest extension versions has fixed the issue. Thanks
