### ISSUE TITLE
Apollo shows up in list in Chrome dev tools but doesn't load

### ISSUE THREAD

**Issue by wildpow** [apollographql/apollo-client-devtools#94]
Inspected the inspector like the readme says and this is the error I get.
```Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:93369:13)
    at __webpack_require__ (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:20:30)
    at Object.<anonymous> (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:70:23)
    at __webpack_require__ (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:20:30)
    at Object.<anonymous> (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:47:19)
    at __webpack_require__ (chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:20:30)
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:40:18
    at chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/dist/index_bundle.js:43:10```

**Comment by neurofoo** [comment]
I'm having the same issue. I have one line above what you wrote, which is:

`Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.`

Seems to be an issue with the iframe not being able to access localStorage. I tried allowing third parties to set cookies in the chrome settings, but still no luck.

**Comment by neurofoo** [comment]
So. Allowing third-parties does work... sometimes. I have to reload the page several times. Once in a while the 'A' icons turns black and I can see the tools. Not optimal.

**Comment by datanotion** [comment]
Same issue here.  Haven't been able to use the panel in a while now.  Even with multiple refreshes it won't enable for me.

**Comment by matthew-gordon** [comment]
I was having the same problem. Apollo dev tools had previously worked seamlessly, until I blocked third party cookies. Couldn't figure out the issue either until undocking the dev tools, inspecting the devtools, and finding the 

```Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.```

I allowed third party cookies, then cleared my local storage. Dev tools reconnected to my graphql api and is now working as expected. 

pretty tricky to diagnose. Thanks @neurofoo, Not optimal.

**Comment by WizardOfOgz** [comment]
I did not want to grant all sites third party sites access to cookies by default, so I allowed an exception for just the Apollo Devtools extension `chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/`.

**Comment by basicdays** [comment]
@WizardOfOgz is the true wizard on this one. I knew there should have been a way to whitelist the extension, I just had no idea what incantation was needed to allow it through. I can now keep 3rd party cookies blocked, *and* still use this extension. This really should be added to the documentation somewhere.

To detail the fix on Chrome, go to the following URL to fix the error:
chrome://settings/content/cookies

And add the following for the extension under Allow:
`chrome-extension://jdkknkkbebbapilgoeccciglkfbmbnfm/`

**Comment by justinanastos** [comment]
This one seems to keep popping up! Thanks for everyone's help in finding a temporary solution until we resolve #118. In the meantime I'm going to close this as a duplicate. Thanks again!
