### ISSUE TITLE
Devtools repo could use TSC CI/CD

### ISSUE THREAD

**Issue by MrDoomBringer** [apollographql/apollo-client-devtools#944]
We should run `tsc` during our CI/CD pipeline to ensure we aren't getting any typescript errors with pull requests

https://github.com/marketplace/actions/typescript-compiler could be helpful for this

**Comment by alessbell** [comment]
`ts-jest` should throw TS errors, and the test job is running on CI, so this probably isn't needed.

**Comment by MrDoomBringer** [comment]
@alessbell good point, I'm now curious as why that test didn't run on https://github.com/apollographql/apollo-client-devtools/pull/919

**Comment by alessbell** [comment]
Hmm, good question @MrDoomBringer, since the author is a first-time contributor it's possible they signed the CLA after opening the PR, which has caused issues with CCI PR jobs in the past... maybe try closing + re-opening the PR?

**Comment by alessbell** [comment]
Now that the test job is running against forks, we can see ts-jest indeed fails the test job on tsc error: https://app.circleci.com/pipelines/github/apollographql/apollo-client-devtools/5885/workflows/b1d3d92f-a99b-43a4-84e6-f3d5b78ee2b4/jobs/5892

Closing as not planned.
