### ISSUE TITLE
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### ISSUE THREAD

**Issue by PtwHub** [apollographql/apollo-client-devtools#96]
I have a working react-graphql application that uses an api server on a separate port. It sets the Access-Control-Allow-Origin header via the pre-flight OPTIONS fine. No problem. I open the apollo-client-devtools in chrome and can see my Introspection results/schema in the "Store". Now I go to the GraphiQL in the same apollo-client-devtools editor and enter a simple (known working) query. What I get is then:

`Failed to load http://localhost:62261/graphql: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 500. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Where can I set the {'mode': 'no-cors'} ? Or any other tips?

Thanks

**Comment by mmiller-callibrity** [comment]
500 is not a valid response status from an OPTIONS request. What does your network tab in your browser devtools look like?

**Comment by PtwHub** [comment]
Thanks. Indeed, the server's 500 should have been something else, but it wasn't in this case. The problem was still the CORS. The difficulty I had was that the graphql-dotnet server is using a middleware approach without the standard CORS hooks. Here is the code that I had to add in the GraphQLMiddleware.cs class, which may not be perfect, but does the job. Thanks again.

`        private async Task<bool> BeginInvoke(HttpContext context)
        {
            //if (context.Request.Method == "OPTIONS") {
            context.Response.Headers.Add("Access-Control-Allow-Origin", new[] { (string)context.Request.Headers["Origin"] });
            context.Response.Headers.Add("Access-Control-Allow-Headers", new[] { "Origin, X-Requested-With, Content-Type, Accept" });
            context.Response.Headers.Add("Access-Control-Allow-Methods", new[] { "GET, POST, PUT, DELETE, OPTIONS" });
            context.Response.Headers.Add("Access-Control-Allow-Credentials", new[] { "true" });
            if (context.Request.Method == "OPTIONS")
            {
                context.Response.StatusCode = 200;
                await context.Response.WriteAsync("OK");
                return true;
            }
            return false;
        }`

AND:

`       public async Task Invoke(HttpContext context, ISchema schema)
        {
            if (await BeginInvoke(context)) return;
            if (!IsGraphQLRequest(context))
            {
                await _next(context);
                return;
            }

            await ExecuteAsync(context, schema);
        }`
