### ISSUE TITLE
Content Security Policy issue with version 2.1.0

### ISSUE THREAD

**Issue by jole78** [apollographql/apollo-client-devtools#99]
Hi,

just wanted to report this error that I'm getting on 2.1.0 

My site is using some CSP headers and the console is now filled with these. It still works though so it's not a major thing.

> Refused to connect to 'https://devtools.apollodata.com/graphql' because it violates the following Content Security Policy directive: "connect-src 'self' ws: localhost:3000".

```
Uncaught (in promise) TypeError: Failed to fetch
    at <anonymous>:1:904
    at n.checkVersions (backend.js:1)
    at n.initBackend (backend.js:1)
    at e (backend.js:1)
    at e (backend.js:1)
```

**Comment by jbaxleyiii** [comment]
@jole78 interesting! I'll get a fix out ASAP! Thanks!

**Comment by jole78** [comment]
@jbaxleyiii can confirm it now works on 2.1.1 ...thx...closing the issue!

**Comment by jole78** [comment]
@jbaxleyiii sorry...I spoke too soon...still errors on 2.1.1 (maybe the fix wasn't in that release after all).

**Comment by meyer** [comment]
@jbaxleyiii why would the Apollo Dev Tools extension need to talk to apollodata.com? Analytics?

**Comment by sheerun** [comment]
Same question, is it really necessary? Can I opt-out?

**Comment by meyer** [comment]
turns out it sends usage info to Google Analytics too :/

i can't use a browser extension that phones home on my work computer. until this issue is fixed i'm using [a fork that doesn't include analytics](https://github.com/meyer/apollo-client-devtools-minus-tracking/commit/20857ef27ad9d397218e0678a4bddb4120ca6310).

**Comment by JayKan** [comment]
Can confirm current issue still exists in version `v2.2.2`
